### ISSUE TITLE
Order of insertion matters when using captures

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#1026]
It should be the case that order of document insertion does not matter when using captures. However, while working through a problem we encountered a case where referring to a document before inserting it resulted in a schema error.

@GavinMendelGleason please if you can, supply the example where we encountered this.

**Comment by GavinMendelGleason** [comment]
https://github.com/terminusdb-labs/nmdc/blob/main/ingest.py

This contains the schema along with a document list which if permuted to place the Study after the Bio-sample, will fail.

**Comment by spl** [comment]
Fixed by https://github.com/terminusdb/terminusdb/pull/1047.
