### ISSUE TITLE
cli integration tests reinitializes store rather than create a test one, then fail

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#1085]
It looks like the cli integration tests intend to create a storage/ folder in the tests/ directory using the terminusdb.sh script. However, when run locally, against a locally built terminusdb binary, this actually does not create a storage/ folder inside of tests/, but reinitializes the storage directory one directory up, then fail the test run because afterwards it is unable to delete tests/storage.

Reinitializing local store is bad!

**Comment by spl** [comment]
The problem was that some environment variables were set that `terminusdb` used.

**Comment by matko** [comment]
The issue was caused by environment variables in Gavin's system overriding the location of the storage directory. After unsetting those, the store directory is initialized in the proper place.

It'd still be a good idea if these tests did not force reinitialization, but instead errored when encountering a storage directory when none is expected.

**Comment by spl** [comment]
Reopening because I have a solution.
