### ISSUE TITLE
WOQL : Importing data from CSV and inserting it in terminusdb not working

### ISSUE THREAD

**Issue by Neelterminusdb** [terminusdb/terminusdb#1087]
**Describe the bug**
Not able to insert data from csv using woql. See following query:

```js
const result = await client.query(
        WOQL.and(
            WOQL.get(
                WOQL.as('Name', name)
                    .as('Team', team)
                    .as('Title', title)
            ).post("Employees.csv"),
            WOQL.insert_document(new WOQL.doc({'@type' : 'Employee',
                                               name : name,
                                               team : team,
                                               title : title}))
        )
    )
```
**To Reproduce**
Run the above query using js client

**Expected behavior**
It should read the csv file and insert the documents into terminusdb

**Comment by hoijnet** [comment]
Wow, love the `WOQL.doc` way of expressing WOQL documents, looks beautiful and straightforward! This will be awesome once the serverside is fixed too!

**Comment by hoijnet** [comment]
Looks like this is now working with the latest javascript client. If a variable is added for `"@id": "v:docid", it fails with `Error: API Error api:message Error: key_has_unknown_prefix("v:docid")`.

Thinking the below should be possible, in including the definition for the ID too?

```
const result = await client.query(
        WOQL.and(
            WOQL.get(
                WOQL.as('Name', name)
                    .as('Team', team)
                    .as('Title', title)
            ).post("Employees.csv"),
            WOQL.unique("", [name,title], "v:_docid"),
            WOQL.idgen("Employee/", ["v:_docid"], "v:docid"),
            WOQL.insert_document(new WOQL.doc({'@type' : 'Employee',
                                               '@id' : 'v:docid',
                                               name : name,
                                               team : team,
                                               title : title}))
        )
    )
```

Unsure if I'm doing something wrong. If I just add `"@id": "Employee/test"` it works, and if I look at the bindings I get back, `v:docid` looks allright too. Same result if replacing `unique` and `idgen` with `WOQL.concat(["Employee", "/", "test"], "v:docid")`. I get the same error about the unknown prefix...

Assuming it's the variable prefix that is not recognized in WOQL?

**Comment by Neelterminusdb** [comment]
You should try to use "docid" as woql variable Var i.e you can define docid as follows to be compatible with WOQL.doc:

```js
let [name, team, title, docid] = WOQL.vars("Name", "Team", "Title", "docid");
```

Also alternatively you can use lexical key (eg: `"@key"  : { "@type": "Lexical", "@fields": ["name"] }`) while defining the schema rather than specifying it when creating a document as shown in your example, this should be quite easy to implement.

**Comment by hoijnet** [comment]
I did use raw WOQL before using the document interface, where it was set as a variable being referenced. Did you manage to set `@id` with docid and get the example to work? For the other variables it worked well, but not for `@id`. Is `@id` treated differently? Might take a day or so before I explore further :-)

**Comment by Neelterminusdb** [comment]
I have not tried running the example with docid will do that and let you know. Also about `@id` being treated differently i have no clue about that maybe @GavinMendelGleason or @spl will know it

**Comment by spl** [comment]
I'm a WOQL novice. But if you give me the raw WOQL, I can look into it.

**Comment by Neelterminusdb** [comment]
I tried it and it inserted the csv data sucessfully, Also `@id` been treated different is because WOQL.doc is is treating it as a string value for that particular field so it is not treating it as a variable and when you submit it to database it gives and error for prefix invalid for the `@id` as the value is invalid for the id. to solve that you will need to define it as Vars using WOQL.vars and pass it in WOQL.doc

The query which i used to test it:

```js
let [name, team, title, docid] = WOQL.vars("Name", "Team", "Title", "docid");

const result = await client.query(
  WOQL.and(
    WOQL.get(WOQL.as("Name", name).as("Team", team).as("Title", title)).post(
      "emp.csv"
    ),
    WOQL.unique("", [name, title], "v:_docid"),
    WOQL.idgen("Employee/", ["v:_docid"], docid),
    WOQL.insert_document(
      new WOQL.doc({
        "@type": "Employee",
        "@id": docid,
        name: name,
        team: team,
        title: title,
      })
    )
  )
);
```

**Comment by hoijnet** [comment]
@spl , I putin the raw WOQL with the variable on [Discord link](https://discord.com/channels/689805612053168129/689886282830315563/959750639653650473) for reference, pasted below.

Perhaps it's as simple as not having the ability to use the `v:` shorthand in the `@id` field with the JS client? Having a test for he doc interface to help others figure out the formst could be helpful though. The automated tests often help me figure things out, kudos for them!!

Below is how I expressed raw documents in WOQL inserts, the `WOQL.doc` is so much easier to use. When back at my computer in the coming days I could try both and see how it goes. (The tuscli client now has a `--woqlCompile` flag to make simple conversions of JS to JSON WOQL if it helps)

Seems from the original issue there was a different problem, likely now resolved. Time to go back and see if it all works it seems, and reestablish my own baseline!

```
WOQL.and(
  WOQL.and(
    WOQL.get(
      WOQL.as('Name', 'v:_Name')
        .as('Manager', 'v:_Manager')
        .as('Title', 'v:_Title')
    ).post("/path_to_csv/Employees.csv"),
    WOQL.typecast("v:_Manager", "xsd:string", "v:Manager"),
    WOQL.typecast("v:_Name", "xsd:string", "v:Name"),
    WOQL.typecast("v:_Title", "xsd:string", "v:Title"),
    WOQL.unique("", ["v:Name", "v:Title"], "v:_docid"),
    WOQL.idgen("Employee/", ["v:_docid"], "v:docid"),
  ),
  WOQL.insert_document({
    '@type': 'Value',
    dictionary: {
      '@type': 'DictionaryTemplate',
      data: [
        {
          '@type': 'FieldValuePair',
          field: '@type',
          value: { '@type': 'Value', data: "Employee" },
        },
        {
          '@type': 'FieldValuePair',
          field: '@id',
          value: { '@type': 'Value', variable: "docid" },
        },
        // {
        //   '@type': 'FieldValuePair',
        //   field: 'Name',
        //   value: { '@type': 'Value', 'variable': 'Name' },
        // },
      ],
    }
  })
)
```

**Comment by hoijnet** [comment]
> to solve that you will need to define it as Vars using WOQL.vars and pass it in WOQL.doc

Now I understand why I likely made it to work with the raw woql originally, I was confused just now as it seemed the code looked to handle docid correctly, but now the other part that later got a bugfix.

I have great use of the `v:` notion generally in the JS client as I don't use raw eval in JS (see tuscli code for the example) for security reasons, and don't let user create variables either. Consistency with the `v:` notion would be helpful. Unsure if that notion is considered legacy or an alternative way. Would be great to have the `v:` notion supported in the doc WOQL if possible?

I'll manage with raw WOQL it seems for this 👍 and will not use the WOQL.doc for the use case due to above; and keep it in mind!

Thanks for checking, then we know the discrepancy ⭐️

**Comment by Neelterminusdb** [comment]
Yes it would be great if we can use `v:` syntax for variable in WOQL.doc as well i will make an issue for the same in js client

**Comment by hoijnet** [comment]
Awesome, thanks @Neelterminusdb , that will make a supernice interface!!

**Comment by Neelterminusdb** [comment]
Closing this issue as it is no longer a terminusdb server issue
