### ISSUE TITLE
Add document interface to CLI

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#1108]
It'd be great if we could use the terminusdb tool to query, insert, replace and delete schema and instance documents. This would be especially convenient for database initialization and update scripts.

**Comment by spl** [comment]
`doc insert` and `doc get` were introduced by #1120. `doc delete` is in #1096.

**Comment by GavinMendelGleason** [comment]
This should be complete now that we have accepted https://github.com/terminusdb/terminusdb/pull/1146
