### ISSUE TITLE
Clone failure leads to inconsistent database

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#1127]
A database created as a result of a clone is in an inconsistent state if there is a failure - this should have a cleanup attached which removes the database - this should probably use `setup_call_catcher_cleanup/4` directly *after* database construction, or filtering out the database exists exception, so as not to destroy already existing databases. The removal has to be *force* deleted as it is a partial DB construction finalised by clone.

**Comment by spl** [comment]
1. Don't delete local database if it exists before clone
2. @spl has a fix for failure to fetch

**Comment by spl** [comment]
> 1. Don't delete local database if it exists before clone

`clone` fails if the local database already exists.
