### ISSUE TITLE
Unfold child documents that are not subdocuments

### ISSUE THREAD

**Issue by KittyJose** [terminusdb/terminusdb#1201]
**Is your feature request related to a problem? Please describe.**

The current structure which I get for a geometry collection is -
```
{
  "@id": "GeometryCollection/9af84a21c83cc2654310e7c6c284d18cba2284ee971a617ffcca798f21a7ac0d",
  "@type": "GeometryCollection",
  "geometries": [
    "LineString/1ca12bb0ea6d46c74e578c8bc4137219794fedc9c71482633af96a895f060e6f",
    "Point/9c03b0565ad8e048bf6947583f7a7f60911e4f7b9842456dd0b760132ca97e5a"
  ],
  "type": "GeometryCollection"
}
```
There is no way in terminusdb-documents-ui to get the coordinates of line string and points to display it in a react-leaflet map ...

**Describe the solution you'd like**
I would like to get back the entire object for all of the geometry types so I can get the coordinates and display accordingly ... 

**Describe alternatives you've considered**
I dont have much of an alternative coz documents-ui dosent have woqlClient in it to make a call to those IDs to get info back.

**Comment by GavinMendelGleason** [comment]
Fixed by #1238
