### ISSUE TITLE
Documentation of new features in prep for 10.1 release

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#1203]
# Documentation

* Type Inference (Gavin)
* Apply (Gavin)
* JSON Documents (Gavin)
* Check path pattern documentation (Sean)

**Comment by hoijnet** [comment]
Keen to understand more on all these, and supercurious especially on how type inference will work once there! So cool ⚡️

**Comment by spl** [comment]
This is the only outstanding issue: https://github.com/terminusdb/terminusdb-client-js/issues/197

**Comment by GavinMendelGleason** [comment]
Path documentation completed.

**Comment by hoijnet** [comment]
@spl and @GavinMendelGleaso, I noticed another regression on the path docs for JS at https://terminusdb.com/docs/index/terminusx-db/reference-guides/javascript-client-reference/woql#path; seems hard to keep them working 😂

**Comment by hoijnet** [comment]
Is there a link to the type inference docs?

**Comment by GavinMendelGleason** [comment]
> @spl and @GavinMendelGleaso, I noticed another regression on the path docs for JS at https://terminusdb.com/docs/index/terminusx-db/reference-guides/javascript-client-reference/woql#path; seems hard to keep them working joy

There was an ambiguity of interpretation for the "from" and "to" parameters in the JS client. I think everything bar the `predicate{n,m}` syntax is working, but this should also work after the next TerminusDB release.

**Comment by GavinMendelGleason** [comment]
> Is there a link to the type inference docs?

https://terminusdb.com/docs/index/terminusx-db/reference-guides/schema#inference

**Comment by GavinMendelGleason** [comment]
Cheers, I'll try to get that fixed.
