### ISSUE TITLE
Endpoint for log / changelog requests (long polls)

### ISSUE THREAD

**Issue by ajf-ajf** [terminusdb/terminusdb#1233]
**Is your feature request related to a problem? Please describe.**
The issue is not a problem, but is a fairly simple alternative to using PubSub that would make it easy to reflect data changes in realtime via JS in a browser client (for instance). PubSub is on the TerminusDB roadmap. In the meantime, this would allow clients to listen for changes via standard HTTP requests. 

**Describe the solution you'd like**
Create a `log` endpoint that would serve histories for a request to the client. See CouchDB's 'long poll' changes `feed` option, for an example of this in a JSON document store:
https://docs.couchdb.org/en/3.2.2/api/database/changes.html

**Describe alternatives you've considered**
A server-side app could process the output of the `log` command and make the data available for a client. Discussion on Discord with Gavin suggests the two clients might offer histories.

**Additional context**
If this is easy to implement then it'd be nice to have. I've found CouchDB's solution simple and reliable for many use cases (e.g., reflecting new and updated records in a list view of documents).

**Comment by GavinMendelGleason** [comment]
You can now get a log with: 

```
curl -X GET http://localhost:6363/api/log/admin/db -uadmin:root
```
Due to #1313 

It would be nice if it were truncated by a size parameter however.
