### ISSUE TITLE
Make JWT subject claim name configurable, sensible or with good fallback

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1237]
**Is your feature request related to a problem? Please describe.**
Configuring JWT authentication in TerminusDB is harder than it should be. The default claim name (`http://terminusdb.com/schema/system#agent_name`) is non-standard and can be very hard to configure at an IdP without having specific skill and an awful lot of permissions; which could be hard to gain in an enterprise context.

Making the default claim name to use from the JWT token would make this much easier. The straight proposal would be to have a fallback to `preferred_username` and if that does not exist, to the `sub` default unique subject name if the others don't exist.

The fix would likely be straightforward, and solve the most important aspect of integration in this older issue:
* [Inconsistent behaviour for JWT JWKS keys/certificates endpoints](https://github.com/terminusdb/terminusdb/issues/728)

The specific code location referenced:
[routed.pl#L2893](https://github.com/terminusdb/terminusdb/blob/dd52f85caa39fc7a89310b5e63ec1902720bf0ad/src/server/routes.pl#L2893)

**Describe the solution you'd like**
I would like to accept a token that includes `preferred_username` with the user to use in TerminusDB, and failing that, fall back to `sub`. Even better would be to make it configurable as that would enable me to use any of the claims in the token, and make the behaviour very clear. 

**Describe alternatives you've considered**
One alternative would be to add the claim to the IdP, which is often not even possible to do without being superadmin. The workaround to use header-based authentication is not strong enough in my opinion, using a JWT is a better and stronger alternative.

**Additional context**

**Comment by rrooij** [comment]
Solved in: 68a9788d15e7b3394be17121d3faf61f3aa86834 I hope this works for you! :smile:

**Comment by hoijnet** [comment]
Great, this will simplify things a lot! For those seeing this, could be interesting to look at issue #728 as well for context. Thanks for providing the option, this will be super-helpful for integrating TerminusDB!
