### ISSUE TITLE
Ability to change password after initialized store: add CLI command

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb#1263]
If you initialize the store with a password, it is relatively complicated to change it later. If you have SWI Prolog installed, it is doable by calculating the hash and replacing the User/admin document with the new hash, but this is fairly complex for people that don't know their way around SWI Prolog.

It would be nice to have it included in the CLI as a flag. Perhaps a subcommand in the `store` command called `reset_pass`, which would like:

`terminusdb store reset_pass YOUR_PASSWORD_HERE`

Or perhaps a dedicated user command would be better:

`terminusdb user reset_pass USER_ID PASSWORD` which could be for example:

`terminusdb user reset_pass admin root`

I propose the latter.

**Comment by matko** [comment]
This is currently being worked on by @GavinMendelGleason .

**Comment by GavinMendelGleason** [comment]
Fixed in #1265
