### ISSUE TITLE
query --json also prints to stderr when the command succeeds

### ISSUE THREAD

**Issue by Tails** [terminusdb/terminusdb#1269]
See: https://discord.com/channels/689805612053168129/689886415491825703/992546940732583976

I expect the ```terminusdb query --json```command to print to stdout when it succeeds, but it prints to stderr irregardless of the command status.

**Comment by GavinMendelGleason** [comment]
Apologies for this! Very silly oversight.

We have a PR #1270

**Comment by rrooij** [comment]
Solved with: https://github.com/terminusdb/terminusdb/pull/1270 Thanks for reporting this!
