### ISSUE TITLE
[CLI] unclear argument for 'terminusdb optimize'

### ISSUE THREAD

**Issue by Tails** [terminusdb/terminusdb#1281]
When trying out the ```terminusdb optimize --help``` command, it was initially unclear what kind of OPTIONS the command was expecting. I initially ran it as ```terminusdb optimize``` but it returned so fast that this could not have been the intended use. After reading the sparse description "Optimize a database" I figured out the OPTIONS argument wanted a database identifier such as USER/DB_NAME. 

It would be good to document the OPTIONS argument, like how it's done with the --help flag.

<img width="642" alt="image" src="https://user-images.githubusercontent.com/354312/178245714-cff8776f-8a67-48c9-aefe-8690b856e627.png">

**Comment by GavinMendelGleason** [comment]
Yikes! Will fix this!

**Comment by GavinMendelGleason** [comment]
Fixed in #1282
