### ISSUE TITLE
`--impersonate` flag that allows CLI to run as a given user

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#1285]
Currently we have no way of running the CLI as a given user. Since access to the store is required to run the CLI it makes no sense to do a full authentication, and yet it would still be useful to run under a lower privilege regime in many circumstances.

Add an `--impersonate USERNAME` flag to CLI commands to allow authentication to use `USERNAME`s authority.

**Comment by rrooij** [comment]
Fixed in 632d012b6103b643e8f5f173d5a58e4c9d9f2687
