### ISSUE TITLE
Access Control - create capability - Error message not clear 

### ISSUE THREAD

**Issue by Francesca-Bit** [terminusdb/terminusdb#1316]
**Describe the bug**
try to create a new capability with roles as string (the correct value for roles is array ["Role/collaborator"])
http://localhost:6363/api/capabilities

payload example
{"operation": "grant", "user": "User/francesca", **"roles": "Role/collaborator",** "scope": "Organization/fra_org"}

I got this error and It's not easy to determine the cause of failure
{
  "api:message":"Unexpected failure in request handler",
  "api:status":"api:failure"
}

**Comment by GavinMendelGleason** [comment]
Fixed in #1329
