### ISSUE TITLE
Schema checker bug with top-level class delete

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1317]
**Describe the bug**
I have removed all documents and other types, only schema element left is a top level "Entity" I can't delete due to a schema check failure. Looks like an odd corner case which helps uncover issues in the schema checker.

As it's otherwise empty, happy to share the data product for investigation if it helps

**To Reproduce**
1. Delete remaining document type
2. Get schema check error

**Expected behavior**
Deletion of document as no records or schema is there. Should have no dependencies.

**Screenshots**
![262D6363-E2B2-4286-8C1F-1EC16FEEE3AA](https://user-images.githubusercontent.com/144317/179727949-7aae826a-e212-4389-aab4-b67eea3fb6aa.png)

**Info (please complete the following information):**
 - TerminusX

**Additional context**

**Comment by GavinMendelGleason** [comment]
This may be an additional referential integrity bug. I'm unable to achieve the same behaviour with a new schema so it may also be fixed. Can we get an example schema?
