### ISSUE TITLE
Time out when cloning large databases

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#133]
**Describe the bug**
When I try to clone a large database, the action times out and does not complete. This does not happen when I have a better internet connection. I understand it is to do with the size and the Cloudflare DNS (the 'Client Max Upload Size' limits to be precise) . As it is not economically possible to solve the problem, would be good to have a chunking approach so that I can still get the clone even with a weaker connection. As DBs get even larger and users more scattered, this will become more of an issue.

**To Reproduce**
1. Go to an area with bad internet
2. Click on click on clone
3. Wait while it tries to clone

**Expected behavior**
I expected the clone to happen,  even if it was a bit slower due to the connection - which I already know isn't great.

**Screenshots**
N/A

**Info (please complete the following information):**
 - OS: windows

**Additional context**
Known problem - keep delivering the dream, Terminators

**Comment by kevinchekovfeeney** [comment]
This is an issue with the hub infrastrcture (cloudflare time outs for POSTs) not the server itself - I think the solution is to upgrade the hub infra account with cloudflare, not chunking as such.

**Comment by luke-feeney** [comment]
that is the easiest solution, but the price is high, so it will likely be a while before we could implement - is chunking not going to be useful for larger database in any case?

**Comment by kevinchekovfeeney** [comment]
Chunking is going to be needed / useful for pushing / uploads - not so much for downloads / clone - actually we could make get and pull use GET to get around the download limitations in the short term...

**Comment by GavinMendelGleason** [comment]
Looks like we're going to have to implement TUS as chunking did not work with cloudflare.
