### ISSUE TITLE
Allow serving HTTP(S) under a URL prefix other than /

### ISSUE THREAD

**Issue by bollwyvl** [terminusdb/terminusdb#134]
## Desired Feature

`TERMINUSDB_URL_PREFIX` (and CLI switches, I guess) existed, could be set to something other than `/`, and the console worked when hosted on a different URL base (e.g. inside another application).

## Motivation

Over on https://github.com/terminusdb/terminusdb-tutorials/pull/31 I've got a brutal, but working, build which starts up an interactive jupyter server with the ability to start the terminusdb server. It mostly works for kernel usage.

However, on Binder,  only _one_ port is exposed per session, but we can use a proxy to get other ports exposed, the final URL ends up looking like:

```
https://hub.gke2.mybinder.org/user/bollwyvl-terminusdb-tutorials-8j8xs8nm/proxy/6363
```

This results in:

---

![Screenshot from 2020-10-17 17-49-32](https://user-images.githubusercontent.com/45380/96354184-c375fa00-10a1-11eb-886f-4207a247fac5.png)

---

The console _doesn't_ show any warnings... but _is_ grabbing things from all over the internet... a separate issue, to be sure...

## Alternatives

There aren't a lot: I've been through this with a bunch of different tools, and it's just generally hard to compose things if every app expects to be installed on `/`. Trying to rewrite URLs on the fly in the proxy is basically insane, the brave new SPA era.

## Thanks!

Thanks for terminusdb! Looking forward to exploring it more!

**Comment by Cheukting** [comment]
Any comment on this @kevinchekovfeeney ?

**Comment by Cheukting** [comment]
see https://github.com/terminusdb/terminusdb-tutorials/pull/31

**Comment by rrooij** [comment]
Are you able to use a reverse proxy for this and put a rewrite rule there? That would be the proper way to "subfolder" this.
