### ISSUE TITLE
WOQL.type_of in Javascript yields TypeError: this.cleanClass is not a function

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1341]
**Describe the bug**
I get a `TypeError: this.cleanClass is not a function` when using `WOQL.type_of` in JavaScript, and a stacktrace from the Javascript client (woqlQuery.js line 1018, from woql.js:1103).

At first glance, looks like a bug.

I am trying to use check if a variable is not an `xsd:string`, approximately below, as part of a `WOQL.and` clause:

```
WOQL.not().type_of("v:my_variable", "xsd:string")
```

I believe it is probably a bug in the Javascript client. Managed to do a workaround by checking for `rdf:null` instead of that the type is `xsd:string` which was to reverse the logic (which fixed my problem). 

**To Reproduce**
1. Create a WOQL that imports a CSV, and splits a column into a list using `WOQL.split`
2. Check whether the column is a string or a list, or `rdf:null` using `WOQL.type_of` (can't share code unfortunately)
3. Submit WOQL
4. Javascript yields an error: `TypeError: this.cleanClass is not a function`
5. See error

**Expected behavior**
It should be possible to use `WOQL.type_of` in javascript

**Screenshots**
N/A, don't have the error here and managed to workaround the problem.

**Info (please complete the following information):**
 - latest docker

**Comment by GavinMendelGleason** [comment]
Yeah, I suspect this is a client bug, I'll have a look.
