### ISSUE TITLE
Can't add Set or List using WOQL update_document

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1342]
**Describe the bug**
Deteced an issue while performing imports today, continuing on the errors with null_unsupported when adding a split list as a variable. What I believed was null (and detected the this.cleanClass error) was a `red herring`. The error lay below that.

I'm trying to perform a CSV import where a cell has commated value that I'd like to split and import as a set. Thus the following sequence (abbreviated to only the key manipulations):

```
// From CSV (Field contains A,B,C
WOQL.as("Field", "v:_field")
// Typecast _field
WOQL.typecast("v:_field", "xsd:string", "v:__field")
// Split the field to a list
WOQL.split("v:__field", ",", "v:field")

// Idea is that "v:field" should now contain the equivalence of ["A","B","C"]
// And if field is a Set of xsd:string, I assume below should work
WOQL.update_document(new WOQL.doc({
  "@type": "Mytype",
  "@id:": "v:docid",
  field: "v:field",
})

Instead, I get Error: API Error api:messdag Error: null_unsupported
```

This happens both with List and Set. Are WOQL inserts for Set and List unsupported, or is it the JS library that for some reason does not manage to add them correctly? I tried omitting the WOQL.doc and writing the WOQL manually for insertion with a FieldValuePair and `field` as a Value variable with the same result.

**To Reproduce**
1. Split an xsd:string into a list variable 
2. Create a document with the list variable as a parameter to a Set or List
3. Receive error `null_unsupported`

**Expected behavior**
It should be straightforward to add a split list as a List or Set to a document and update or insert it.

**Info (please complete the following information):**
 - Latest docker, Javascript client

**Comment by rrooij** [comment]
Oneliner for reproducing the issue quickly (can be done in dashboard as well):

`WOQL.split(WOQL.string('A,B,C'), ',', 'v:Split').insert_document(WOQL.doc({ "@type" : "test", "testlist": 'v:Split' }))`
