### ISSUE TITLE
Can't add prefix

### ISSUE THREAD

**Issue by bascott** [terminusdb/terminusdb#136]
**Describe the bug**
Trying to add prefix foaf for http://xmlns.com/foaf/0.1/ to a database fails in the console, both through the UI and through a WOQL query (see screenshot below for error).

**To Reproduce**
1. Open the console.
2. Select a database.
3. Navigate to Schema tab.
4. Click New Prefix.
5. Enter `foaf` in the first box and `http://xmlns.com/foaf/0.1/` in the second.
6. Click Create.

**Expected behavior**
The prefix `foaf` for IRI `http://xmlns.com/foaf/0.1/` is listed in available prefixes.

**Screenshots**
![image](https://user-images.githubusercontent.com/2665771/98448719-2df7e400-20fc-11eb-839a-15b1104bd0bb.png)

**Info**
 - OS: Windows 10
 - terminus-server run using terminusdb/terminusdb-bootstrap@6d5617e98bc99931d461dd0fdfd8af274e71ae30

**Comment by rrooij** [comment]
It works for me on the dev branch, but I can reproduce this on the latest master. Thanks a lot for reporting this!

**Comment by bascott** [comment]
Error no longer occurs as of terminusdb/terminusdb-bootstrap@35110511cff228e5751a8c5bd48794afaa2bdc5f and I am able to add documents using the prefixed term.
