### ISSUE TITLE
Databases can't be renamed

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1366]
**Is your feature request related to a problem? Please describe.**
I want to rename a database name, if I realize I named it incorrectly.

**Describe the solution you'd like**
There should be a woqlClient option in the Javascript client to rename a database

**Describe alternatives you've considered**
The alternative is to clone the database and delete the old one. Whilst possible, it introduces a number of unknowns and has a risk of failing mid-way leaving things in a bad state.

**Comment by GavinMendelGleason** [comment]
This should be covered by: https://terminusdb.com/docs/index/terminusx-db/reference-guides/openapi#db-organization-database-4
