### ISSUE TITLE
Database label and comments can't be updated in TerminusX

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1367]
**Describe the bug**
Database labels and comments can be updated in local open source instances by overwriting the UserDatabase entry in the `_system` database, or by manipulating the entries via WOQL. This is not possible in TerminusX and thus there is no exposed way to update the label and comment of a user database.

Labels and comments should be possible to update for a data product as clarity will evolve over time about it.

Also, if it should not be possible, the error message is incorrect as it should be a `403 Forbidden` instead.

**To Reproduce**
1. set client.systemDb
2. perform updateDocument on the UserDatabase entry
3. Error 500

```
{
  "name": "Error",
  "message": "API Error api:message Error: read_access_malformed_collection(system_descriptor{}) api:status api:server_error Code: 500 url: https://terminusx/INSTANCE/api/woql/_system"
}
```

**Expected behavior**
Clearcut way to update label and comment in TerminusX (or a 403 indicating this should not be possible)

**Info (please complete the following information):**
 - OS: macOS/Docker
 - TerminusX

**Comment by GavinMendelGleason** [comment]
This should be covered by: https://terminusdb.com/docs/index/terminusx-db/reference-guides/openapi#db-organization-database-4
