### ISSUE TITLE
Wrong prefix for property names

### ISSUE THREAD

**Issue by k-tipp** [terminusdb/terminusdb#137]
**Describe the bug**
Instead of the "scm" prefix, "xsd" is selected, if the property id is equal to a datatype.

**To Reproduce**
```
client.create_database(dbid="testdb", accountid="admin", label="test database", description="", include_schema=True)

client.db("testdb")

WOQLQuery().doctype("RosterRecord", label="Roster Record", description="Roster Record", graph="schema")
    .property("name", "string")
    .property("date", "date", label="Registration Date")
    .property("paid", "string", label="Paid")
    .property("boolean", "boolean")
    .property("string", "string").execute(client)
```
**Expected behavior**
scm:string, scm:boolean, scm:date instead of xsd:xxx

**Screenshots**
![grafik](https://user-images.githubusercontent.com/3494491/98803406-fdbe8700-2414-11eb-8a6a-db4d87f3bba2.png)

**Info (please complete the following information):**
Using latest terminusdb-bootstrap and python client

**Comment by kevinchekovfeeney** [comment]
That's a definite bug - should always go to scm when there is no prefix supplied for the property id - as a workaround, you can explicitly specify "scm:string" / or whatever. It's also something we should pick up in schema validation - a datatype and a property with the same ID doesn't seem to me like something that you ever actually should have.

**Comment by k-tipp** [comment]
Thx for your feedback, I agree, registration_date would have been a better name, but if you just play around and dont think too much about your naming, things happen ;-)

**Comment by luke-feeney** [comment]
Thanks for this @k-tipp - we are going to discuss at the next issues and docs triage session in the Discord server

What: Issues and Docs Triage
Where: Discord Server (https://discord.gg/CzE5yZdjpr)
When: Every Thursday from this week until the end of time @ 2pm GMT; 3pm CET; 9am ET; 6am PT; 7.30pm IST

Will update here after

**Comment by kevinchekovfeeney** [comment]
Fixed in latest release
