### ISSUE TITLE
Provide a way to Reload/Refresh the current page of the desktop app

### ISSUE THREAD

**Issue by EmmanuelOga** [terminusdb/terminusdb#138]
While using the JS API, after performing certain CRUD operation, sometimes I want to verify the result of the operation on the desktop app.

The desktop app doesn't provide a way to soft-refresh, so currently I either click a diff tab and come back, reload through the tray icon menu or CTRL-R. These last two ways takes 1 or 2 seconds to reload or sometimes more.

Would be nice to have a reload button on the UI able to reload just the current page: for instance, on the list of documents, just refresh the list of documents.

I wonder if the UI could receive notifications of the server when something updates and refresh on its own... although this sounds like a more complicated ask 😄 .

**Comment by EmmanuelOga** [comment]
cc: @dmytri @Francesca-Bit

**Comment by luke-feeney** [comment]
Thanks for this @EmmanuelOga - we are going to discuss at the next issues and docs triage session in the Discord server

What: Issues and Docs Triage
Where: Discord Server (https://discord.gg/CzE5yZdjpr)
When: Every Thursday from this week until the end of time @ 2pm GMT; 3pm CET; 9am ET; 6am PT; 7.30pm IST

Will report back after

**Comment by luke-feeney** [comment]
Looking at adding a reload button to the document page so you can reload without having to refresh everything. Ctl-R works, but agree that it isn't the best when in the document viewer. Thanks.

**Comment by Francesca-Bit** [comment]
we added a refresh button under the tables
