### ISSUE TITLE
Display URL of the server and location of configuration files on Desktop App

### ISSUE THREAD

**Issue by EmmanuelOga** [terminusdb/terminusdb#139]
As a first time user of the desktop app, which I downloaded from https://terminusdb.com/hub/download, I couldn't tell which port the server was running at and how to change it if I wanted to.

Eventually I realized most tutorials were talking to localhost:6363, so I picked that and it worked!

Would be nice to display on the desktop app this information. Also, showing the location of the configuration file would be helpful.

cc: @dmytri @Francesca-Bit

**Comment by luke-feeney** [comment]
Thanks for this @EmmanuelOga - we are going to discuss this issue at the next issues and docs triage session in the Discord server. Plan is to discuss each issue that comes up weekly (once we have got 4.0 out the door)

What: Issues and Docs Triage
Where: Discord Server (https://discord.gg/CzE5yZdjpr)
When: Every Thursday from this week until the end of time @ 2pm GMT; 3pm CET; 9am ET; 6am PT; 7.30pm IST

Open to all to come and talk about issues.

**Comment by kevinchekovfeeney** [comment]
This is in console from 4.0.1 - accessible via a (i) button in the top navigation bar
