### ISSUE TITLE
openapi: log not documented

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb#1395]
The `/api/log` endpoint is not documented but very useful. We should add it.

It is not yet available in `main`: https://editor.swagger.io/?url=https://raw.githubusercontent.com/terminusdb/terminusdb/main/docs/openapi.yaml

**Comment by matko** [comment]
it is now documented.

**Comment by rrooij** [comment]
Solved in: https://github.com/terminusdb/terminusdb/pull/1396 Just for future reference
