### ISSUE TITLE
Possible bug in setof/3 call

### ISSUE THREAD

**Issue by pmoura** [terminusdb/terminusdb#14]
In the following predicate definition:

https://github.com/terminusdb/terminus-server/blob/152b2f58c869523f2ad5ffeecbb702045d3a84d2/library/validate_schema.pl#L476-L482

the Logtalk linter reports:

```logtalk
*     Suspicious call: xrdf(A,B,C,D,E) in setof/3 goal contains singleton variable D
*       while compiling object validate_schema
*       in file /Users/pmoura/terminus-server/library/validate_schema.pl between lines 476-482
```

The reported singleton variable can result in multiple solutions (one per binding of the variable) where a single solution is expected.

**Comment by GavinMendelGleason** [comment]
I think this is actually correct - the point is to check if there are multiple answers.

**Comment by pmoura** [comment]
Yes, I noticed the soft-cut control construct. But, theoretically, that call can generating multiple solutions for the bindings of the `Collection`, `Schema`, `X`, and `CE` variables. But the use of an anonymous variable in the fourth argument suggests that you don't want multiple solutions for the bindings of that particular argument.

**Comment by GavinMendelGleason** [comment]
Indeed, but we want to be able to check length(L,1) - so we're intending to find if there are duplicates.

**Comment by pmoura** [comment]
Still confused by this predicate definition. Given the comment "Exactly one reference to this class" shouldn't the predicate call `bagof/3` instead of `setof/3`? But assuming `setof/3` is correct, why not simplifying it to:

```prolog
anonymousEquivalentClass(C,CE,Database) :-
    database_schema(Database,Schema),
    equivalentClass(C,CE,Database),
    % Exactly one reference to this class, or everything will go to hell.
    setof(X,xrdf(Database,Schema,X,_,CE),[_]).
```

**Comment by GavinMendelGleason** [comment]
Yikes, indeed, this can't be setof/3, but must be bagof/3.

**Comment by GavinMendelGleason** [comment]
closed due to age
