### ISSUE TITLE
Apparent encoding issue attempting to insert a fishy Unicode character (🐠)

### ISSUE THREAD

**Issue by EmmanuelOga** [terminusdb/terminusdb#140]
Hello,

I'm [executing this query](https://gist.github.com/EmmanuelOga/d83f14f1cc57513def3d189dd1a453b9#file-tdb-query-json-L146) which contains this character: 🐠.

If I remove the character, the query executes just fine.

Note that this is using node v14.10.0 with terminusdb client 4.0.0. The JavaScript source file is properly encoded in utf-8 as far as I can tell.

TDB version is 3.0.1 on windows 10 64.

The server response is:

```
Couldn't create doc:public/: Error: API Error <!DOCTYPE html>
<html>
<head>
<title>500 Internal server error</title>

<meta http-equiv="content-type" content="text/html; charset=UTF-8">

</head>
<body>

<h1>Internal server error</h1>

<p>
string_codes/2: Cannot represent due to `character_code'</p>

<address>
<a href="http://www.swi-prolog.org">SWI-Prolog</a> httpd at DESKTOP-SVB6D03
</address>

</body>
</html>
Code: 500 url: https://127.0.0.1:6363/api/woql/admin/emmanuelogacom/local/branch/main
Done in 1.52s.
```

**Comment by GavinMendelGleason** [comment]
This is actually a known bug in SWIPL's handling of multibyte codes on windows. It works correctly on linux.

We have a strategy for fixing this but it's relatively complicated as it involves fixing the SWIPL handling of strings on windows.

**Comment by EmmanuelOga** [comment]
Got it! It seems like I should finally give https://github.com/terminusdb/terminusdb-bootstrap a try!

**Comment by luke-feeney** [comment]
Closing as seems to be clear! Will reopen with any updates on SWIPL fix.
