### ISSUE TITLE
CLI triple load: wrong database name shows help message, should show helpful error

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#1408]
When trying to load a triple file into a database that doesn't exist, the CLI will show a help message. This is a result of the underlying predicate failing, without us properly handling that failure.

There's two things to do here. First, failure should not fall through to the help message. This is actually a general problem which keeps biting us, so maybe we should just fix it once and for all.

Second, error conditions in the triple load should lead to actual errors being thrown, not failures. So we need to track down where the failure is, and wrap it in a `do_or_die`.

**Comment by GavinMendelGleason** [comment]
Fixed by #1410
