### ISSUE TITLE
What happened when datasets more than RAM?

### ISSUE THREAD

**Issue by kokizzu** [terminusdb/terminusdb#141]
In RediGraph it's cannot add more record (unless using enterprise version of redis that could store in SSD), TigerGraph and DGraph and Neo4j is fine, because it's not in-memory database, how about terminusDB?

**Comment by GavinMendelGleason** [comment]
You can't have more records than available memory in TerminusDB. However we do store information in a succinct data structure which improves the total amount of information you can fit in memory substantially.
