### ISSUE TITLE
Unnecessary space in branches when fetching db info

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb#1419]
When fetching a database with `verbose=true`, I get the following JSON back:

```
{
  "@id":"UserDatabase/c308f1b37ecea5893a9fb44ee04f773547a7403b4cbcbcafc83623ede587836e",
  "@type":"UserDatabase",
  "branches": ["main" ],
  "comment":"test1",
  "creation_date":"2022-08-31T13:44:34.510Z",
  "label":"test1",
  "name":"test1",
  "path":"admin/test1",
  "state":"finalized"
}
```

Notice that the branches list (`"branches": ["main" ]`) has a space that shouldn't be there.

Creating a new branch also adds an unnecessary space at the end:

```
"branches": ["main", "test" ],
```

To reproduce:

1. `./terminusdb db create admin/test1`
2. `curl -u admin:root -X GET localhost:6363/api/db/admin/test1?verbose=true`

**Comment by rrooij** [comment]
This actually happens to all the lists in JSON. Seems to be a SWI-Prolog bug as I can reproduce it by executing the following content in a test Prolog file:

```prolog
:- use_module(library(http/json)).
:- json_write(current_output, point{x:1,y:["test", "test2"]}), nl, halt.
```

**Comment by GavinMendelGleason** [comment]
Not going to fix this one! We can make default be single line JSON though.
