### ISSUE TITLE
Add commit message to Schema Builder

### ISSUE THREAD

**Issue by panasenco** [terminusdb/terminusdb#143]
**Is your feature request related to a problem? Please describe.**
I love Schema Builder, but really dislike that I can't set the commit message when saving my schema. 

**Describe the solution you'd like**
Add a commit message text field when saving a schema with Schema Builder - exactly the same as the Query tab has ("Enter reason for update here").

**Describe alternatives you've considered**
Using WOQL.js directly is a possibility, but Schema Builder is so much easier to work with...

**Comment by luke-feeney** [comment]
Thanks for this @panasenco - really helpful feedback and great that you like the new model builder. We'll review over the break and discuss in our first issue triage of 2021. That will be Thursday 7 Jan I think. I'll report back!

**Comment by luke-feeney** [comment]
@Francesca-Bit is working on a solution - should have something to report in the not too distant future.

**Comment by Francesca-Bit** [comment]
Fixed in dev/canary branch
