### ISSUE TITLE
WOQL.insert_document(), not catched error 

### ISSUE THREAD

**Issue by Francesca-Bit** [terminusdb/terminusdb#1434]
using WOQL.insert_document(), 
if I insert a document that already exists (with the same id),
I get this error

`api:message: "Error: can_not_insert_existing_object_with_id('terminusdb:///data/Organization/org___009')\n  [55] throw(error(can_not_insert_existing_object_with_id('terminusdb:///data/Organization/org___009'),_7746))\n  [53] when:trigger_first(true,'document/json':(...,...)) at /usr/lib/swipl/library/when.pl:100\n  [47] unfreeze('<garbage_collected>') at /usr/lib/swipl/boot/attvar.pl:103\n  [45] call_all_attr_uhooks('<garbage_collected>',true) at /usr/lib/swipl/boot/attvar.pl:63\n  [44] '$wakeup'('<garbage_collected>') at /usr/lib/swipl/boot/attvar.pl:58\n  [43] true=true <foreign>\n  [42] '<meta-call>'('<garbage_collected>') <foreign>\n  [41] findall_loop(_7992,'<garbage_collected>',_7996,[]) at /usr/lib/swipl/boot/bags.pl:99\n  [40] setup_call_catcher_cleanup('$bags':'$new_findall_bag','$bags':findall_loop(_8050,...,_8054,[]),_8032,'$bags':'$destroy_findall_bag') at /usr/lib/swipl/boot/init.pl:663\n  [36] '<meta-call>'('<garbage_collected>') <foreign>\n  [35] call('<garbage_collected>') at ...... `

**Comment by matko** [comment]
@GavinMendelGleason did you fix this?

**Comment by matko** [comment]
Apparently we need to do a similar sort of document threading into the error type that we do in the document interface, and this is currently not done.
