### ISSUE TITLE
Loading CSV files with semicolon separators is not supported

### ISSUE THREAD

**Issue by MichaelSavin** [terminusdb/terminusdb#144]
**Describe the bug**
Loading CSV files with semicolon separators is not supported

**To Reproduce**
1. Create a new database
2. Load this CSV [o3.txt](https://github.com/terminusdb/terminusdb/files/5724244/o3.txt)

**Error**
terminus_store_rust_error('CSV error: record 1 (line: 1, byte: 26): found record with 4 fields, but the previous record has 1 fields')

**Comment by luke-feeney** [comment]
Thanks @MichaelSavin - we are reviewing this and will include in our next issue triage (unless we can fix in advance). That will be Thursday 7 January I think. Will report back.

**Comment by luke-feeney** [comment]
This is in the backlog to solve - we currently just support commas, but there is underlying support for other separators we just have to expose. Will keep the issue open so we can double back when resolved

**Comment by GavinMendelGleason** [comment]
I'm able to load this and dump it successfully with the linux command line interface, so I strongly suspect this is related to the windows version. 

We have known issues with high code pages on windows, but this is low enough that I'm not sure of the cause. I'll look into it further and see if we can provide a patch to the windows version that will fix it.

**Comment by Cheukting** [comment]
@GavinMendelGleason will give you a more relevant explanation

**Comment by GavinMendelGleason** [comment]
We will not be extending CSV to other separators on near term road map.
