### ISSUE TITLE
CSV import - UTF-8 cyrillyc symbols is not supported

### ISSUE THREAD

**Issue by MichaelSavin** [terminusdb/terminusdb#145]
**Describe the bug**
Loading CSV UTF-8 files with cyryllic is not supported

**To Reproduce**
1. Create a new database
2. Load this CSV 
[o01.txt](https://github.com/terminusdb/terminusdb/files/5724339/o01.txt)

**Error**
io_error(write,<stream>(0x55b461b58f00)) context(system:write/2,'Encoding cannot represent character')

**Comment by luke-feeney** [comment]
This is a interesting one! Will have to check it out. Will also include for discussion in our next issue triage. Please come along to discuss. Will be Thursday 7 Jan at 2pm GMT in the TerminusDB Discord server.

**Comment by rrooij** [comment]
On which platform / OS are you running TerminusDB?

**Comment by MichaelSavin** [comment]
Windows 10

**Comment by GavinMendelGleason** [comment]
This is a bug in swipl on windows 10 and its inability to properly process utf8. The work around is to use the docker at the minute. We're currently working out a permanent solution to fix the bug in swipl but it will be a few months yet before we can solve it.
