### ISSUE TITLE
Provide labels for entities linked through object properties in document views

### ISSUE THREAD

**Issue by adhollander** [terminusdb/terminusdb#146]
I love the direction TerminusDB is going, especially in its 4.0 release. I've been looking for years now for an interface allowing non-programmers to be able to create and maintain RDF linked datasets, and TerminusDB is definitely on the right track. But here are a couple of related enhancements that I think are key if people are to work with it successfully as a CMS for RDF datasets.

When one uses the desktop client to edit a document in a database, usually there will be other entities linked to the document via object properties. (E.g. Organization _produces_ Dataset). As far as I can tell, in the UI under the documents tab, if one wants to link another document to a given document via an object property, one has to enter in the full id for the related document (e.g. `doc:Dataset_iqr9w1607571537493`). This is a burdensome step for users to follow.

What the interface should do at this point is to prompt the user with the rdfs:label strings for the entities that are possibilities as the objects of the object property. (e.g. a listing of all the Datasets already in the system). This might be done via a dropdown menu or a typeahead form. The user would select one or multiple entries, and when the data is saved it would store the correct id for the referent. 

Similarly, in the page view for a document, the record should display the rdfs:label for the referent for an object property in addition to or instead of the id string.

Thanks, Allan

**Comment by kevinchekovfeeney** [comment]
Thanks Allan - definitely agree with you - in fact these are coming in version 4.2 - nearly ready!

**Comment by Cheukting** [comment]
Hey it's already out @adhollander I hope you have already check it out? Let us know if you have further suggestions.
