### ISSUE TITLE
Miscellaneous XSD types not rendering in graph view 

### ISSUE THREAD

**Issue by majidaldo** [terminusdb/terminusdb#1503]
**Describe the bug**
Miscellaneous XSD types do not render in the graph view. Furthermore, they don't show up even as an option in the GUI.

**To Reproduce**
input this json:
```
    {
        "@id": "File",
        "@key": {
            "@type": "Random"
        },
        "@type": "Class",
        "name": "xsd:Name", # 'misc' type
        "names": "xsd:string",
        "path": "xsd:anyURI",  # 'misc' type
        "paths": "xsd:string"
    }
```
does not render
![image](https://user-images.githubusercontent.com/3588248/195198916-61b4ac86-6d8d-4b2b-89fc-3072ab751b86.png)

**Expected behavior**
should show up in properties

**Info (please complete the following information):**
latest terminusdb bootstrap.

**Comment by Francesca-Bit** [comment]
This is fixed in terminusX and in the latest Terminusdb  bootstrap.
Just stop and run bootstrap again.
Thanks for your bug report.
