### ISSUE TITLE
implosion on self ref prefix

### ISSUE THREAD

**Issue by majidaldo** [terminusdb/terminusdb#1504]
**Describe the bug**
self ref prefix causes 'implosion'.

**To Reproduce**
minimal example put into gui:
```
[
    {
        "@base": "terminusdb:///data/",
        "@schema": "terminusdb:///schema#",
        "@type": "@context",
        "pfx": "pfx"
    },
    {
        "@id": "pfx:somethign",
        "@type": "Class"
    }
]
```
gives:
```
[
    "["
]
```

**Expected behavior**
not to 'implode'

**Info (please complete the following information):**
latest terminusdb bootstrap

**Additional context**
seems to put the data product into an unrecoverable state. rollback doesn't work.

**Comment by Francesca-Bit** [comment]
I'm fixing the interface (no to implode)
But the main problem is server side. 
The schema was not created correctly, and when the interface tries to retrive the schema back 
http://127.0.0.1:6363/api/document/admin/youdbname/local/branch/main?as_list=true&graph_type=schema
The server response is :
`[
{"@base":"terminusdb:///data/", "@schema":"terminusdb:///schema#", "@type":"@context", "pfx":"pfx"}Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Credentials: true
Access-Control-Max-Age: 1728000
Access-Control-Allow-Headers: Authorization, Authorization-Remote, Accept, Accept-Encoding, Accept-Language, Host, Origin, Referer, Content-Type, Content-Length, Content-Range, Content-Disposition, Content-Description
Access-Control-Allow-Origin: http://localhost:3030
Status: 404
Content-type: application/json

{"@type":"api:GetDocumentErrorResponse", "api:error": {"@type":"api:DocumentNotFound", "api:document_id":"pfxsomethign"}, "api:message":"Document not found: pfxsomethign", "api:status":"api:not_found"}`

**Comment by majidaldo** [comment]
> I'm fixing the interface (no to implode) But the main problem is server side. The schema was not created correctly, and when the interface tries to retrive the schema back http://127.0.0.1:6363/api/document/admin/youdbname/local/branch/main?as_list=true&graph_type=schema The server response is : `[ {"@base":"terminusdb:///data/", "@Schema":"terminusdb:///schema#", "@type":"@context", "pfx":"pfx"}Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS Access-Control-Allow-Credentials: true Access-Control-Max-Age: 1728000 Access-Control-Allow-Headers: Authorization, Authorization-Remote, Accept, Accept-Encoding, Accept-Language, Host, Origin, Referer, Content-Type, Content-Length, Content-Range, Content-Disposition, Content-Description Access-Control-Allow-Origin: http://localhost:3030 Status: 404 Content-type: application/json
> 
> {"@type":"api:GetDocumentErrorResponse", "api:error": {"@type":"api:DocumentNotFound", "api:document_id":"pfxsomethign"}, "api:message":"Document not found: pfxsomethign", "api:status":"api:not_found"}`

actually, anything will do it
```
[
    {
        "@base": "terminusdb:///data/",
        "@schema": "terminusdb:///schema#",
        "@type": "@context",
        "pfx": "sdfsdf"
    },
    {
        "@id": "pfx:SomeThing",
        "@type": "Class"
    }
]

```
