### ISSUE TITLE
Minimise Electron App in Windows

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#151]
This is half bug half enhancement - when you minimise the electron in windows it goes to the tray and not the toolbar/taskbar. Would be much handier if it minimised to the taskbar and closed to the tray. 

**To Reproduce**
1. Go to electron app in windows
2. Click on minimise
3. See pov

**Expected behavior**
Would be better if it went to the bar at the bottom

![image](https://user-images.githubusercontent.com/53231019/105855526-18e66f00-5fe0-11eb-86cb-5202f6ab1b24.png)

**Info (please complete the following information):**
 - OS: Windows 10
 - Windows Electron App

**Additional context**
Love the product!

**Comment by Cheukting** [comment]
Mostly solved! Thanks @roj
