### ISSUE TITLE
Typo in Server documentation

### ISSUE THREAD

**Issue by pbaille** [terminusdb/terminusdb#152]
One segment of the URL is missing in the template for [Delete Database](https://terminusdb.com/docs/reference/server/api/#delete-database) section

The given code is:

`DELETE http://localhost:6363/api/<organization>/<dbid>`

where it should be:

`DELETE http://localhost:6363/api/db/<organization>/<dbid>`

**Comment by GavinMendelGleason** [comment]
Fixed in https://github.com/terminusdb/terminusdb-doc/commit/5950bd576853ea3dc99633f8f656338f0c08dfcc
