### ISSUE TITLE
Bad error report for "Failed to merge" "graph_sets_not_included"

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#154]
A generic error report is given for this specific `graph_sets_not_included` error: 

```javascript
{
  "data": {
    "api:message": "Error: graph_sets_not_included(doc:'ValidCommit_dj9578n4totlczk94086dg0lihx1urh',doc:'ValidCommit_fb4si5lv7j4bkiaspf2kjcsthehysl3')",
    "api:status": "api:server_error",
    "end": "2021-02-02T10:58:42.368Z",
    "start": "2021-02-02T10:58:42.368Z",
    "duration": "2021-02-02T10:58:42.368Z"
  }
}
```

**To Reproduce**
Create a database without a schema, create a branch *with* a schema. Attempt to rebase from one to the other.

**Expected behavior**
We should rather return a specific API JSON-LD object report for this error.

**Comment by spl** [comment]
Not fixing this now. It will be better though!
