### ISSUE TITLE
Post-update schema retrieval intermittent disconnect in TerminusX 

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1582]
**Describe the bug**

When a schema update occurs, there should be no significant side-effects on schema retrieval after that schema update operation is completed.

With a fairly small schema (~50 classes in a hierarchy), normal schema retrieval is sub-500ms from TerminusX in general. If a schema update is preceding the schema retrieval, up to 30 second elapses and then TerminusX closes the connection abruptly, forcing the user to retrieve the schema anew. (this was pronounced between in 1700-1900CET 2022-11-23).

It seems to happen from time to time, but could not reproduce today in TerminusX. I will keep an eye on it and update this once I find some patterns.

**To Reproduce**
Not yet clear. Likely a post-update of the schema such as add?/update?, and then the subsequent retrieval is slow intermittently.

**Expected behavior**
Consistent time for full schema retrieval (as_list), and similar latency once the schema checker has completed the update 

**Screenshots**
N/A

**Info (please complete the following information):**
 - OS: Javascript client, against TerminusX, version 10.1.7 when tested.

**Additional context**
Testing from DFRNT, and getting hard session disconnects (session closed without reply after 30 seconds almost exactly, give or take a few milliseconds).

**Comment by matko** [comment]
This is very mysterious. There is no post-update process that runs after schema updates. There are two sources of slowdown after a schema update. The first is that traversing the full schema data might now traverse multiple layers. The other is that you might be hitting a terminusx server that doesn't have the schema in cache, whereas before it did. Neither one explains a slowdown of minutes.

Please keep us updated if you find a more reproducible way to trigger this.

**Comment by hoijnet** [comment]
Indeed mysterious. 

I have dug into it and identified a few greedy server loading scenarios that loaded the same data multiple times starting at almost the same time, including the schema, fixing that both reduced server calls, and improved performance. Some remaining code from old logic was cleaned up on my end too, connecting to /api/info and when such a call failed, it invalidated the newly loaded schema.

Fixing these reduced the occurence of the issue which was most connected to /api/info, but also other calls. I found that if I leave for a while (about 10 minutes) and then come back to do an update, I often get the error, indicating rather that it is something between TerminusX and the client. I suspect one of the proxied between us, but need to narrow it down further.

My current hypothesis is that there is some (to me) wierd timeout that causes some kept alive connections (probably in HTTP/2) that should have been declared dead, to linger.

I have not seen the issue again with my limited testing so far, but I also can't declare it overcome. I close the issue. I will ask to reopen it if and when I find a reproducible way that requires us to do something together to solve it. It might be some proxy tuning is required.

I will update here if I find something, if someone else faces a similar issue.

**Comment by hoijnet** [comment]
I took quite some time writing the previous post, and the issue happened immediately after and was indeed connected to /api/info. Could it be, on a larger schema, that there is an interplay between a non-cached server and the client running /api/info first thing, translating to a heavy schema traversal across a number of layers. If I remember, /api/info is much heaver than it needs to be, but it could also be a red herring.

If there is a short-lived stickyness of sessions to a cached server for 5-10 minutes and a schema loading with deep traversal times out, it could be something perhaps. But I doubt it. Keeping it open for a bit longer as I try to reproduce it cleanly.

**Comment by hoijnet** [comment]
For anyone else facing this, this was due to an idle timeout of our cloud provider that was set to 240 seconds for SNAT to upstream (TerminusDB). In order to fix the issue, the upstream idle_timeout in our custom http client had to be set to less than the SNAT timeout for the connections to not go stale and cause an upstreams disconnect.

What could be perhaps be done to help others is to set a the tcp keepalive socket connection option of approx 240s for the initial keep-alive packet for long-lived connections (as results my take some time to compute), but that might need to be checked in intermediate proxies one the TerminusX edge as well, and probably not an issue. 

Closing this one, sorry for the fuzz, this was on my end. All is working now!

**Comment by rrooij** [comment]
Thanks so much for figuring this out! Glad you got it working.
