### ISSUE TITLE
make the GraphQL API accept query with [ID!] type 

### ISSUE THREAD

**Issue by hannaszepesi** [terminusdb/terminusdb#1583]
**Is your feature request related to a problem? Please describe.**
When I try to query documents by id with the GraphQL API I cannot pass an array of ids. When I solve this problem with aliases, it results in a very long query. If I do that with the filter it works neither, because filtering is not possible by id.

**Describe the solution you'd like**
It would be really nice if the query accepted an array of ids. :)

**Comment by GavinMendelGleason** [comment]
We will be able to get this into dev for next week. I think we'll probably be able to release it by Thursday, but not 100% sure yet.

**Comment by matko** [comment]
Implemented in #1589
