### ISSUE TITLE
Missing documentation for @metadata class field for sys:JSON documents on schema

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1594]
**Describe the bug**
The `@metadata` Schema field field added in #1537 and #1532 is not documented in the [schema documentation](https://terminusdb.com/docs/guides/reference-guides/schema). 

**To Reproduce**
1. Search for metadata, and a reference to using `sys:JSON` is as a field is found (but not on the class level, which is supported)
2. Go to the schema documentation (https://terminusdb.com/docs/guides/reference-guides/schema)
3. search for @metadata
4. No match

**Expected behavior**
A clear and concise description of how to use `@metadata` on a type.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Documentation (last checked 2022-12-01)

**Additional context**
Really looking forward to start to use these fields, and it is clear from #1537 and #1532 how to use it, but putting the issue in for the benefit of others!

**Comment by GavinMendelGleason** [comment]
Fixed!

**Comment by hoijnet** [comment]
I think ended up in the wrong place (as part of the `@type` part), leaving the rest of the docs in an odd format. Probably should put the section between `@document` and `@base` sections as it needs to be fixed anyways?

[@metadata in Schema section](https://terminusdb.com/docs/guides/reference-guides/schema#metadata)
