### ISSUE TITLE
Documentation for dbDoc mentioned in updateDatabase for Javascript is missing

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1616]
**Describe the bug**
The documentation for dbDoc mentioned in updateDatabase for Javascript is missing. It should be possible to look up in the typeDef section, but is missing.

**To Reproduce**
1. Go to the [updateDatabase doc](https://terminusdb.com/docs/guides/reference-guides/javascript-client-reference/woqlclient#module_woqlclient..woqlclient+setapikey)
2. Notice the dbDoc reference
3. Go to [dbDetails](https://terminusdb.com/docs/guides/reference-guides/javascript-client-reference/typedef#dbdetails), assuming they are similar, there is no mention of dbDoc

**Expected behavior**
dbDoc should be documented. Also, it seems update_database is missing in the Python client, so could not look it up there either.

**Screenshots**
<img width="681" alt="image" src="https://user-images.githubusercontent.com/144317/208142056-8f1c0cce-b2ef-4e95-bfa5-93cc9b2cdfd6.png">

**Info (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by hoijnet** [comment]
In the PR, I did a small update to the documentation too, thus this one can perhaps be closed after a documentation run.

**Comment by matko** [comment]
@rrooij can you look into this?

**Comment by rrooij** [comment]
This should be solved now. :+1:

**Comment by hoijnet** [comment]
Looks great, I just had an additional though, @rrooij In reference to #1618, should metadata be added to dbDoc too? Or is there some other way to update it only?
