### ISSUE TITLE
Support @metadata JSON on data product level (and perhaps instance too?)

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1618]
**Is your feature request related to a problem? Please describe.**
When adding documentation to data products today, there are only two fields and no data structure helpful to add additional metadata to a data product (like processing instructions, branch metadata, tags etc). The main item I would like at the moment, is to be able to annotate a data product with tags, to help filter and organize multiple data products, when they are shared amongst multiple people.

When sharing access to data products, metadata needs to be the same for both data product consumers, hence a local repository of metadata is not as helpful. The best would be to have a space in the data product itself (and in the instance) to add information about data products and instances respectively.

**Describe the solution you'd like**
The idea is that this would be context data, and processed as free-form metadata, for the data product. Similar to how an `@schema` element can have a `@metadata` field with arbitrary JSON. 

For instance data this is not as clear-cut, but a read-write JSON structure on the instance would be helpful for instance admins to read and write instance data. Instance admins may write, readers only access the information. 

**Describe alternatives you've considered**
I have considered to host the metadata elsewhere, in own and custom metadata structures, but it would introduce custom data structures connected to the data product that should ideally live with the data product itself and the instance. This should probably be part of the git-for-data ecosystem, much like certain metadata for settings and similar in git belongs in the git repository.

Tags are the most important (i.e. custom key+ custom value) to add, but similar to `@schema:` `@metadata` usecases, having a JSON enables creativity and flexibility.

**Additional context**
N/A

**Comment by GavinMendelGleason** [comment]
Already implemented, but it was not documented! Documented now.

**Comment by hoijnet** [comment]
Fantastic! Does this in some way address instance level too? Should I file a separate enhancement req for that?

**Comment by GavinMendelGleason** [comment]
Oh sorry forgot about the instance level metadata! I think that should be a separate enhancement.

**Comment by hoijnet** [comment]
Could you pass a link to the documentation? Thinking it is not mentioned of the dbDoc update in #1616? Will put in a separate enhancement!

**Comment by hoijnet** [comment]
See also #1640 for instance level metadata :-)
