### ISSUE TITLE
Javascript documentation sidebar looks odd

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1626]
**Describe the bug**
Rendering of the documentation sidebar for the Javascript client seems to have gotten broken. It is hard to use the index in the current state of the documentation. Below is how the docs look currently at [Javascript Client - WOQLClient](https://terminusdb.com/docs/guides/reference-guides/javascript-client-reference/woqlclient#rebase).

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/144317/209764891-11d2b025-290f-4efd-bccc-7fc3d0b96743.png">

**To Reproduce**
1. Go to [Javascript Client - WOQLClient](https://terminusdb.com/docs/guides/reference-guides/javascript-client-reference/woqlclient#rebase)
2. Look at the sidebar

**Expected behavior**
The sidebar should continue the initial headings:
<img width="252" alt="image" src="https://user-images.githubusercontent.com/144317/209765091-18b7aafc-6cb3-4b35-943c-0cc691a77b0a.png">

**Screenshots**
See above.

**Info (please complete the following information):**
 - OS: macOS/Edge Chromium

**Additional context**
N/A

**Comment by matko** [comment]
@rrooij can you look at this?

**Comment by rrooij** [comment]
It is fixed!
