### ISSUE TITLE
Uncaught error: push_has_no_repository_head

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb#1642]
The error `push_has_no_repository_head` isn't properly catched and instead prints a stack trace.

To reproduce:

1. `./terminusdb db create admin/test`
2. `./terminusdb remote add admin/test testremote example.org`
3. `curl localhost:6363/api/push/admin/test10/local/branch/main -X POST -u admin:root -H 'Authorization-Remote: Basic YWRtaW46cm9vdAo=' -H 'Content-Type: application/json' -d '{"remote": "testremote", "remote_branch": "main"}'`

**Comment by GavinMendelGleason** [comment]
Fixed in #1813
