### ISSUE TITLE
How-To: visualise a random schema in TerminusDB

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#165]
How can I import and visualise a schema in TerminusDB?

**Comment by luke-feeney** [comment]
Goes in here:

https://github.com/terminusdb/terminusdb/blob/master/docs/How_To/visualize_schema.md

Maybe there is no good answer? Maybe we just need a workaround... but maybe not!

@KittyJose - for you1

**Comment by KittyJose** [comment]
Once you have a schema in the visualizing part is in here https://terminusdb.github.io/terminusdb/#/How_To/visualize_schema
