### ISSUE TITLE
/api/ok endpoint fails CORS, whereas /api/info doesn't

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1652]
**Describe the bug**
The `/api/ok` endpoint is great for quick connection tests. However it behaves differently from `/api/info`. Using /api/ok fails with CORS, and if checking against /api/info it works.

Have not dug deep but could be worth looking into. Likely the `Access-Control-Allow-Origin` is not set correctly.

**To Reproduce**
1. Call `/api/info` on localhost in a cross-origin scenario, success
2. Call `/api/ok` on localhost in a cross-origin scenario, fails with error below in browser

**Expected behavior**
/api/ok and /api/info should essentially work the same way. Probably the mimetype for /api/ok should be set to plain text or similar to prevent a downloaded file when "just checking".

**Screenshots**
```
Access to XMLHttpRequest at 'http://localhost:6364/api/ok' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
**Info (please complete the following information):**
 - Docker latest

**Additional context**
N/A

**Comment by matko** [comment]
This is resolved in the current dev, and will be resolved in the next release.

**Comment by hoijnet** [comment]
Great! Thanks!! Will revert back to the ok endpoint!
