### ISSUE TITLE
How-To: revert in TerminusDB

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#168]
How do I revert in TerminusDB?

Probably best to cover all the possible supported approached

**Comment by luke-feeney** [comment]
Ok - so would be good to give a How To on the various approaches.

Goes in here:

https://github.com/terminusdb/terminusdb/blob/master/docs/How_To/revert.md

@KittyJose - another one for you

**Comment by KittyJose** [comment]
This feature is on our to-do list, and is coming soon
