### ISSUE TITLE
Faster local clone/fetch/push

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#1694]
Currently the code path for a local and remote clone is exactly the same. Even for a local clone we connect to a 'remote' terminusdb and transfer a pack file. This is completely unnecessary work.

We should have a quicker path for purely local clones. I think this would require us having a special kind of remote, or a flag on a remote, saying it is actually resolvable against the local server. If this is the case, clones, fetches and pulls can be implemented differently to do local capability checking and layer swizzling instead.

**Comment by GavinMendelGleason** [comment]
Fixed in #1698
