### ISSUE TITLE
Provide terminusdb-10-to-11 upgrade as docker package

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1706]
**Is your feature request related to a problem? Please describe.**
Building rust using the latest versions on rust, and in many environments might be a challenge for some. It could be helpful to publish a docker image with the tool and a helpful instruction on how to run it with a docker command mounting the directory one wants to convert.

**Describe the solution you'd like**
Build the binary in docker and publish it as a simple docker image with a helpful instruction on how to perform the upgrade using the docker tool. Perhaps it's as simple as just providing some additional documentation on how to run an upgrade using the existing terminusdb image

```
docker run --rm -it -v -v "`pwd`"/db10:/db10 -v "`pwd`"/db11:/db11 --entrypoint=/path/to/terminusdb-10-to-11 terminusdb/terminusdb-server  convert-store -krv /db10 /db11
```

Or something like it?

**Describe alternatives you've considered**
Compiling myself and realized I will try using docker too.

**Additional context**
Will likely look at it again in the weekend to convert a local one. I'll add more here once/if I get there.

**Comment by hoijnet** [comment]
Looks like most of it already exists in a separate image:

WARNING: Must check db10/STORAGE_VERSION to be `1` first before launching!

1. Get the old database into a folder db10 in the current directory
1. Run the command below
1. Move db11 to where your terminusdb server expects it.

```
cp -r terminusdb/db_10/db/ convert/db10
docker run --rm -it -e RUST_BACKTRACE=full -v "`pwd`"/db10:/db10 -v "`pwd`"/db11:/db11 -v "`pwd`"/work10-to-11:/work10-to-11 --entrypoint=/app/terminusdb-upgrade/bin/terminusdb-10-to-11 terminusdb/terminusdb-upgrade:latest convert-store /db10 /db11 -w /work10-to-11
```

I did get an error with the above command though, so not successful yet, but it seems to launch the process. This is with an old database that has been around for a long time.

**Comment by matko** [comment]
We actually do have a docker image for this.
It is terminusdb/terminusdb-upgrade, and it is intended to work with the bootstrap script. We'll maintain this container going forward for all our upgrade needs.

It looks like in all our release chaos we missed actually updating the README for the bootstrap project though. It is a subcommand on the terminusdb-container script that can be used like so:
`./terminusdb-container upgrade`

This will take care of upgrades for people that use bootstrap. I imagine the container is also quite usable for people who have other sorts of container deploys though.
