### ISSUE TITLE
How-To: merge back into main? 

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#171]
How do I merge back into main?

**Comment by luke-feeney** [comment]
I *think* this is a console How-To, but I suppose it could be CLI or anywhere? Liverpool or Rome? 

Goes in here:

https://github.com/terminusdb/terminusdb/blob/master/docs/How_To/merge_main.md

@KittyJose could you take a look?

**Comment by KittyJose** [comment]
I have added this bit on how to merge to main using Javascript client under
https://github.com/terminusdb/terminusdb/blob/master/docs/How_To/merge_main.md
