### ISSUE TITLE
Invalid token errors yield error 500

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1727]
**Describe the bug**
Invalid tokens should not yield error 500, they should yield error 401, when using the `API_TOKEN` for authorization. This is the default way to pass tokens using the javascript client, but should behave the same as using Bearer tokens (which return a more correct 403).

Whilst the 403 could be argued for the Bearer authorization interface, it should probably return a 401 for a bad token, and a 403 for a token that is valid in general but is not authorized for the specific resource.

**To Reproduce**
1. make a GET request to api/info on a TerminusX data product using API_TOKEN to hold an incorrect token (see example below)
2. Receive error 500: `{"message":"Check tokenAPI error","err":"Invalid Api Token"}`

`curl -H "Accept: application/json" -H "API_TOKEN: asdfasdf" 'https://cloud.terminusdb.com/example-instance/api/info'`

**Expected behavior**
A 401 should be returned instead of error 500 which is confusing (not successfully processing an authorization token should not result in error 500, or there is a serious issue).

**Screenshots**
N/A

**Info (please complete the following information):**
 - OS: any - curl - TerminusX

**Additional context**
N/A

**Comment by matko** [comment]
Thanks for reporting. 500 is indeed the wrong code to use here. We'll fix it so that it is a 401/403 instead.

As a sidenote, `API_TOKEN` is deprecated. Please use `Authorization: Token <your token>` as it is more compatible with middleware.

**Comment by rrooij** [comment]
Fixed. It now returns 401. Thanks a lot for reporting!

**Comment by hoijnet** [comment]
I think API_TOKEN is still in use in the Javascript SDK, perhaps a separate issue should be created for it?

Mobila hälsningar // ... on the go...
Philippe
--
Mobil: +46701491111<tel:+46701491111>
Web: https://hoij.net<https://hoij.net/>

20 feb. 2023 kl. 13:29 skrev Matthijs van Otterdijk ***@***.***>:

﻿

Thanks for reporting. 500 is indeed the wrong code to use here. We'll fix it so that it is a 401/403 instead.

As a sidenote, API_TOKEN is deprecated. Please use Authorization: Token <your token> as it is more compatible with middleware.

**Comment by rrooij** [comment]
@hoijnet Hmmm, if I `grep` for API_TOKEN in the JavaScript client, I can't find anything that mentions it anymore. Perhaps you are on an older version? I think it was fixed here: https://github.com/terminusdb/terminusdb-client-js/commit/adab8800411f9531e00c1fda261b29a2ab613c64
