### ISSUE TITLE
How-To: save a query? 

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#173]
How do I save a query? 

If you can't do directly yet, include the work around. That is as good as golden.

**Comment by luke-feeney** [comment]
I don't think we have this implemented yet, but comes up quite a bit in the server, so would be good to give a work around of some kind.

Goes here:

https://github.com/terminusdb/terminusdb/blob/master/docs/How_To/save_query.md

@KittyJose - for u!

**Comment by KittyJose** [comment]
working example - https://terminusdb.github.io/terminusdb/#/How_To/save_query
working tutorial - https://github.com/terminusdb/terminusdb-tutorials/tree/master/woql

**Comment by KittyJose** [comment]
working example - https://terminusdb.github.io/terminusdb/#/How_To/save_query
working tutorial - https://github.com/terminusdb/terminusdb-tutorials/tree/master/woql

Closing issue
