### ISSUE TITLE
How-To: import the schema.org schemas into TerminusDB? 

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#174]
How do I import the schema.org schemas into TerminusDB?

**Comment by luke-feeney** [comment]
I know you have done plenty of extensive work on this @Cheukting, so maybe you could boil it down into a How To?

Goes in here:

https://github.com/terminusdb/terminusdb/blob/master/docs/How_To/import_schemaorg.md

If it is too long for a How-To, we could make a tutorial, but would be nice to try to boil down to the bare minimum even if it doesn't do everything

**Comment by Cheukting** [comment]
I think it makes more sense to have it in a tutorial

**Comment by luke-feeney** [comment]
That works for me - I'll remove the How-To and we can just leave it in the tutorial repo.
