### ISSUE TITLE
GraphQL query against non required field can result in "null" result.

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#1742]
If one field is missing from a multi-field document, sometimes the system will return `null`. 

Try creating a schema with two fields, the first a string, the second an array, and search for documents with the first field specified but nothing specified for the second. 

Also, does an empty array come back as empty in the GraphQL interface, or as no result? It should be the former.

**Comment by matko** [comment]
I've seen this happen when something in the graphql schema is not being generated as optional, but then the value realization returns a null anyway. It might be that.

**Comment by matko** [comment]
The exact case described in the initial report is unreproducible. The following schema returns empty arrays just fine:
```
{
  "@base": "terminusdb:///data/",
  "@schema": "terminusdb:///schema#",
  "@type": "@context"
}
{
  "@id": "Foo",
  "@type": "Class",
  "a": "xsd:string",
  "b": {
    "@class": "xsd:string",
    "@dimensions": 1,
    "@type": "Array"
  }
}
```

**Comment by matko** [comment]
Closing. We'll open a new issue when we have a reproducible example.
