### ISSUE TITLE
Adding schema with no id leads to silent failure

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#1744]
Try adding the following schema at the command line:

```json
[
    { "@type" : "@context",
      "@base" : "terminusdb:///instance/",
      "@schema" : "terminusdb:///schema#"},
    { "@type" : "Class",
      "string" : "xsd:string",
      "array" : { "@type" : "Array",
                  "@class" : "xsd:string" }
    }
]
```

**Comment by matko** [comment]
By failure, I assume you mean a prolog predicate failure somewhere?

The behavior I see when trying to insert this is that I get the cli help printed, which usually indicates predicate failure.

**Comment by matko** [comment]
Interestingly, the correct thing seems to happen when just inserting that single class document, without trying to do a full schema replace.
