### ISSUE TITLE
How-To: handle merge conflicts?

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#179]
How do I handle merge conflicts?

**Comment by luke-feeney** [comment]
This is a bit of a How To issue. We just need to spell out the work around until we have a better solution. 
In here:

https://github.com/terminusdb/terminusdb/blob/master/docs/How_To/merge_conflict.md

@GavinMendelGleason - I think you have an idea of what we might say?

**Comment by henryjcee** [comment]
Hi @luke-feeney, I'm Henry and I'm currently working on [Merge Mamba](https://github.com/marketplace/merge-mamba). If you're having trouble with merge conflicts you might find it helps to avoid them in future and it'll always be free for open source projects.

I'll be adding new features over the next few months so if there are any adjacent problems that your project would love a tool to help with, just let me know and I'll try and fit them into the roadmap.

**Comment by luke-feeney** [comment]
Hey @henryjcee ! Cool project. This thread is about merge conflicts when merging databases. TerminusDB is structured a bit like git, but is for data. 

We have some issues with merging large databases and dealing with conflicts. We'd love a tool to deal with that, but fear it might not be an adjacent problem!

**Comment by henryjcee** [comment]
> We have some issues with merging large databases and dealing with conflicts. We'd love a tool to deal with that, but fear it might not be an adjacent problem!

Ah, major apologies I misunderstood the thread! Happy to delete and apologies for hijacking your issue.

H

**Comment by luke-feeney** [comment]
don't worry about it at all! will check out merge mamba anyhow as could help on the code deployment side. 

good luck

**Comment by GavinMendelGleason** [comment]
I will close this as we've a plan for simplified merge API.
