### ISSUE TITLE
Possible bug in setof/3 call in frame module

### ISSUE THREAD

**Issue by pmoura** [terminusdb/terminusdb#18]
In the `setof/3` call in the following clause:

https://github.com/terminusdb/terminus-server/blob/82871e8522e9cf993b0f53cad8ada3994a007901/library/frame.pl#L730-L750

the Logtalk linter reports:

```logtalk
*     Suspicious call: A^(inferredEdge(B,C,A,D),(schema:document(A,D)->(E=<1->F=[A];G is E-1,document_object(A,D,G,H),H=[I,J|F]);realiser(A,K,D,E,F))) in setof/3 goal contains singleton variables [I,J]
*       while compiling object frame
*       in file /Users/pmoura/terminus-server/library/frame.pl between lines 730-750
```

The reported variables are `_Type ` and `_Id ` in the sub-goal:

```
Object = [_Type,_Id|New_Realiser]
```

This may be a false positive as in #14. Still using complex goals in all-solutions predicate calls is not ideal for performance and readability. Here, a suitably named auxiliary predicate would improve the code and simplify the `setof/3` call by also eliminating the need of existentially qualify any variables.

**Comment by GavinMendelGleason** [comment]
Indeed this is ugly and needs a rewrite. I'm going to have a go at a complete overhaul of frames after release.
