### ISSUE TITLE
How-To: delete in TerminusDB? 

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#180]
How does deleting work?

**Comment by luke-feeney** [comment]
just need to give the method as it currently stands. Step by step How To

https://github.com/terminusdb/terminusdb/blob/master/docs/How_To/delete.md

@Cheukting can you take a look?

**Comment by Cheukting** [comment]
## Delete a database with console

In the home page of the database that you want to delete, click on the delete button (see example below)

![delete graph step 1](https://assets.terminusdb.com/docs/delete-graph1.png)

Then, type out the database id to confirm (see example below)

![delete graph step 2](https://assets.terminusdb.com/docs/delete-graph2.png)

## Delete database via Python client

The `WOQLClient` provide a `delete_database` method to do so. For example:

```
>>> client = WOQLClient("https://127.0.0.1:6363/")
>>> client.delete_database("pybike")
```

**Comment by Cheukting** [comment]
@luke-feeney, please review

**Comment by luke-feeney** [comment]
Thanks!
