### ISSUE TITLE
Non-String types not returned by client.get_document or client.query_document

### ISSUE THREAD

**Issue by fischer70** [terminusdb/terminusdb#1801]
**Describe the bug**
Fetching documents using the python client API using get_document or query_document results in all values being returned as strings which can no longer be instantiated as objects because of type mismatch

**To Reproduce**
Simple Python usage to demonstrate problem.  Both TypeError exceptions are tripped when importing objects

```
schema = WOQLSchema()
class Structure(DocumentTemplate):
    _schema = schema
    _key = LexicalKey(["inchi"])
    inchi: str
    data: float

if __name__ == '__main__':
    client = Client(...)
    schema.commit(client, commit_msg="Committing schema for load", full_replace=True)

    # Create the sample object, don't worry if it's already there.
    try:
        s = Structure(inchi="somevalue", data=25.2)
        client.insert_document(s)
    except DatabaseError as de:
        # Already created
        pass

    # Try and retrieve the object directly from the iri
    t = client.get_document("Structure/somevalue")
    print(t)
    try:
        tobj = schema.import_objects(t)
    except TypeError as te:
        print(sys.exc_info())

    # Try and retrieve the object via a property query
    t = list(client.query_document({"@type": "Structure", "inchi":"somevalue"}))
    print(t[0])
    try:
        tobj = schema.import_objects(t[0])
    except TypeError as te:
        print(sys.exc_info())
```

Full traceback goes to setattr in schema.py:
```
  File "testtypes.py", line 33, in <module>
    tobj = schema.import_objects(t)
  File "python3.9/site-packages/terminusdb_client/schema/schema.py", line 705, in import_objects
    return self._construct_object(obj_dict)
  File "python3.9/site-packages/terminusdb_client/schema/schema.py", line 620, in _construct_object
    return create_obj(type_class, obj_id, params)
  File "python3.9/site-packages/terminusdb_client/schema/schema.py", line 561, in create_obj
    new_obj.__init__(new_obj, **params)
  File "python3.9/site-packages/terminusdb_client/schema/schema.py", line 142, in init
    setattr(obj, key, value)
  File "python3.9/site-packages/terminusdb_client/schema/schema.py", line 193, in __setattr__
    _check_mismatch_type(name, value, correct_type)
  File "python3.9/site-packages/terminusdb_client/schema/schema.py", line 70, in _check_mismatch_type
    check_type(prop, prop_value, prop_type)
  File "python3.9/site-packages/typeguard/__init__.py", line 764, in check_type
    check_number(argname, value, expected_type)
  File "python3.9/site-packages/typeguard/__init__.py", line 655, in check_number
    raise TypeError('type of {} must be either float or int; got {} instead'.
TypeError: type of data must be either float or int; got str instead
```
**Expected behavior**
The "data" field should be returned as a numeric value and allow instantiation of a local "Structure" object.  Note WOQL queries using the webpage are correctly typed:
`let v = Vars("obj", "inchi","data");
limit(5)
	.and(
  		triple(v.obj, "inchi", v.inchi),
  		triple(v.obj, "data", v.data)
  		)`

Result:
`[
  {
    "data": {
      "@type": "xsd:decimal",
      "@value": 25.2
    },
    "inchi": {
      "@type": "xsd:string",
      "@value": "somevalue"
    },
    "obj": "Structure/somevalue"
  }
]`

**Info (please complete the following information):**
Ubuntu 20, terminusdb 11.0.5, manual install

**Comment by GavinMendelGleason** [comment]
I'm able to get this to work in the latest code, with the result: 

```
{'@id': 'Structure/somevalue', '@type': 'Structure', 'data': 25.2, 'inchi': 'somevalue'}
{'@id': 'Structure/somevalue', '@type': 'Structure', 'data': 25.2, 'inchi': 'somevalue'}
```

Would you mind trying to install from the repo? Maybe something is going on with the release detection.

`python -m pip install git+https://github.com/terminusdb/terminusdb-client-python.git`

**Comment by rrooij** [comment]
We tested it using the latest terminusdb-client-python (10.2.2) and couldn't reproduce the issue. Perhaps you are still on an older version? You can try `pip install terminusdb-client --upgrade` to get the latest version.

**Comment by fischer70** [comment]
For posterity, I WAS using this terminusdb-client version: 

```
>>> terminusdb_client.__version__.__version__
'10.2.0'
```

Upgrading to 10.2.2 and adding a call to server info in case I've got something old on the server side doesn't change the behavior for me:
```
Client version:10.2.2
Server info:@type:api:InfoResponse;api:info:{'authority': 'terminusdb://system/data/User/admin', 'storage': {'version': '2'}, 'terminusdb': {'git_hash': 'ded94f86e71a3e3eeb475dcac2c471a3701d977b', 'version': '11.0.5'}, 'terminusdb_store': {'version': '0.19.8'}};api:status:api:success
{'@id': 'Structure/somevalue', '@type': 'Structure', 'data': '25.2', 'inchi': 'somevalue'}
(<class 'TypeError'>, TypeError('type of data must be either float or int; got str instead'), <traceback object at 0x10bb2cd80>)
{'@id': 'Structure/somevalue', '@type': 'Structure', 'data': '25.2', 'inchi': 'somevalue'}
(<class 'TypeError'>, TypeError('type of data must be either float or int; got str instead'), <traceback object at 0x10bb2c880>)
```

Pulling the git repo results in the same output.  FWIW (lots of YMMV), I didn't think it was the python client's fault, when I dug through the request being made to the server, the reply json from the server has everything as strings, but that could just be my not understanding what that should look like. 

```
result = {dict: 4} {'@id': 'Structure/somevalue', '@type': 'Structure', 'data': '25.2', 'inchi': 'somevalue'}
 '@id' = {str} 'Structure/somevalue'
 '@type' = {str} 'Structure'
 'data' = {str} '25.2'
 'inchi' = {str} 'somevalue'
 __len__ = {int} 4
```

**Comment by fischer70** [comment]
Ah got it.  I didn't blow away the database before upgrading the client.  If I delete the data product, then rerun with 10.2.2, it succeeds.  So I guess the problem is on insert with the 10.2.0 client?  

Either way, success using the 10.2.2 version:
```
Client version:10.2.2
Server info:@type:api:InfoResponse;api:info:{'authority': 'terminusdb://system/data/User/admin', 'storage': {'version': '2'}, 'terminusdb': {'git_hash': 'ded94f86e71a3e3eeb475dcac2c471a3701d977b', 'version': '11.0.5'}, 'terminusdb_store': {'version': '0.19.8'}};api:status:api:success
{'@id': 'Structure/somevalue', '@type': 'Structure', 'data': 25.2, 'inchi': 'somevalue'}
{'@id': 'Structure/somevalue', '@type': 'Structure', 'data': 25.2, 'inchi': 'somevalue'}
```

Thanks for the help and apologies for not working through the client upgrades first, should have thought of that.  I did upgrade the server, but didn't notice the client upgrade from 10.2 to 10.2.2.

**Comment by GavinMendelGleason** [comment]
Aha! I think we introduced a backward incompatibility in the schema mapping from the python client. It is now using a float instead of a decimal!
