### ISSUE TITLE
How-To: use branches for deduplication? 

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#181]
How do I use branches for deduplication?

**Comment by luke-feeney** [comment]
Not sure where to start on this one - was an issue in the server...

https://github.com/terminusdb/terminusdb/blob/master/docs/How_To/branch_deduplication.md

@GavinMendelGleason - is this for you?

**Comment by GavinMendelGleason** [comment]
This is no longer relevant.
