### ISSUE TITLE
How-To: get access to deltas directly? 

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#182]
How do I get access to deltas directly?

**Comment by luke-feeney** [comment]
Hmmmm. This is a good one. Great for a How-To. Not sure how to approach thou (client, console etc.)

Goes in here:

https://github.com/terminusdb/terminusdb/blob/master/docs/How_To/access_deltas.md

Can you take a look @Francesca-Bit

**Comment by Francesca-Bit** [comment]
this document has been removed
