### ISSUE TITLE
How-To: get the container at startup to not drop me straight into an SWI-prolog repl and then bail out. 

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#183]
How do I get the container at startup to not drop me straight into an SWI-prolog repl and then bail out.

**Comment by luke-feeney** [comment]
This was a questions that came up in the forum.

Goes in here:

https://github.com/terminusdb/terminusdb/blob/master/docs/How_To/start_container.md

Would be good to give a basic answer

@rrooij - could you take a look

**Comment by rrooij** [comment]
Made general instructions on how to run it from a container.
