### ISSUE TITLE
Deletion of property from schema allowed, but does not delete value

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#1849]
Drop a property of type integer from a schema in which this field is populated. Now re-introduce it. The data is still there. (Observed in TerminusCMS)

**Comment by GavinMendelGleason** [comment]
I'm unable to reproduce this issue on simple examples.

**Comment by hoijnet** [comment]
It sounds similar to #1548?

**Comment by hoijnet** [comment]
I left the comment as it could be a way to think about and trigger the other one too perhaps if they are similar?
