### ISSUE TITLE
How To: Set ENV variable in Bootstrap? 

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#186]
ENV variables that can be set by either setting ENV variables locally, or by creating a file called ENV that will be read on the start of the script.

This needs to be reconstituted as a How-To:

https://terminusdb.com/docs/reference/bootstrap

**Comment by luke-feeney** [comment]
I did this one! Not sure if it is all still correct so somebody might check:

https://terminusdb.github.io/terminusdb/#/How_To/ENV

Will you take a look @rrooij to see if something more/less is needed.

**Comment by rrooij** [comment]
Looked it through, looks good!
