### ISSUE TITLE
Explanation: How you should model your data? What's the best way. 

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#191]
How you should model your data? 

TerminusDB and modelling thinking to the rescue in less than 800 words of discussion.

**Comment by luke-feeney** [comment]
This goes in here:

https://github.com/terminusdb/terminusdb/blob/master/docs/Explanation/MODELHOW.md

Or can be a comment on this issue

Basically this is an extension of this blog: 

https://terminusdb.com/blog/2020/11/19/model-builder-and-data-modeling/

But with some commentary on how data modelling works in other contexts. 

@Francesca-Bit - data modeller!

**Comment by Francesca-Bit** [comment]
finished!!! I think
