### ISSUE TITLE
Explanation: What’s a delta roll up? And why would I need one?

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#196]
What’s a delta roll up? And why would I need one?

**Comment by luke-feeney** [comment]
This goes in here:

https://github.com/terminusdb/terminusdb/blob/master/docs/Explanation/DELTA.md

Or can be provided as reply to issue.

This is a slightly more discursive and evergreen version of this: 

https://terminusdb.com/blog/2020/09/15/delta-rollup/

@matko - best person for the job

**Comment by matko** [comment]
It is done.
