### ISSUE TITLE
Foreign references in documents rendered incorrectly

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1972]
**Describe the bug**
When a document is created with a foreign reference, the fetched document does not match the submitted document format. I expect the prefix to be observed, but the TerminusDB internal structure should not be exposed. 

The documentation mentions that the [format for foreign references is simply a foreign IRI](https://terminusdb.com/docs/schema-reference-guide/#codeanexamplecreatingandreferringtoaforeigntype).

Schema:
```json
[
  {
    "@base": "terminusdb:///data/",
    "@schema": "terminusdb:///schema#",
    "@type": "@context"
  },
  { "@type" : "Foreign", "@id" : "Person"},
  { "@type" : "Class", "@id" : "Event", "date" : "xsd:date", "person" : "Person" }
]
```

I expect that this document, when added, should be retrieved in the same format. See screenshots below for how it is returned incorrectly.
```json
{ "@type" : "Event", "date" : "2022-10-05", "person" : "terminusdb:///data/Person/Gavin"}
```

**To Reproduce**
1. Create a data product with the schema above
2. Add an instance of the document above
3. Get the instance of the document above
4. Diff the documents, note that the id is embedded in the object, see screenshot below

**Expected behavior**
I expect the submitted document to be the same as the retrieved document.

**Screenshots**

The retrieved document, the expectation is that person should just be the string `Person/Gavin` (the reason being that the JSON-LD @base prefix of the schema context object shortens the IRI and accurately substitutes the prefix `terminusdb:///data/`.

```json
{
  "@id": "Event/JAJ1-m_4vBOgwjLD",
  "@type": "Event",
  "date": "2022-10-05",
  "person": {
    "@id": "Person/Gavin",
    "http://terminusdb.com/schema/sys#foreign_type": "@schema:Person"
  }
}
```

Expected document:
```json
{
  "@id": "Event/JAJ1-m_4vBOgwjLD",
  "@type": "Event",
  "date": "2022-10-05",
  "person": "Person/Gavin"
}
```

**Info (please complete the following information):**
 - OS: TerminusCMS 11.1.3 via API

**Comment by GavinMendelGleason** [comment]
Should be fixed in #1976
