### ISSUE TITLE
Issue with WOQL not returning any documents.

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#1974]
**Describe the bug**
The following WOQL has changed behaviour in the last release. It does not return documents anymore. The read_document code with issue referenced in #1910 made me switch to the document interface for this code to retrieve documents. But, I suspect this issue affects other things as well.

```
        WOQL.select(
          "v:document",
          WOQL.and(
            WOQL.member("v:doc", docIds),
            WOQL.triple("v:doc", "rdf:type", "v:type"),
            WOQL.not(WOQL.eq("v:type", "rdf:List")),
            WOQL.read_document("v:doc", "v:document")
            // Reference to TerminusDB issue #1910 too
          )
        )
```

You add the id:s in docIds and it should do a read_document to fetch them.

**To Reproduce**
1. Run the WOQL code with instance ids
2. Notice how in previous versions, before 11.1.3, it returns documents
3. Note how it doesn't in current versions (just returns "document")

**Expected behavior**
I expected documents to be returned with the document variable binding.

**Screenshots**
N/A

**Info (please complete the following information):**
 - OS: TerminusCMS via DFRNT

**Additional context**
N/A

**Comment by GavinMendelGleason** [comment]
#1973
