### ISSUE TITLE
Explanation: What do YOU mean by low-code?

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#198]
What do YOU mean by low-code?

What does that mean to TerminusDB

**Comment by luke-feeney** [comment]
This goes in here:

https://github.com/terminusdb/terminusdb/blob/master/docs/Explanation/LOWCODE.md

Or you can write as a reply to this issue and we will copy across

Discussion of what low code is and what it means to us - and what TerminusDB wants to achieve with the console interfacing with the way people really work. General and workflow on console oriented. 

@KittyJose - you rule the console, give this a try!

**Comment by KittyJose** [comment]
available in https://terminusdb.github.io/terminusdb/#/Explanation/LOWCODE
