### ISSUE TITLE
GraphQL error with namespaced properties

### ISSUE THREAD

**Issue by timathom** [terminusdb/terminusdb#1984]
**Describe the bug**
In GraphiQL, there still seems to be an issue with namespaced properties. With [this schema](https://github.com/timathom/linked-art-terminusdb/blob/main/schema/CombinedLinkedArtSchemaExpanded.json) and [this dataset](https://github.com/timathom/linked-art-terminusdb/tree/main/test/dataset), the following query works:
```
query{
  crm_E33_Linguistic_Object {
    rdfs_label
    
  }
}
```
But these two do not:
```
query{
  crm_E33_Linguistic_Object {
    rdfs_label
    crm_P2_has_type {
      _type
    }
  }
}
```
```
query{
  crm_E33_Linguistic_Object {
    rdfs_label
    _path_to_crm_E21_Person(path: ".,.,.") {
      _type
    }
  }
}
```
They both throw an error:
```
{
  "errors": [
    {
      "message": "Unexpected error in graphql: error(rust_error(panic(\"This class name {db_short_name} *should* exist\")),_7356)"
    }
  ]
}
```
**To Reproduce**
1. Load the schema and dataset
2. Run the GraphQL queries in the console

**Expected behavior**
If I change the `@schema` mapping from `"@schema": "terminusdb:///schema#"` to `"@schema": "http://www.cidoc-crm.org/cidoc-crm/"`, eliminating the namespace prefix, then all queries work. I would expect them to work both with and without namespace prefixed properties.

**Info (please complete the following information):**
 - Latest TerminusCMS

**Comment by GavinMendelGleason** [comment]
Fixed in #2004
