### ISSUE TITLE
Can't start terminus on macOS 10.14.6

### ISSUE THREAD

**Issue by nemanjavuk** [terminusdb/terminusdb#2]
I've been following the instructions from the README.md, installed swi-prolog, installed hdt-cpp but whe I try to run `./start.pl` i get the following:

> ERROR: /Users/nemanjav/dev/terminusdb/library/triplestore.pl:18:
> 	source_sink `library(hdt)' does not exist
> Warning: /Users/nemanjav/dev/terminusdb/library/triplestore.pl:18:
> 	Goal (directive) failed: triplestore:use_module(library(hdt))
> ERROR: /Users/nemanjav/dev/terminusdb/library/triplestore.pl:625:20: Syntax error: Operator expected
> ERROR: /Users/nemanjav/dev/terminusdb/library/triplestore.pl:627:20: Syntax error: Operator expected
> ERROR: /Users/nemanjav/dev/terminusdb/library/json_ld.pl:34:
> 	source_sink `library(mavis)' does not exist
> Warning: /Users/nemanjav/dev/terminusdb/library/json_ld.pl:34:
> 	Goal (directive) failed: json_ld:use_module(library(mavis))
> ERROR: /Users/nemanjav/dev/terminusdb/library/api.pl:90:7: Syntax error: Operator expected
> ERROR: /Users/nemanjav/dev/terminusdb/library/api.pl:103:7: Syntax error: Operator expected
> Warning: /Users/nemanjav/dev/terminusdb/library/api.pl:122:
> 	Singleton variables: [DB]
> Warning: /Users/nemanjav/dev/terminusdb/library/api.pl:128:
> 	Singleton variables: [Auth]
> ERROR: /Users/nemanjav/dev/terminusdb/library/api.pl:128:
> 	Full stop in clause-body?  Cannot redefine ,/2
> Warning: /Users/nemanjav/dev/terminusdb/library/api.pl:131:
> 	Singleton variables: [DB]
> Warning: /Users/nemanjav/dev/terminusdb/library/api.pl:137:
> 	Singleton variables: [Data]
> ERROR: /Users/nemanjav/dev/terminusdb/library/api.pl:137:
> 	Full stop in clause-body?  Cannot redefine ,/2
> Warning: /Users/nemanjav/dev/terminusdb/library/api.pl:160:
> 	Singleton variables: [Request,Method,DB,Docid]
> % Started server at http://localhost:6363/
> 
>  ** Syncing schema in collection 'http://localhost/capability'
> ERROR: /Users/nemanjav/dev/terminusdb/start.pl:21: Initialization goal raised exception:
> ERROR: '<meta-call>'/1: Undefined procedure: triplestore:hdt_open/2
> Welcome to SWI-Prolog (threaded, 64 bits, version 8.0.3)
> SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
> Please run ?- license. for legal details.
> 
> For online help and background, visit http://www.swi-prolog.org
> For built-in help, use ?- help(Topic). or ?- apropos(Word).
> 
> ?-

What am I doing wrong? I also don't see `hdt.pl` in the `library` folder. Is that maybe the cause of the problem?

**Comment by GavinMendelGleason** [comment]
Hello!

Thanks for the message, stupid bug on my part. There are two additional
dependencies that I had forgotten about. Swipl needs to have mavis and hdt
libraries installed. You can get them with the swipl package manager. I'll
fix this in the documentation as soon as possible.

This gives an example of package installation and available packages.

https://www.swi-prolog.org/pack/list

We've just thrown this up in the last couple of weeks and have not really
launched the beta yet, it's scheduled for October, so this is really
bleeding edge!

Gavin

**Comment by GavinMendelGleason** [comment]
README updated.

**Comment by nemanjavuk** [comment]
I see that it’s still nascent. I saw a couple of videos from the Knowledge Graph Conference and I wanted to see what you’ve done. I’m also interested in WOQL. Do you have any document that describes it? :)

**Comment by GavinMendelGleason** [comment]
Previously our database was proprietary. We're repackaging everything up
and launching as 100% open source. We expect to have the WOQL documentation
ready in a few weeks.

Thanks for the questions!

Gavin
