### ISSUE TITLE
Can't quit TerminusDB desktop on Linux

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#205]
**Describe the bug**
After starting and quitting TerminusDB you will see the Terminus icon in the application tray. Quitting the application here does not help. Only killing the application from the command line works.

**To Reproduce**
This can be reproduced simply by starting the application on linux and attempting to close.

**Info (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Running 'canary' from 5-Feb desktop application

**Comment by luke-feeney** [comment]
Is this a feature of a bug - do we WANT people quitting?

**Comment by kaaloo** [comment]
Quitting working fine for me on Ubuntu 20.10.
