### ISSUE TITLE
New Docs Site Break

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#207]
Create new top level break on the [documentation page](https://terminusdb.com/documentation/) of the TerminusDB website. Something like the below image. The TerminusHub break goes to existing docs (soon to be updated) the TerminusDB goes to the new docsify site

![image](https://user-images.githubusercontent.com/53231019/107514555-bd041480-6ba1-11eb-813e-03950e3e5258.png)

**Comment by luke-feeney** [comment]
This is for @KittyJose ;-)

**Comment by spl** [comment]
Our documentation is now at <https://terminusdb.com/docs/v10.0/>.
