### ISSUE TITLE
Tutorial: Getting Started with Console

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#208]
Assume Installation already done
Create Schema
Import Data
Query Data
Use Branching

This goes in here:

https://github.com/terminusdb/terminusdb/blob/master/docs/Intro_Tutorials/Start_with_Console.md

Or can be a comment on this issue and we can move across.

Idea it to keep it simple and get the person from 0 to 1 - installation is already included in the intro, so tutorial can just refer them back to the install instructions. (but maybe we should include console specific thing there?)

@KittyJose - this is for you

**Comment by KittyJose** [comment]
Available in https://terminusdb.github.io/terminusdb/#/Intro_Tutorials/Start_With_Console
