### ISSUE TITLE
Roadmap Text

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#209]
The main TerminusDB roadmap needs to be populated. It can be fairly sparse for the moment as we work out the priorities for the next phase, but we should include an update of the text as part of every new episode. 

Here is the relevant page:

https://terminusdb.github.io/terminusdb/#/ROADMAP

@dmytri - you might take a look at putting in some text

**Comment by spl** [comment]
Our public roadmap is now at <https://github.com/orgs/terminusdb/projects/2>.
