### ISSUE TITLE
Install fails on WSL

### ISSUE THREAD

**Issue by adhalanay** [terminusdb/terminusdb#2115]
**Describe the bug**
When trying to build from source `make install-tus` fails

**To Reproduce**
1. Clone the terminusdb repository with `git clone https://github.com/terminusdb/terminusdb`
2. Run `cd terminusdb`
3. Run `make install-tus`
4. Get `-g pack_install('file:///home/andrei/terminusdb/.deps/tus', [interactive(false), git(true)]): Process "process(path(git),[-C,/home/andrei/.local/share/swi-prolog/pack/tus,pull])": exit status: 1`

**Expected behavior**
No error

**Screenshots**

**Info (please complete the following information):**
 - OS: [Arch linux on WSL 2 on Windows 11]
 - manual installation
- SWI-Prolog version 9.2.2 for x86_64-linux

**Comment by GavinMendelGleason** [comment]
If you manually invoke swipl and run the command it appears to work fine. e.g.

```prolog
?- pack_remove(tus). 
?- pack_install('file:///MY_PATHterminusdb/.deps/tus'). 
```

I'll try to figure out why the make file doesn't work.

**Comment by GavinMendelGleason** [comment]
If you manually invoke swipl and run the command it appears to work fine. e.g.

```prolog

```

I'll try to figure out why the make file doesn't work.
