### ISSUE TITLE
Console, Canary (2021-02-12) - Hub repo delete button

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb#213]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot 2021-02-12 at 13 19 54](https://user-images.githubusercontent.com/28761465/107773081-05a00700-6d35-11eb-8596-fd3c0a1b7dc2.png)

**Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - How did you run terminus-server (terminus-quickstart, using Docker directly, manual installation)
- SWI Prolog version if you're using the manual installation

**Additional context**

**Comment by Francesca-Bit** [comment]
fix css
