### ISSUE TITLE
Canary Bootstrap - WOQL.eval doesn't work! 

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#214]
Tried to run through the bank balance example and got the below result

![image](https://user-images.githubusercontent.com/53231019/107773055-fcaf3580-6d34-11eb-9997-2d729de1d7e2.png)

Works fine in master.

**Comment by luke-feeney** [comment]
@KittyJose confirmed that also an issue in dev - works fine in master as per previous report

**Comment by Francesca-Bit** [comment]
fix it in terminusdb-client
