### ISSUE TITLE
Console - delete origin behavior is strange

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb#215]
**Describe the bug**
delete origin behavior is strange

**To Reproduce**
1. Clone Bank Example on Hub
2. Make a clone of the local clone
3. Delete the 1st local clone
4. See the screen shot behavior

**Expected behavior**
Better handling?

**Screenshots**
![Screenshot 2021-02-12 at 13 30 19](https://user-images.githubusercontent.com/28761465/107774129-81e71a00-6d36-11eb-8b9c-5fb69242f633.png)
It says clone of undefined

![Screenshot 2021-02-12 at 13 30 30](https://user-images.githubusercontent.com/28761465/107774189-93c8bd00-6d36-11eb-8a49-a67b0caeaa80.png)
It still try to show the deleted origin

**Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - How did you run terminus-server (terminus-quickstart, using Docker directly, manual installation)
- SWI Prolog version if you're using the manual installation

**Additional context**

**Comment by spl** [comment]
Not relevant anymore.
