### ISSUE TITLE
Creating Place for Python Tutorials to Go

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#218]
Further to discussion we are going to split the JS and Python tutorials at the top level and we need a place to put the relevant tutorials that we can link to from the top level navigation

**Comment by Cheukting** [comment]
This is what it will look like when the new doc for the Python client went live.
![Screenshot 2021-02-18 at 23 08 04](https://user-images.githubusercontent.com/28761465/108433775-6c925400-723e-11eb-9c51-7528b2808006.png)
Changes are now in [terminusdb-client-python dev](https://github.com/terminusdb/terminusdb-client-python/commit/9d22e7271f5abe9587aa44ef67f1b713d8da3555)
