### ISSUE TITLE
Reference: CLI

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#220]
We need material for the CLI reference section in the new TerminusDB docs. Not sure where you want to put it, but we need a link for the main navigation. 

Could you have a look @GavinMendelGleason

**Comment by GavinMendelGleason** [comment]
This one? https://github.com/terminusdb/terminusdb/blob/dev/docs/CLI.md

**Comment by luke-feeney** [comment]
That's the one - thanks!

**Comment by luke-feeney** [comment]
me working in master and stuff happening in dev makes discovery a little tricky - but I'll withdraw once we get released and then workflow can return to dev first!
