### ISSUE TITLE
Reference: Store

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#221]
We need to include the reference material for store in the main navigation. Suspect it is best to keep it in the store repo and just link to that from the main navigation. 

Is it currently somewhere? Or does it need to be marshaled somehow? 

@matko - master of store

**Comment by matko** [comment]
The main store reference is up on [docs.rs](https://docs.rs/terminus-store/). Would it be ok to just link that?

**Comment by GavinMendelGleason** [comment]
Yup

**Comment by luke-feeney** [comment]
Ok - used that link - was there another store reference thing that was mentioned? Or are we good with the link?

**Comment by matko** [comment]
IMO the documentation up on docs.rs is /the/ reference. So I think that is good. Unless you think it is not.

**Comment by luke-feeney** [comment]
that's fine for me - have used that link. I just thought that @GavinMendelGleason had mentioned something else! Will close issue.
