### ISSUE TITLE
Explanation: TerminusDB Vocab

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#225]
This is a short guide to all the TerminusDB vocab - each concept with a short description and example under the word. Think this could be really useful for users - and we get these questions a lot. 

@Francesca-Bit suggested these as a start: 
```
Triple......
Object: ....
Abstract.....
Document......
```
Please add more to this thread! We can build as we develop.

Place for the text: 

https://github.com/terminusdb/terminusdb/blob/master/docs/Explanation/VOCABULARY.md

@Francesca-Bit will you get the ball rolling.

**Comment by spl** [comment]
Replaced by a glossary. See https://github.com/terminusdb/terminusdb-docs/issues/10.
