### ISSUE TITLE
Reference: White List of XSD datatypes 

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#228]
A list of all the XSD datatypes that work in TerminusDB

We will add useful additions as we go:

https://github.com/terminusdb/terminusdb/tree/master/docs/reference

**Comment by luke-feeney** [comment]
Sorry in here: 

https://github.com/terminusdb/terminusdb/blob/master/docs/reference/XSD_WHITELIST.md

**Comment by sachinbhutani** [comment]
Does uuid deserve its own data type instead of string?
