### ISSUE TITLE
Windows Desktop Console Out of Place Element in GUI

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#230]
**Describe the bug**
On the clone screen the search for publisher id box is over the ``recommendations`` element when the interface is not at maximum size.

**To Reproduce**
download windows version
click restore down button on window
view overlap

**Expected behavior**
that elements do not overlap

**Screenshots**
![image](https://user-images.githubusercontent.com/53231019/109300957-22593600-782f-11eb-92ad-8d3b7b0c0929.png)

**Info (please complete the following information):**
Windows

**Comment by KittyJose** [comment]
Overlapping issue fixed in dev
