### ISSUE TITLE
Do we need a 'contribution guide' specifically for the JS client?

### ISSUE THREAD

**Issue by luke-feeney** [terminusdb/terminusdb#238]
We have a general guide (for server), a python guide and a store guide, so we probably need a guide for people that want to contribute to the JS client.

**Comment by yashasvimisra2798** [comment]
Hey, @luke-feeney I would like to work on this issue. Can you elaborate more on what shall I add to the guide?

**Comment by spl** [comment]
We have [`Contributing.md`](https://github.com/terminusdb/terminusdb-client-js/blob/fe2f083f9ae9309bb2fa927f2f11d8cad9d3b88b/Contributing.md).
