### ISSUE TITLE
README redirects to dead documentation link

### ISSUE THREAD

**Issue by yu-eric** [terminusdb/terminusdb#241]
**Describe the typo/ misinformation**
The "Documentation" section has a link that redirects to https://terminusdb.com/documentation/ which returns 404 NOT FOUND

**Expected changes**
Change this link to https://terminusdb.com/docs/

**Comment by rrooij** [comment]
Good catch! It should indeed be updated with the new documentation URLs.

**Comment by rrooij** [comment]
Fixed in 2de02d9
