### ISSUE TITLE
xsd:nonNegativeInteger permits negative integers on cast

### ISSUE THREAD

**Issue by jbennettgit** [terminusdb/terminusdb#243]
Ubuntu 18.04 running bootstrap version 4.1.2 in docker container, via python client:

WOQLQuery().cast('-1','xsd:nonNegativeInteger','v:Value').execute(client)

returns:

{'@type': 'api:WoqlResponse', 'api:status': 'api:success', 'api:variable_names': ['Value'], 'bindings': [{'Value': {'@type': 'http://www.w3.org/2001/XMLSchema#nonNegativeInteger', '@value': -1}}], 'deletes': 0, 'inserts': 0, 'transaction_retry_count': 0}

Expected an error of some sort.

**Comment by GavinMendelGleason** [comment]
That is indeed silly - fixing for a patch now.

**Comment by GavinMendelGleason** [comment]
Fixed in e28b1f4
