### ISSUE TITLE
Casting to unknown types does not generate expected api:BadCast error

### ISSUE THREAD

**Issue by jbennettgit** [terminusdb/terminusdb#245]
Ubuntu 18.04 running bootstrap version 4.1.2 in docker container, via python client:

>> WOQLQuery().cast('0123','unknown_type','v:Value').execute(client)
yields:
{'@type': 'api:WoqlResponse', 'api:status': 'api:success', 'api:variable_names': ['Value'], 'bindings': [], 'deletes': 0, 'inserts': 0, 'transaction_retry_count': 0}

I expected a complaint.

**Comment by GavinMendelGleason** [comment]
Fixed in e28b1f4
