### ISSUE TITLE
<Response 200> object returned from execute() call

### ISSUE THREAD

**Issue by jbennettgit** [terminusdb/terminusdb#256]
Per Gavin, updated to dev server (see below) via docker container running on Ubuntu 18.04.  Also updated, via pip, the python terminusdb client version: woql.__version__. __version__ = 0.6.1.

Unable to find image 'terminusdb/terminusdb-server:dev' locally
dev: Pulling from terminusdb/terminusdb-server
...
Digest: sha256:c963490d7ff605e3ddf1e94ea0df6f4f8c8ce7c6871714f9cbe61714c1b3f7db
Status: Downloaded newer image for terminusdb/terminusdb-server:dev
terminusdb-server container started https://127.0.0.1:6363/

Running our insertion_from_csv code, which worked previously, the 2nd and subsequent calls to execute() of a query return not a dict with bindings but a <Response 200> object which appears to be something from the intermediate http traffic with the server.

python3 insert_from_csv.py 
/home/ubuntu/.local/lib/python3.6/site-packages/terminusdb_client/woqlview/woql_view.py:9: UserWarning: woqlview need to be used in Jupyter notebook.

  warnings.warn(msg)
Parsing data from equinox.csv
Committing data for Code book i:6 d:0 0.30s << works once and result dict returns 6 inserts, no deletes
WARNING: Pre-casting '1790000:490000' from AfDurrn|Social Complexity variables|Social Scale|Polity territory to a range: likely ill-formed!
WARNING: Pre-casting '3:4' from AfDurrn|Social Complexity variables|Hierarchical Complexity|Settlement hierarchy to a range: likely ill-formed!
WARNING: Pre-casting '1:2' from AfDurrn|Social Complexity variables|Hierarchical Complexity|Religious levels to a range: likely ill-formed!
Execution ERROR while Committing data for AfDurrn after 1.11s -- skipped  << caught exception during 2nd execute()
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "insert_from_csv.py", line 39, in execute_commit
    result = q.execute(client,commit_msg=msg)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/terminusdb_client/woqlquery/woql_query.py", line 448, in execute
    return client.query(self, commit_msg, file_dict=file_dict)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/terminusdb_client/woqlclient/woqlClient.py", line 1025, in query
    if result.get("inserts") or result.get("deletes"):
AttributeError: 'Response' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "insert_from_csv.py", line 277, in <module>
    assert_seshat_row(Polity, Variable, Value_From, Value_To, Date_From, Date_To, Fact_Type, Value_Note)
  File "insert_from_csv.py", line 71, in assert_seshat_row
    execute_commit(polity_query)
  File "insert_from_csv.py", line 58, in execute_commit
    print(f"{exception.msg}")

Without dicts with bindings being consistently returned we are unable to continue development.

**Comment by GavinMendelGleason** [comment]
I can't reproduce this with v1.0 of the python client. This might be a bug in an older version?

**Comment by jbennettgit** [comment]
Perhaps.  I tried to update via pip before submitting the bug but that yielded v 0.6.1 and maintained the bug.  What is the proper technique to update to the dev version of the client?  Pull from git and install directly?  Just want to follow best practice and not make things worse.  Let me know.

**Comment by Cheukting** [comment]
@jbennettgit could you try upgrading to the latest released version by `pip install -U terminusdb_client`

**Comment by jbennettgit** [comment]
Thanks that did the trick.  The current client works with the dev server on my version now.  No more <Response> objects.

**Comment by Cheukting** [comment]
You are welcome :-)
