### ISSUE TITLE
create datatypes (xsd) for sequence (auto-increment integer) and uuid

### ISSUE THREAD

**Issue by sachinbhutani** [terminusdb/terminusdb#257]
**Is your feature request related to a problem? Please describe.**
need auto increment sequence number 
need auto generated uuid 

**Describe the solution you'd like**
schema definition should allow to include a property which can be a unique sequence number (int or bigint) which can be auto-incremented on each insert. 

**Describe alternatives you've considered**

A query may be created to first read the highest id and then update new id with max id + 1, however it would not be possible to insert multiple records in a single query this way
use case for uuid: application may generate a uuid and then populate it into the database, or may require the database to generate a uuid, when application is creating a uuid it may be stored as a string, but there should also be an option for the uuid to be generated from the database and provided back to the application. 

**Additional context**
It would be great if  an auto(increment)  function can be provided like cardinality, which can be attached to existing datatype positiveInteger or integer

**Comment by spl** [comment]
Not as relevant now.
