### ISSUE TITLE
Console/hub-console - class frames/document interface - delete property button dosen't work

### ISSUE THREAD

**Issue by Francesca-Bit** [terminusdb/terminusdb#258]
**Describe the bug**
when I try to delete a document property it dosen't work 

**To Reproduce**
1. Go to 'document interface.'
2. Click on 'plus button'
3. choose a new document
4. remove a property using the "-" button
5. you can not add the property any more 
------
6. if you have 2 property of the same type it remove both

**Comment by Cheukting** [comment]
@KittyJose is this done? Can I close it?

**Comment by KittyJose** [comment]
Fix in dev, will release to canary today :)
