### ISSUE TITLE
Allow queries to submit an expected commit id and fail when it does not match

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#264]
When writing client code, it can be useful at times to be really sure that a query is executed in the state we expect a branch to be in, and to error when the database is actually in another state. I propose we add an optional parameter to the `woql` endpoint, `commit_id`. If the current commit does not match what is in `commit_id`, the server is to send back an error saying so, along with the newest commit id of the branch.

This would obviously only be relevant for queries on branches. We may wish to consider similar mechanisms for queries on the commit graph and metadata graph, but this is less important.

This is the dual of #248.

**Comment by spl** [comment]
Fixed by #911.
