### ISSUE TITLE
Can't find the cli tool on macOS

### ISSUE THREAD

**Issue by andeplane** [terminusdb/terminusdb#279]
**Describe the bug**
I'm on macOS 10.15.7 and was going to check out terminusdb, and installed it by downloading .dmg and moving the executable into /Applications. I then wanted to work with the cli tool, but can't find any reference to how to install it / where it is if it is in my current installation. The README points to https://github.com/terminusdb/terminusdb/blob/master/docs/CLI.md but it is not mentioned how i get the `terminusdb` executable in the first place.

Seems like the code is in `src/cli/main.pl`, but my only attempt `perl main.pl` didn't work, so gave up :D

**To Reproduce**
1. Be on macOS
2. Download and install TerminusDB by copying .app into /Applications
3. Start application
4. Open terminal and try to run `terminusdb`

**Expected behavior**
At least some documentation on how to get the cli, or the app automatically symlink it or something.

**Info (please complete the following information):**
macOS 10.15.7

**Comment by rrooij** [comment]
There is no compiled binary yet for MacOS unfortunately. You can build one yourself by following the instructions at: https://github.com/terminusdb/terminusdb/blob/master/docs/BUILD.md#mac-os 

Unfortunately, getting a static SWI Prolog build on MacOS is a lot of work which is required for getting a decent static binary.

We don't use Perl by the way. Prolog files and Perl files share the same file extension unfortunately.

**Comment by Cheukting** [comment]
Maybe we can have a simple wrapper in the Python client which you can use cli with the Python client.

**Comment by andeplane** [comment]
Ahh it's prolog, that explains absolutely everything :D I see that GitHub also shows this (98.9% Prolog), but didn't notice.

I can work in a linux VM to explore this anyway, so no worries. I'd appreciate something about it in the readme :) Anyway, the database looks awesome. I will explore it for my company where we need version controlled data + files as a part of our services.

**Comment by spl** [comment]
@andeplane Do you use [Homebrew](https://brew.sh/)? I'm also a macOS user, and I think it would be useful to have the CLI available through Homebrew. From my experience, it's a bit of a pain to install and use a CLI with a `.dmg` or `.app`, whereas, with Homebrew, you just `brew install terminusdb-cli` (or whatever it might be named) and `brew upgrade` to get the latest.

**Comment by rrooij** [comment]
We decided to drop the Mac OS `.dmg`. You can still compile it yourself on Mac OS although we officially don't support it.
