### ISSUE TITLE
Horizontal Scroll in Query Results

### ISSUE THREAD

**Issue by MrRaymondLee** [terminusdb/terminusdb#287]
**Is your feature request related to a problem? Please describe.**
When querying many properties, there is no horizontal scroll and thus one isn't able to see properties on the far right.

**Describe the solution you'd like**
Ability to horizontal scroll.

**Describe alternatives you've considered**
There isn't a comment out ability in the query so have to copy & paste into a text editor and remove properties to see the far right 
properties.

**Comment by Francesca-Bit** [comment]
implemented
