### ISSUE TITLE
Provide a way to easily check that a database has changed

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#298]
We currently have no way to quickly check that a database was updated. The only way is to actually open a database and see if new commits were added.

We could provide an easy first pass way to check that a database has changed by simply comparing the revision number of a label file. If this hasn't changed, for sure the database has not updated and we don't have to look any deeper. To support this we'd need to return the label revision number or label commit id, or a hash of it, in a header, which the client can submit back upon doing a request.

A second improvement on top of that would also include the commit graph layer or a hash of it in the headers.

**Comment by GavinMendelGleason** [comment]
Is this not already implemented?

**Comment by matko** [comment]
This is already implemented. The header `TerminusDB-Data-Version` is returned with each response where it is relevant, and can be submitted to ensure that the version queried hasn't been updated since, erroring otherwise.
