### ISSUE TITLE
The name of the python library is not specified

### ISSUE THREAD

**Issue by erikseulean** [terminusdb/terminusdb#306]
In the url here https://terminusdb.com/docs/terminusdb/#/How_To/graph_query it's mentioned that there's a Python client library, however the name of the library is not mentioned anywhere. (or at least I'm not spotting it). Consider adding the library name somewhere and the versions of Python supported.

**Comment by rrooij** [comment]
You are right. The library is https://github.com/terminusdb/terminusdb-client-python/ and is called `terminusdb-client` on pip, but this should be mentioned.
