### ISSUE TITLE
organization name filter is too strict

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#312]
in `organization_database_name/3`, there is a check that the organization name is not 'excluded'. This exclusion is implemented through a regex, which appears to be way too strict. For example, any instance of 'db' anywhere in the organization name will now throw an error.

This is way too strict. We should make this regex match only things that are truly problematic.

**Comment by rrooij** [comment]
Related pull request. https://github.com/terminusdb/terminusdb/pull/313

**Comment by rrooij** [comment]
Solved in that pull request
