### ISSUE TITLE
Incorrect properties for key cause silent dropping

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#334]
If you have a key in which the properties are incorrectly spelled, it will silently drop them leading to a keyless class.

```javascript
{ "@type" : "Class", 
  "@id" : "TestClass", 
  "@key" : { "@type" : "Lexical", 
                   "@feilds" : [ "name" ] } }
```

To reproduce you can try inserting this class into a schema. 

This exists in the document interface in dev branch

**Comment by spl** [comment]
Fixed as mentioned above.
