### ISSUE TITLE
xdd:coordinate fields fail

### ISSUE THREAD

**Issue by somethingelseentirely** [terminusdb/terminusdb#337]
**Describe the bug**
When trying to create an object with `xdd:coordinate` coordinates through the GUI I get the following error when trying to commit:

```
The value point(49.00882,8.43888) could not be cast as 'http://terminusdb.com/schema/xdd#coordinatePolyline'less
{
  "data": {
    "@type": "api:FrameErrorResponse",
    "api:error": {
      "@type": "api:BadCast",
      "api:type": "http://terminusdb.com/schema/xdd#coordinatePolyline",
      "api:value": "point(49.00882,8.43888)"
    },
    "api:message": "The value point(49.00882,8.43888) could not be cast as 'http://terminusdb.com/schema/xdd#coordinatePolyline'",
    "api:status": "api:failure",
    "end": "2021-06-22T14:26:39.958Z",
    "start": "2021-06-22T14:26:39.958Z",
    "duration": "2021-06-22T14:26:39.958Z"
  }
}
```

**To Reproduce**
1. Create a Schema with an object containing a `xdd:coordinate` field.
2. Try to create an instance of said object through the documents tab.
3. Get the error.

**Expected behavior**
The commit should succeed as it is a valid document..

**Screenshots**
![Screenshot from 2021-06-22 16-33-11](https://user-images.githubusercontent.com/74891396/122944023-c5523480-d377-11eb-86d8-3c6998225438.png)

**Info (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - TerminusDB Desktop on Linux / appimage

**Comment by GavinMendelGleason** [comment]
This is curious, I'll have a look at it.

**Comment by matko** [comment]
It turns out that some of the relevant code has been fixed in our canary branch, but this never made its way back into dev. This needs to be merged back. (to main, since we changed branch strategy). @GavinMendelGleason

**Comment by spl** [comment]
We're working on a release, and this will be fixed then. Thanks for the report!
