### ISSUE TITLE
Enums are partially broken in the schema editor.

### ISSUE THREAD

**Issue by somethingelseentirely** [terminusdb/terminusdb#339]
**Describe the bug**
When creating an enum and a field using it an error is thrown.

**To Reproduce**
1. Create a fresh db.
2. Create a schema containing an entity, and a document with a field using said entity.
3. Commit.

**Expected behavior**
The schema should be commited.

**Screenshots**
![Screenshot from 2021-06-22 17-41-26](https://user-images.githubusercontent.com/74891396/122956893-b3758f00-d381-11eb-8bbc-c0d44603784a.png)

**Info (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - TerminusDB Bootstrap

**Additional Information**
It is possible to commit the enum in a transaction, and then add the field in another one.

**Comment by AstroChelonian** [comment]
This will be solved by the new terminus release.
