### ISSUE TITLE
Documentation is outdated, inconsistent, and disconnected.

### ISSUE THREAD

**Issue by somethingelseentirely** [terminusdb/terminusdb#341]
**What's missing**
The naming in the tutorials, examples, and references don't match up,
e.g. WOWL.js client initialisation.
The split into terminusdb and terminushub documentation also doesn't help,
the terminushub documentation contains references on WOQL which seem to be more up to date
than the ones in the TerminusDB docs.

**Comment by spl** [comment]
Thanks for taking a look at the docs. There has unfortunately been a bit of neglect there. But we're now working diligently to improve it all.

**Comment by spl** [comment]
Check out <https://docs.terminusdb.com/>!
