### ISSUE TITLE
Documentation issue on the python intro tutorial page

### ISSUE THREAD

**Issue by mlliarm** [terminusdb/terminusdb#342]
**Describe the typo/ misinformation**
Hello, I was wandering through the docs and reached this point:

https://terminusdb.github.io/terminusdb/#/Intro_Tutorials/Start_With_Python?id=woqlviews

After that it was supposed to show something in the box beneath the text "which will result in something like this", but all I can see is white. I guess something is wrong?

I'm using Google Chrome Version 91.0.4472.124 (Official Build) (64-bit), on Windows 10.

**Expected changes**
I expected to be able to see something (I guess something like a graph) in that box of white.

**Screenshots**
See attached image.
![Capture](https://user-images.githubusercontent.com/5833270/123511958-ede27300-d684-11eb-95f3-ab10fbe8e4b7.PNG)

**Comment by kamleshjoshi8102** [comment]
> **Describe the typo/ misinformation**
> Hello, I was wandering through the docs and reached this point:
> 
> https://terminusdb.github.io/terminusdb/#/Intro_Tutorials/Start_With_Python?id=woqlviews
> 
> After that it was supposed to show something in the box beneath the text "which will result in something like this", but all I can see is white. I guess something is wrong?
> 
> I'm using Google Chrome Version 91.0.4472.124 (Official Build) (64-bit), on Windows 10.
> 
> **Expected changes**
> I expected to be able to see something (I guess something like a graph) in that box of white.
> 
> **Screenshots**
> See attached image.
> ![Capture](https://user-images.githubusercontent.com/5833270/123511958-ede27300-d684-11eb-95f3-ab10fbe8e4b7.PNG)

Hey! Can you explain a little more I can't understand  
:P

**Comment by spl** [comment]
Thanks for the report! I recall somebody saying something about bintray not being available to us, and that looks like the problem.

@Cheukting Were you looking into this?

**Comment by spl** [comment]
@Cheukting Is it enough to do <https://github.com/terminusdb/terminusdb-tutorials/pull/32>? I'm not sure if some sort of deployment is needed.

**Comment by spl** [comment]
Looks like this is fixed! Thanks again for the report. Let us know if you run into any other problems.
