### ISSUE TITLE
Bintray 

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb#343]
**Describe the bug**
We no longer use bintray for publishing but it is still mentioned in numerous places, resulting in reports like #342.

**To Reproduce**
See <https://github.com/search?q=org%3Aterminusdb+bintray&type=code> for many of the places bintray is mentioned.

**Expected behavior**
Bintray is not named everywhere it should not be named.

**Additional context**
I think we should do a full sweep of the relevant repositories and substitute every mention of bintray with something appropriate.

**Comment by spl** [comment]
I think <https://github.com/terminusdb/terminusdb-web-assets/blob/master/docs/bike-graph.html> needs to be changed to be like <https://github.com/terminusdb/terminusdb-tutorials/pull/32>.

**Comment by spl** [comment]
> I think https://github.com/terminusdb/terminusdb-web-assets/blob/master/docs/bike-graph.html needs to be changed to be like [terminusdb/terminusdb-tutorials#32](https://github.com/terminusdb/terminusdb-tutorials/pull/32).

Done by @rrooij! https://github.com/terminusdb/terminusdb-web-assets/commit/0909f9c04bc6a8af1c40c37a03f6042b1c7be0f1

**Comment by Cheukting** [comment]
@rrooij is this done and can be closed?
