### ISSUE TITLE
Path traversal documentation incorrectly formatted

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#346]
**Describe the typo/ misinformation**
On the documentation about the primitives, the information for _path regular expression_ for _path traversal_, in the patterns part, are missing the characters for some fields ("alternatives" and "any predicate")

**Expected changes**

I was expecting/presuming the following and it seems to work as per expectations:

* pipe should be representing the alternatives
* star should be representing the any predicate option

Looks like the characters fell off, might be a good idea to write out which character it is.

**Screenshots**
![image](https://user-images.githubusercontent.com/144317/123676820-b3bfcf80-d844-11eb-8470-56891a0d8f18.png)

**Additional context**
Will add separate issue for path traversal with star.

**Comment by spl** [comment]
Thanks! Looks like some easy fixes. I also see at least one typo: “predcitates.” We'll get on it!

**Comment by spl** [comment]
@hoijnet For now, you can view the revised docs at <https://github.com/terminusdb/terminusdb-client-js/blob/dev/docs/api/woql.js.md#path>. Thanks again!

**Comment by spl** [comment]
Or even better, as I just discovered: <https://terminusdb.github.io/terminusdb-client-js/#/api/woql.js?id=woqlpathsubject-pattern-object-resultvarname-%e2%87%92-woqlquery>

**Comment by hoijnet** [comment]
Thanks for the update! It looks beautiful, helpful and much clearer! 🙏

**Comment by hoijnet** [comment]
There is a regression and the issue should be reopened, the document is badly formatted anew: https://terminusdb.github.io/terminusdb-client-js/#/api/woql.js?id=path
