### ISSUE TITLE
Document Interface - PUT rest call - by web interface

### ISSUE THREAD

**Issue by Francesca-Bit** [terminusdb/terminusdb#354]
**Describe the bug**
When you trying to update a document using the PUT call throw the dashboard interface you get an error 

**To Reproduce**
1. Go to dashboard document  test interface
2. Try to replace an existed document 

Access to XMLHttpRequest at 'https://127.0.0.1:6363/api/document/admin/new_test/local/branch/main?graph_type=schema&author=admin&message=update%20document' from origin 'http://localhost:3030' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

xhr.js:177 PUT https://127.0.0.1:6363/api/document/admin/new_test/local/branch/main?graph_type=schema&author=admin&message=update%20document net::ERR_FAILED

**Comment by matko** [comment]
If you actually look at the message that came back that results in the CORS error, what is in there?
Generally, you can still see the contents despite the CORS error in your network debug view thingie. It may provide some sort of hint of what is going wrong here.

**Comment by matko** [comment]
I believe this has actually been resolved. @Francesca-Bit confirm?

**Comment by Francesca-Bit** [comment]
yes I confirm
