### ISSUE TITLE
Document Interface overwrite a schema graph

### ISSUE THREAD

**Issue by Francesca-Bit** [terminusdb/terminusdb#356]
**Describe the bug**
try to override a schema graph 

**To Reproduce**

1. POST url https://127.0.0.1:6363/api/document/admin/__DB__NAME__/local/branch/main?graph_type=schema&overwrite=true&author=admin&message=add%20a%20new%20document

Payload:
[
    {
        "@base": "terminusdb:///data/",
        "@schema": "terminusdb:///schema#",
        "@type": "@context"
    },
    {
        "@id": "Coordinate",
        "@type": "Class",
        "x": "xsd:decimal",
        "y": "xsd:decimal"
    }
]
3. See error
_{
  "api:message":"Error: no_id_in_schema_document(json{'@base':\"terminusdb:///data/\",'@schema':\"terminusdb:///schema#\",'@type':\"@context\"})\n\n\nNote: some frames are missing due to last-call optimization.\nRe-run your program in debug mode (:- debug.) to get more detail.\n\n",
  "api:status":"api:server_error"
}

**Comment by matko** [comment]
Don't use `overwrite` but `full_replace` as a query parameter if you want to do a full replacement.

Overwrite is not implemented at the moment.

You cannot use POST to insert the context document at the moment.
