### ISSUE TITLE
[new document API] Enum is not updating

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb#372]
**Describe the bug**
When updating an Enum class in the schema with replace_document() in the Python client, the backend does not get updated

**To Reproduce**
updating Team with:
`{'@type': 'Enum', '@id': 'Team', '@value': ['IT', 'Marketing']}`

but got this when call get_all_documents():
`{'@id': 'Team', '@type': 'Enum', '@value': ['Information Technology', 'Amazing Marketing']}`

which is the old Team definition

**Expected behavior**
get back what I send with replace_document()

**Additional context**
This issue appear in the latest development branch

**Comment by GavinMendelGleason** [comment]
Fixed in 61593985
