### ISSUE TITLE
Cannot bundle a database

### ISSUE THREAD

**Issue by ghpu** [terminusdb/terminusdb#379]
When trying to bundle a database with the cli : terminusdb bundle admin/my_db ,

I got the error :

Error: schema_check_failure([_17722{'@type':'vio:UntypedInstance','vio:message':_17750{'@type':'xsd:string','@value':'The subject terminusdb:///repository/data/Remote_79b96e8b0b24e00e25cf2adb6602233f has no defined class.'},'vio:subject':_17738{'@type':'xsd:anyURI','@value':'terminusdb:///repository/data/Remote_79b96e8b0b24e00e25cf2adb6602233f'}}])

The problem appears my_db being empty or full.

Infos
==
 - OS:  Ubuntu 21.04
 - terminusdb compiled from v4.2.1 tag, 
- SWI Prolog v 8.2.4

**Comment by ghpu** [comment]
As a work-around, one can comment out  "validate_validation_objects(Validations, All_Witnesses, Witnesses)" in the   run_transactions(Transactions, All_Witnesses, Meta_Data) , line 235 of src/core/transaction/database.pl .

**Comment by spl** [comment]
@ghpu Merci beaucoup for your helpful error report! The fix in our `main` branch and will be in our next major release.
