### ISSUE TITLE
When I add properties with cardinality messes up all the other document classes

### ISSUE THREAD

**Issue by KittyJose** [terminusdb/terminusdb#386]
**Describe the bug**
When I add properties with cardinality messes up all the other document classes

**To Reproduce**
` //cardinality 
  [{ "@type" : "Class",
    "@id" : "Person",
    "name" : "xsd:string",
    "age": { "@type" : "Optional", 
              "@class" : "xsd:decimal"},
    "friend_of" : { "@type" : "Cardinality", 
                    "@class" : "Person", 
                    "@cardinality" : 3 }
  }]`

after this update you loose other document classes as well of the db

**Comment by GavinMendelGleason** [comment]
Currently cardinality is unimplemented - we should throw an error instead and implement cardinality later.

**Comment by KittyJose** [comment]
Why throwing an error? if its un imlemented, is it okay to nuke it from the UI for now?

**Comment by GavinMendelGleason** [comment]
Well we shouldn't silently allow them to specify cardinalities if we don't treat them. Yes, it can be safely nuked from UI for now.

**Comment by KittyJose** [comment]
Great, closing this issue for now :)
