### ISSUE TITLE
Casting error in timestamp

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb#391]
Schema:
[{'@type': 'Class', '@id': 'my_ip', '@key': {'@type': 'Lexical', '@fields': ['timestamp']}, 'ip': 'xsd:string', 'timestamp': 'xsd:dateTime'}]
Data:
[{'@type': 'my_ip', 'timestamp': '2021-08-09T15:08:02.538620+00:00', 'ip': '0:0:0:0:0:0:0:1'}]
Error:
terminusdb_client.errors.DatabaseError: Error: casting_error("2021-08-09T15:08:02.538620+00:00",'http://www.w3.org/2001/XMLSchema#dateTime')

**Comment by Cheukting** [comment]
Can someone tell me more about how timestamp is handled in the backend? I may have to do some meshing before giving it to the backend (if backend is not handling it that is) What are the standards? It's definitely a tricky issue

**Comment by Cheukting** [comment]
timestamp is generate form here: https://github.com/singer-io/getting-started/blob/master/docs/RUNNING_AND_DEVELOPING.md#a-python-tap

**Comment by GavinMendelGleason** [comment]
Fixed in 7c0999c
