### ISSUE TITLE
Hash key is lost in a round trip

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb#395]
what goes in:

{'@type': 'Class', '@id': 'Grades', 'last_name': 'xsd:string', 'first_name': 'xsd:string', 'ssn': 'xsd:string', 'test1': 'xsd:decimal', 'test2': 'xsd:decimal', 'test3': 'xsd:decimal', 'test4': 'xsd:decimal', 'final': 'xsd:decimal', 'grade': 'xsd:string', '@key': {'@type': 'Hash', '@field': ['last_name', 'first_name', 'ssn', 'test1', 'test2', 'test3', 'test4', 'final', 'grade']}}

What comes out (via get documents):

{'@id': 'Grades', '@type': 'Class', 'final': 'xsd:decimal', 'first_name': 'xsd:string', 'grade': 'xsd:string', 'last_name': 'xsd:string', 'ssn': 'xsd:string', 'test1': 'xsd:decimal', 'test2': 'xsd:decimal', 'test3': 'xsd:decimal', 'test4': 'xsd:decimal'}

**Comment by GavinMendelGleason** [comment]
Fixed in 013a6060 by reporting an error about the form of the key.
