### ISSUE TITLE
schema error on deleting a database

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#398]
@KittyJose is reporting a bug where she occasionally gets a CORS error when she tries to delete a database.

**Comment by KittyJose** [comment]
Issue in deleting some database, receive CORS error. I suspect this occurs for only some databases coz its gone into a weird state.
If CORS is resolved i can see the response back coz as of now it fails to reload :)

**Comment by KittyJose** [comment]
Update - After @matko resolving CORS error at server side I can see the error now on deleting some dataproducts.

Error 

`{
  "api:message":"Schema check failure",
  "api:status":"api:failure",
  "system:witnesses": [
    {
      "@type":"subject_has_no_type",
      "subject":"terminusdb://system/data/UserDatabase_b7207c2d8d5d7bcd2e277010eb9f9aba"
    }
  ]
}`

**Comment by matko** [comment]
I did not resolve the CORS error :) That was Gavin.

Looks like we're trying to delete something in the system database and are leaving behind orphan triples. Interesting.

**Comment by AstroChelonian** [comment]
it is sth similar to what we resolved on Monday. I will try to find where the orphan triples are.

**Comment by spl** [comment]
I believe we've found the deletion issue. I opened up https://github.com/terminusdb/terminusdb/issues/406 to track it with more details.
