### ISSUE TITLE
Create documentation from Schema - specifically necessary for WOQL

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#404]
This needs to be generated automatically from `terminusdb/terminusdb/src/terminus-schema/WOQL.json`

This can be done either in python or javascript

https://terminusdb.github.io/terminusdb/#/reference/WOQL_JSON

**Comment by Cheukting** [comment]
To put it another way, it is to generate a md file for documentation from the json file above
