### ISSUE TITLE
Should a subdocument key have the type Random by default?

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb#411]
Is this the expected thing? Does any other key type alternative make sense?

**Comment by GavinMendelGleason** [comment]
It's possible for lexical hash for subdocuments to have meaning but they have to acquire the id from the path from the parent. This turned out to be a little intricate to programme and so I punted.

**Comment by spl** [comment]
When thinking about this, we might consider what conceptually makes the most sense to — or, alternatively, is the simplest to understand for — the schema creator who did not think it was necessary to add a `@key` to the subdocument.

**Comment by Cheukting** [comment]
Yes

**Comment by GavinMendelGleason** [comment]
Now enforced in c49f9f220c574185d28f2552407fd14a71f7c49f
