### ISSUE TITLE
Required fields are not actually required

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#438]
I've inserted the following class definition:
```
{"@id":"Moo",
 "@type":"Class",
 "name":"xsd:string"}
```

When I then insert the following object:
```
{"@type": "Moo",
 "@id": "an_absolutely_humongous_moo",
}
```

The document is inserted without problems, even though the name field is missing.

This document should have been rejected because it has a missing field.

**Comment by GavinMendelGleason** [comment]
Fixed in 2922823d4ce175171fd0f081d25a36ec03e16c69
