### ISSUE TITLE
Null cast as string silently

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#450]
JSON has a null type which should not be automatically cast to a string. 

If you have a schema with a property having an `xsd:string` type, and you attempt to insert a null, the database will silently cast it. This should not happen at all, but rather the property should be treated as not present.

**Comment by spl** [comment]
@GavinMendelGleason says it's probably something that needs to be carefully treated in `json_woql.pl`, and then you'll probably need to elaborate pairs of `predicate : null` as nothing, and that would be in `json.pl`.

**Comment by spl** [comment]
This was not fixed in the big change as of f58d7a00bb321486e79cb8913556df5f00cfd42a.
