### ISSUE TITLE
expand create_db prefix precheck and throw a different error

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#453]
currently, the `create_db` api method does a pre-check for `@base` and `@schema` being present, and being a proper url. if not, a schema error is thrown.

For error reporting purposes, it would be more useful if it threw something else, which we can detect as an api input error. A schema error could have many reasons, some of them due to our own mistakes in our internal code, but we actually know the specific reason here, and it would be good to have a proper error term for it which we could transform to a nice json message.

Secondly, currently the pre-check only checks `@base` and `@schema`. It would be good if it actually checked all the prefixes in the prefix document.

**Comment by spl** [comment]
> Secondly, currently the pre-check only checks `@base` and `@schema`. It would be good if it actually checked all the prefixes in the prefix document.

What should we be checking for all the prefixes? Just that they are all URI's?

**Comment by matko** [comment]
> > Secondly, currently the pre-check only checks `@base` and `@schema`. It would be good if it actually checked all the prefixes in the prefix document.
> 
> What should we be checking for all the prefixes? Just that they are all URI's?

Anything that'd otherwise cause the schema to fail on this URI, which as far as I can tell is just checking that it is a string and that it has a protocol.
