### ISSUE TITLE
Strange thing happend when update schema to a type that violate the existing data

### ISSUE THREAD

**Issue by Cheukting** [terminusdb/terminusdb#464]
**To Reproduce**
Load in 'indexData_sample.csv' with cli, schema will have 'volume' as float (which will be xsd:decimal)
Load in 'other.csv' with cli, schema will update 'volume as int (which will be xsd:integer), this is because all volume in this csv are 0 so pandas thinks it's int
No Error message till now
when I get the data entry form indesData_sample I get something like:
`{'@id': 'IndexData_25ec6cb430695494e4b16b5a473660a60206d4ab3ff363b786bad0526dca69d2', '@type': 'IndexData', 'adj_close': 506.899994, 'close': 506.899994, 'date': '1970-01-29', 'high': 506.899994, 'index': 'NYA', 'low': 506.899994, 'open': 506.899994, 'volume': {'@type': 'http://www.w3.org/2001/XMLSchema#decimal', '@value': 0.0}}`

Obviously volume is now confused as it is now a full path.

**Expected behavior**
Give a warning when schema update will cause something weird I guess? I can bypass the problem on the client-side but don't know if there are any though about handling it at the backend. What will be the solution?

**Comment by spl** [comment]
I'm not sure how this can/should be fixed on the backend. It seems like the client can try to verify that the data matches the schema.

**Comment by spl** [comment]
I didn't understand at first, but it seems like the input is `0.0` for an `xsd:integer` type and the output is `{"@type": "http://www.w3.org/2001/XMLSchema#decimal", "@value": 0.0}`.

**Comment by spl** [comment]
The script below creates a schema with a `value` of type `xsd:integer` and submits a `value` of `0.0`. The response is a `BadCast` error.

```sh
#!/bin/bash
set -ex

xh 'http://admin:root@localhost:6363/api/db/admin/tdb' label=l comment=c

xh 'http://admin:root@localhost:6363/api/document/admin/tdb' graph_type==schema author==a message==m <<EOF
{"@id":"J","@type":"Class","value":"xsd:integer"}
EOF

xh 'http://admin:root@localhost:6363/api/document/admin/tdb' author==a message==m <<EOF
{"@type":"J","value":0.0}
EOF
```

The output from the last command:

```json
HTTP/1.1 400 Bad Request
Connection: keep-alive
Content-Length: 350
Content-Type: application/json
Date: Mon, 20 Sep 2021 09:14:24 GMT

{
    "@type": "api:InsertDocumentErrorResponse",
    "api:error": {
        "@type": "api:BadCast",
        "api:document": {
            "@type": "J",
            "value": 0.0
        },
        "api:type": "http://www.w3.org/2001/XMLSchema#integer",
        "api:value": 0.0
    },
    "api:message": "value 0.0 could not be casted to a 'http://www.w3.org/2001/XMLSchema#integer'",
    "api:status": "api:failure"
}
```

**Comment by spl** [comment]
This is already fixed!
