### ISSUE TITLE
Concurrency problems

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#466]
Concurrent updates seem to sometimes result in success but not an update. Sometimes we get a transaction retry count exhaustion. We need a strategy to remove both of these problems.

**Comment by spl** [comment]
1. [ ] Increase transaction retry count
2. [ ] Implement write transaction locking
3. [ ] Look into alternative concurrent write transaction approaches

**Comment by spl** [comment]
Fixed.
