### ISSUE TITLE
Objects in the system graph template have wrong ids

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#488]
Some objects in the system instance template have an explicit id specified for them, which do not match the key strategy of their type. This is a problem if these objects are ever updated.

This is the case for Organization `admin_organization`, Capability `server_access`, User `anonymous`, and User `admin`.

We need to make sure the template contains the valid id. Also, when inserted originally, I'd have expected the schema checker to error on these invalid keys, which did not happen. This needs to be investigated.

**Comment by GavinMendelGleason** [comment]
Fixed in #499
