### ISSUE TITLE
return empty array on document retrieval when there's no elements

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#497]
when a document has a property which is an array, and that array is empty, the returned document will have that property missing.

It should instead return an empty list.

**Comment by Cheukting** [comment]
Will test with Python client when fixed

**Comment by AstroChelonian** [comment]
to replicate:
#!/bin/bash


# Create the database.
`
xh 'http://admin:root@localhost:6363/api/db/admin/test497' <<EOF
{"label":"l","comment":"c"}
EOF
`

# Create a type that contains an array.
`
curl -X POST -H "Content-Type: application/json" -u "admin:root" "http://localhost:6363/api/document/admin/test497?graph_type=schema&author=me&message=me" --data-binary '{"@id": "ArrayTestDoc", "@type": "Class", "array": {"@type": "Array", "@class": "xsd:string"}}'
`

# Create a document in ArrayTestDoc.
`curl -X POST -H "Content-Type: application/json" -u "admin:root" "http://localhost:6363/api/document/admin/test497?graph_type=instance&author=me&message=me" --data-binary '{"@id": "ArrayTestDoc/IdForArrayDoc", "@type": "ArrayTestDoc", "array": ["array1", "array2", "array3"]}'`


# Insert a document with an empty field array.
`curl -X POST -H "Content-Type: application/json" -u "admin:root" "http://localhost:6363/api/document/admin/test497?graph_type=instance&author=me&message=me" --data-binary '{"@id": "ArrayTestDoc/IdForArrayDocEmpty", "@type": "ArrayTestDoc", "array": []}'
`
#Read the document with the field array.
`curl -X GET -H "Content-Type: application/json" -u "admin:root" "http://localhost:6363/api/document/admin/test497?graph_type=instance"`
 
 Output:
```
 {"@id":"ArrayTestDoc/IdForArrayDoc", "@type":"ArrayTestDoc", "array": ["array1", "array2", "array3" ]}
{"@id":"ArrayTestDoc/IdForArrayDocEmpty", "@type":"ArrayTestDoc"}
```

**Comment by AstroChelonian** [comment]
Accepted this as the default behaviour for now. We might re-visit this later.
