### ISSUE TITLE
API endpoint for commit log access

### ISSUE THREAD

**Issue by LogicalDash** [terminusdb/terminusdb#500]
**Is your feature request related to a problem? Please describe.**
I have an app that would benefit from a display of recent changes to the graph.

**Describe the solution you'd like**
I'd like an API endpoint that returns an array of commit messages in a particular branch and timeframe.

**Describe alternatives you've considered**
Right now I'd have to use the CLI to generate that data ahead of time.

**Additional context**
Wouldn't this be useful when using `client.ref(..)` as well? Maybe I don't have a shell in the server, and need to look at the commit log to decide which commit I want to check out.

**Comment by GavinMendelGleason** [comment]
That's a good idea @LogicalDash - we'll put it somewhere in our roadmap.

In the meantime there are library functions for this in the python and javascript client. Are you writing your own client?

**Comment by LogicalDash** [comment]
[Is this what you mean?](https://terminusdb.github.io/terminusdb-client-python/woqlLib.html#terminusdb_client.WOQLLib.commit_chain_full) Seriously, I can't tell... I guess this issue might be interpreted as a request for documentation.

**Comment by LogicalDash** [comment]
To answer your question, I'd prefer not to implement my own client, and would like direction to the correct bits of the official clients.

**Comment by Cheukting** [comment]
Hi @LogicalDash would really know what is your use case? Are you using our official JS client or Python client? If you are using Python client I know there is a [method](https://terminusdb.github.io/terminusdb-client-python/woqlClient.html#terminusdb_client.WOQLClient.get_commit_history) that may be useful to you? So far we have no direct endpoint to get commit history yet. Like @GavinMendelGleason said we will put this in our roadmap but right now you can get around by either making a WOQL query or the Python method (that wrap the query in its call) to get it directly.

**Comment by LogicalDash** [comment]
the app is for organizing a cooperative. The org chart for the cooperative
is expected to change over time. We want to display its current state and
also a ticker of recent changes. We're using javascript.

**Comment by Cheukting** [comment]
I see, there is definitely something (maybe a WOQL query) in the JS client to get the commit history, the team was using it for developing the dashboard. I cannot say for sure on their behalf. @Francesca-Bit or @KittyJose would maybe give you some insight?

**Comment by Francesca-Bit** [comment]
Hi we have 3 method in WOQL
1) 
```
let query = WOQL.lib().commits()
/**
 * get all the commits of a specific branch
 * if a timestamp is given, gets all the commits before the given timestamp
 * @param {string} branch - the branch name
 * @param {number} limit - the max number of result
 * @param {number} timestamp - Unix timestamp in seconds
 */

WOQLLibrary.prototype.commits = function (branch="main",limit=10,timestamp=null)...
```
2)
```
const = WOQL.lib().previousCommits('m8vpxewh2aovfauebfkbzwmj4qwr5lb')
/** 
*get commits older than the specified commit id
*/
WOQLLibrary.prototype.previousCommits = function(commit_id,limit=10){

```
3)return the first commit
```
WOQL.lib().first_commit()

WOQLLibrary.prototype.first_commit = function()...
```



```

**Comment by LogicalDash** [comment]
This appears to be completely undocumented https://terminusdb.github.io/terminusdb-client-js/#/api/woqlClient.js?id=terminusdb-client-api

ctrl+f "lib", no results.

**Comment by Francesca-Bit** [comment]
It is WOQL Object no WOQLClient
I added the example in the documentation too
this is the link
https://terminusdb.github.io/terminusdb-client-js/#/api/woql.js?id=lib
