### ISSUE TITLE
Rewrite unit tests to not run as admin

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#502]
We've set up the vast majority of our unit tests to run as admin. This means that most paths skip the authorization code paths, and these end up not getting tested.

I think it'd be a good idea to change the majority of tests over to run as a normal user, so we do test these paths.

**Comment by spl** [comment]
Closing in favor of <https://github.com/terminusdb/terminusdb/issues/941#issuecomment-1038992021>.
