### ISSUE TITLE
SubmittedIdDoesNotMatchBase error is cryptic

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb#509]
As of f58d7a00bb321486e79cb8913556df5f00cfd42a, we have a wonderful new error message. I'm guessing it has to do with a mismatch between the `@key` `@type` and the provided `@id`, but it is difficult to understand. Can we improve on the error message?

Script (run from a freshly initialized store):

```sh
#!/bin/bash

set -ex

# Create the database.
xh 'http://admin:root@localhost:6363/api/db/admin/t' <<EOF
{"label":"l","comment":"c"}
EOF

# Create the schema.
xh 'http://admin:root@localhost:6363/api/document/admin/t?author=a&message=m&graph_type=schema' <<EOF
{"@type": "Class","@id": "String"}
EOF

# Post an instance.
xh 'http://admin:root@localhost:6363/api/document/admin/t?author=a&message=m' <<EOF
{"@id": "something","@type": "String"}
EOF
```

Output of last command:

```json
HTTP/1.1 400 Bad Request
connection: keep-alive
content-length: 402
content-type: application/json
date: Thu, 02 Sep 2021 17:47:32 GMT

{
    "@type": "api:InsertDocumentErrorResponse",
    "api:error": {
        "@type": "api:SubmittedIdDoesNotMatchBase",
        "api:base": "String/",
        "api:document": {
            "@id": "something",
            "@type": "String"
        },
        "api:submitted_id": "terminusdb:///data/something"
    },
    "api:message": "Document was submitted with id 'terminusdb:///data/something' which does not match base 'String/'",
    "api:status": "api:failure"
}
```

Some questions that arise from reading the above:
* What is `api:base`? Does it have anything to do with `@base`? If so, how? If not, then perhaps it should be called something else.
* Why does `String/` have the `/` at the end?
* Where did `terminusdb:///data/something` come from? I gave the `@id` `something`, but why am I seeing `terminusdb:///data/` in front of it? If `terminusdb:///data/` is the default `@base`, should `String/` also have `terminusdb:///data/` in front of it?
* Is `terminusdb:///data/something` is supposed to match `String/`? How?

**Comment by GavinMendelGleason** [comment]
Id's should match the default 'base' that is used to form their id. You can set the base to '' to get no base. The response message should return either an expanded Base (in which case you'll see `terminusdb:///data/something/BASE` or they should both be truncated so that the comparison is more obvious. 

The URI base is formed from either the `@base` provided with the class, or with the type by default.

**Comment by matko** [comment]
It may be confusing that we have both `@base` for the entire schema, and `@base` for individual types. For the schema, it denotes the default prefix for all nodes in the instance graph. For individual types, it denotes part of the prefix specific to that type. By default, this defaults to the class name but it is overridable.

So for example, if you have defined a class Person, and your schema base is 'http://base/', then ids will be like
- http://base/Person/mark
- http://base/Person/sean

Here, 'http://base/' is the `@base` for the entire schema, and then 'Person/' is the `@base` for the Person type.

It is perhaps confusing that we have these two meanings for `@base`. I'm not sure if in this stage we can still alter that.

**Comment by GavinMendelGleason** [comment]
It probably *is* possible to alter it at this point as it is auto-translated internally to a fully qualified URL. As long as we keep the fully qualified URL the same it should be ok.
