### ISSUE TITLE
Domain Sharding

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#518]
# Domain Sharding 

TerminusDB and TerminusX allow you to query across different data-products via the `Using` WOQL word. The document interface doesn't have any support for multiple data-products. But extending our current offering in a non-breaking and backward-compatible way should be relatively easy. 

Combined with object storage on TerminusX, this would give us *Infinitely scalable domain sharding*

![Screenshot from 2021-09-04 08-56-35](https://user-images.githubusercontent.com/1993386/132085812-4344284f-b931-4820-8335-34553e5d20e6.png)

## Foreign Types

Currently when we reference foreign instances we are doing so by constructing an empty class, and tagging the instance as being of this class, or we are reproducing the entire class definition internally to the data product. This doesn't scale well and ties representations which other domain teams should be in charge of. 

The way to fix this is to add a foreign type edge. This would be like `rdf:type` but instead use the tag `system:foreign_type` or something along those lines. All we would need to alter is the instance checking procedure to treat `system:foreign_type` tagged entities as opaque and terminal (they can have no exiting edges).

The reason to use a different edge from `rdf:type` is to facilitate a *union* operation. We would like to keep our strategy of only recording the principle type of an object, and never having two type designators - otherwise things will become significantly more complicated in the constraint reasoner.

This is probably a few-line change and shouldn't take more than a day and has no backward compatibility issues. This gets us 90% of the way there and we should do this and then build an example data product assemblage using Marketing, Finance and HumanResources for instance, which has links going in different directions.

## Foreign Type Discovery

Assuming we use the above approach, it makes it very easy to have a "late binding strategy" where you simply have to look the object up in another data product to get its description.  It would be handy though to know which data products it might live in! We will at some point want a data product discovery which can tell you which data products have the URI available to you (it might live in more than one because there may be different versions of the data product which you have access to).

## Union

To create assemblages for analysis it would be nice if you could create a *union* of branches from various data products and give it to the document API. Updates would always take place in the data product of which the type is defined, and reads could happen across the data products. 

To implement the union, we just need to add some sort of descriptor for unions (a list should work fine) and extend the API so that you can send in a list of paths. At the lower level reads are across collections of descriptors anyhow, but writes will require discovery of the principle. We probably could have a quick check that there is no duplication in the schema when you do an assemblage.

## Infinitely scalable domain sharding 

With a few lines of code we can reasonably claim to scale up indefinitely for assemblages of data products. Simply shard your data by domain, and use pointers across the shards. The rest are really just convenience features. 

We can produce some test examples but internally it would be extremely useful for us to pursue this approach for the system graph itself. If we shard by organisation for servers already, it probably makes sense to shard the data on this boundary as well. This will reduce the overheads to the system graph writes which currently will have difficulty scaling up.

**Comment by luke-feeney** [comment]
I like the sound of this! I particularly like the idea contained in the diagram.

**Comment by matko** [comment]
I really like the idea of using foreign_type so that we can just union graphs and have something that works! We just need to make really sure that foreign types can't also be local types, so we know absolutely sure that there cannot be duplicate triples.
