### ISSUE TITLE
Patch API

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#534]
Currently we have POST, PUT and DELETE endpoints but no PATCH. It would be extremely useful to have a way to specify only the change to the document for alterations. It would also be nice if we had some tools to construct patches from two documents, apply patches to a document and give a list of alternatives for conflicting patch application stacks.

The PATCH interface should take a minus/plus format as well as a more minimal format that just asks for a given update. The minimal format can be elaborated into a minus/plus.

Further, we need a way to construct patches out of minus/plus triple layers so that these can be reported to users in a way that is more straightforward.  The layer-stack needs to be queried and a patch plus/minus pair should be constructed for each change. 

- [x] Patch API with minus/plus (swi)
- [ ] Elaborator from positive to minus/plus (swi)
- [ ] Query interface to layer-stack (rust)
- [ ] Patch construction from layer-stack (swi)
- [ ] Patch conflict detection and application (js/python client?)

**Comment by spl** [comment]
Should we have two endpoints – one for diff to query and one for patch to update – or just one that combines the two operations?

**Comment by GavinMendelGleason** [comment]
Probably two endpoints unless there is some reason to do otherwise?

**Comment by GavinMendelGleason** [comment]
For set, optional, cardinality and the default cardinality 1 a patch can just be `"{old": {"property": "value_old"}, "new":{"property" :"value_new"}}`. However, for an array or list it's a bit trickier.

For now we can force a complete description of the before and after in a patch for lists and arrays.
