### ISSUE TITLE
Use newline-delimited, minimized JSON stream in response

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb#550]
The TerminusDB server currently sends nicely formatted streams of JSON objects, in which each object covers multiple lines and the fields are indented. They are pleasant to inspect with `curl`/`xh`. However, there are two not insignificant issues:

1. The format is not widely supported by clients. I have already run into this issue twice. In both cases, support for newline-delimited JSON (minimized JSON objects separated by newlines) was easily found, but the current format was not supported.
2. The whitespace adds a large number of bytes to the content length, which results in more time (a) printing the response, (b) sending it over the network, and (c) parsing it in the receiver. With large and/or many responses, this can make a difference.

While I have enjoyed being able to easily read the JSON responses, I think the priority – and, therefore, the default – should be a standard format that is also efficient. We can always add, say, an HTTP request header that requests prettily printed JSON.

**Comment by matko** [comment]
We already have this.

if you specify `minimized=true` as one of the query parameters, json objects will come out newline delineated.

**Comment by spl** [comment]
Great! Yes!
