### ISSUE TITLE
Ensure Lexicals over optionals work

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#570]
There's some uncertainty over what lexicals over optionals do right now, and if it is the right thing. Better get that checked.

**Comment by AstroChelonian** [comment]
To replicate:
#!/bin/bash

set -ex

Create the database.
```
xh 'http://admin:root@localhost:6363/api/db/admin/test570' <<EOF
{"label":"l","comment":"c"}
EOF

```
#Create a schema with an optional field and a lexical key.
`curl -X POST -H "Content-Type: application/json" -u "admin:root" "http://localhost:6363/api/document/admin/test570?graph_type=schema&author=me&message=me" --data-binary '{"@id": "Doc", "@type": "Class", "optional_field": {"@type": "Optional", "@class": "xsd:string"}, "@key": { "@type" : "Lexical", "@fields" : ["optional_field"]}}'`

Add something in the optional field.
`curl -X POST -H "Content-Type: application/json" -u "admin:root" "http://localhost:6363/api/document/admin/test570?graph_type=instance&author=me&message=me" --data-binary '{"@type": "Doc", "optional_field": "string"}'`

 Omit the optional field.
`curl -X POST -H "Content-Type: application/json" -u "admin:root" "http://localhost:6363/api/document/admin/test570?graph_type=instance&author=me&message=me" --data-binary '{"@type": "Doc"}'`

When the optional field is omitted, the following error occurs:
```

{
  "api:message":"Error: missing_key('terminusdb:///schema#optional_field',json{'@id':_6198,'@type':'terminusdb:///schema#Doc'})\n  [46] throw(error(missing_key('terminusdb:///schema#optional_field',...),_6250))\n  [44] catch('<garbage_collected>','<garbage_collected>','<garbage_collected>') at /usr/lib/swi-prolog/boot/init.pl:533\n  [42] api_document:api_insert_document_(instance,transaction_object{commit_info:commit_info{},descriptor:branch_descriptor{branch_name:\"main\",repository_descriptor: ...},inference_objects:[],instance_objects:[...],parent:transaction_object{descriptor: ...,inference_objects:[],instance_objects: ...,parent: ...,schema_objects: ...},schema_objects:[...]},<stream>(0x7f1388009760),_6332) at /home/astrochelonian/Documents/terminusdb/src/core/api/api_document.pl:188\n  [41] '$bags':findall_loop(_6448,'<garbage_collected>',_6452,[]) at /usr/lib/swi-prolog/boot/bags.pl:99\n  [40] setup_call_catcher_cleanup('$bags':'$new_findall_bag','$bags':findall_loop(_6506,...,_6510,[]),_6488,'$bags':'$destroy_findall_bag') at /usr/lib/swi-prolog/boot/init.pl:614\n  [36] '<meta-call>'('<garbage_collected>') <foreign>\n  [35] database:with_transaction_(query_context{all_witnesses:false,authorization:'terminusdb://system/data/User/admin',bindings:[],commit_info:commit_info{author:me,message:me},default_collection:branch_descriptor{branch_name:\"main\",repository_descriptor: ...},files:[],filter:type_filter{types: ...},prefixes:_6718{'@base':\"terminusdb:///data/\",'@schema':\"terminusdb:///schema#\",'@type':'Context',api:'http://terminusdb.com/schema/api#',owl:'http://www.w3.org/2002/07/owl#',rdf:'http://www.w3.org/1999/02/22-rdf-syntax-ns#',rdfs:'http://www.w3.org/2000/01/rdf-schema#',sys:'http://terminusdb.com/schema/sys#',vio:'http://terminusdb.com/schema/vio#',woql:'http://terminusdb.com/schema/woql#',xdd:'http://terminusdb.com/schema/xdd#',xsd:'http://www.w3.org/2001/XMLSchema#'},selected:[],system:system_descriptor{},transaction_objects:[...],update_guard:_6642,write_graph:branch_graph{branch_name:\"main\",database_name:\"test570\",organization_name:\"admin\",repository_name:\"local\",type:instance}},api_document:(...;...),_6592) at /home/astrochelonian/Documents/terminusdb/src/core/transaction/database.pl:220\n  [34] setup_call_catcher_cleanup(database:true,database:with_transaction_(...,...,_6834),_6812,database:true) at /usr/lib/swi-prolog/boot/init.pl:614\n  [30] '<meta-call>'('<garbage_collected>') <foreign>\n  [29] catch(routes:(...,...),error(missing_key('terminusdb:///schema#optional_field',...),context(_6936,_6938)),routes:do_or_die(...,...)) at /usr/lib/swi-prolog/boot/init.pl:532\n  [28] catch_with_backtrace('<garbage_collected>','<garbage_collected>','<garbage_collected>') at /usr/lib/swi-prolog/boot/init.pl:582\n\nNote: some frames are missing due to last-call optimization.\nRe-run your program in debug mode (:- debug.) to get more detail.\n\n",
  "api:status":"api:server_error"
}%                   
```

**Comment by matko** [comment]
So long story short, optional fields in lexical keys are treated exactly the same as the nonoptional variant. Their value is used to construct the lexical key (taking no special steps on account of its optional-ness), and if it's missing, a huge ugly error is thrown because they id building strategy expected it to be there.

**Comment by GavinMendelGleason** [comment]
A variant of 2. 

We should have the key formed with an out-of-band value to ensure that we get a valid lexical key which can not experience collisions whether the value is there or not.

The out of band value can be an unencoded '+' for the "none" condition, or we can encode the value with a "Some+{value}" prefix, where Some is literally anything (including nothing).

**Comment by matko** [comment]
@AstroChelonian I'm fixing this today.

**Comment by matko** [comment]
So one thing that would be nice is if people make an existing field optional or remove the optional restriction, any existing objects that did have the property set remain valid. So an out-of-band value for 'none' is probably best.
