### ISSUE TITLE
Audit the API to make sure input names are URI-encoded

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb#578]
We should probably accept only URI-encoded names for things that appear in our URIs (organization name, database name, branch name, others?). Therefore, we should reject any names that are not URI-encoded before they are stored in the database.

**Comment by spl** [comment]
Is this completely handled by the SWI-Prolog route handler?

**Comment by GavinMendelGleason** [comment]
I believe so.

**Comment by spl** [comment]
Look in pull and rebase operations, since these use an input document with a location field.
