### ISSUE TITLE
Passwordless Login

### ISSUE THREAD

**Issue by robertross** [terminusdb/terminusdb#580]
I'm always frustrated when I try to loginor signup to the dashboards and it says...
 
" Wrong email or password. "

**Describe the solution you'd like**
a passwordless identity confirmation process

**Describe alternatives you've considered**
A password-reset link feature or link... 

**Additional context**
I was under the impression that I already had an account when I tried to register via the login screen but actually needed to signup but still was getting " Wrong email or password. " or other password related validation errors

**Comment by luke-feeney** [comment]
Hello! Yes - this is a serious problem. We are about to deliver a new sign in and sign up flow that should make everything clearer, but waiting for designers to give us some screens. Annoying, but it is temporary!

**Comment by GavinMendelGleason** [comment]
We have a password reset link now.
