### ISSUE TITLE
Type error doesn't tell you where the problem is

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb#587]
The error explains the problem (excusing the use of `dict`, which is Prolog-specific) but doesn't tell you where the problem is.

```sh
#!/bin/bash
set -ex

xh 'http://admin:root@localhost:6363/api/db/admin/tdb' label=l comment=c

xh 'http://admin:root@localhost:6363/api/document/admin/tdb' graph_type==schema author==a message==m <<EOF
{"@id":"Child","@type":"Class","@key":false}
EOF
```

```json
HTTP/1.1 400 Bad Request
Connection: keep-alive
Content-Length: 299
Content-Type: application/json
Date: Wed, 15 Sep 2021 11:47:44 GMT

{
    "api:message": "Type error for false which should be dict",
    "api:status": "api:failure",
    "system:witnesses": [
        {
            "@type": "vio:ViolationWithDatatypeObject",
            "vio:literal": false,
            "vio:message": "Type error for false which should be dict",
            "vio:type": "dict"
        }
    ]
}
```

**Comment by GavinMendelGleason** [comment]
That is indeed a very irritating message. We should be defensive about the type going into the key and report early if its not valid.

**Comment by matko** [comment]
Also, looks like this error is not following the proper format for api errors, where it specifies what response it is part of.

**Comment by GavinMendelGleason** [comment]
It's because it's actually being translated from a generic python error at the very top level...

**Comment by spl** [comment]
We should drop the `vio` error handler and use the new and improved `api_error` handler.
