### ISSUE TITLE
Log authentication information

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#615]
When a user is authenticated, it'd be good if we logged who they are and how they authenticated, so we can associate operations in the log with actual people.

**Comment by Francesca-Bit** [comment]
we can do this with the cloud-api

**Comment by matko** [comment]
IMO we should do both.
For terminusdb we need to consider the standalone scenario as well as the scenario where terminusdb is deployed as part of a larger cloud solution. So terminusdb should log what it knows, cause there may not be a frontend like with terminusx.
Furthermore, due to bugs terminusdb and cloud-api may have different opinions on who is actually being authenticated, and that's exactly the sort of thing we need to be able to spot when digging in the logs.
