### ISSUE TITLE
empty branch problems

### ISSUE THREAD

**Issue by Francesca-Bit** [terminusdb/terminusdb#619]
**Describe the bug**

1. **An empty branch does not create an empty schema, so if you try to add a new document in this branch you'll get the following error :**
{
  "@type":"api:InsertDocumentErrorResponse",
  "api:error": {
    "@type":"api:SchemaCheckFailure",
    "api:witnesses": [ {"@type":"context_not_found"} ]
  },
  "api:message":"Schema check failure",
  "api:status":"api:failure"
}

2.  **if you perform a query against an empty branch you'll get the following error message:**

{
  "api:message":"Error: prefix_error('@base','User/auth0%7C614ceb4c2a17ef006a6c5951')\n  [35] throw(error(prefix_error('@base','User/auth0%7C614ceb4c2a17ef006a6c5951'),_23890))\n  [34] literals:prefixed_to_uri('User/auth0%7C614ceb4c2a17ef006a6c5951',_23940{api:'http://terminusdb.com/schema/api#',owl:'http://www.w3.org/2002/07/owl#',rdf:'http://www.w3.org/1999/02/22-rdf-syntax-ns#',rdfs:'http://www.w3.org/2000/01/rdf-schema#',sys:'http://terminusdb.com/schema/sys#',vio:'http://terminusdb.com/schema/vio#',woql:'http://terminusdb.com/schema/woql#',xdd:'http://terminusdb.com/schema/xdd#',xsd:'http://www.w3.org/2001/XMLSchema#'},'terminusdb://system/data/User/admin') at /app/terminusdb/src/core/triple/literals.pl:531\n  [32] woql_compile:assert_pre_flight_access(query_context{all_witnesses:false,authorization:'User/auth0%7C614ceb4c2a17ef006a6c5951',bindings:[],commit_info:_24094{},default_collection:branch_descriptor{branch_name:\"ttttt\",repository_descriptor: ...},files:[],filter:type_filter{types: ...},prefixes:_23940{api:'http://terminusdb.com/schema/api#',owl:'http://www.w3.org/2002/07/owl#',rdf:'http://www.w3.org/1999/02/22-rdf-syntax-ns#',rdfs:'http://www.w3.org/2000/01/rdf-schema#',sys:'http://terminusdb.com/schema/sys#',vio:'http://terminusdb.com/schema/vio#',woql:'http://terminusdb.com/schema/woql#',xdd:'http://terminusdb.com/schema/xdd#',xsd:'http://www.w3.org/2001/XMLSchema#'},selected:[],system:transaction_object{descriptor: ...,inference_objects:[],instance_objects: ...,schema_objects: ...},transaction_objects:[...],update_guard:_24064,write_graph:branch_graph{branch_name:\"ttttt\",database_name:\"test\",organization_name:\"hehjuejkjek\",repository_name:\"local\",type:instance}},limit(10^^ ...,t(...,...,...))) at /app/terminusdb/src/core/query/woql_compile.pl:1020\n  [31] woql_compile:compile_query(limit(10^^ ...,t(...,...,...)),_24242,query_context{all_witnesses:false,authorization:'User/auth0%7C614ceb4c2a17ef006a6c5951',bindings:[],commit_info:_24094{},default_collection:branch_descriptor{branch_name:\"ttttt\",repository_descriptor: ...},files:[],filter:type_filter{types: ...},prefixes:_23940{api:'http://terminusdb.com/schema/api#',owl:'http://www.w3.org/2002/07/owl#',rdf:'http://www.w3.org/1999/02/22-rdf-syntax-ns#',rdfs:'http://www.w3.org/2000/01/rdf-schema#',sys:'http://terminusdb.com/schema/sys#',vio:'http://terminusdb.com/schema/vio#',woql:'http://terminusdb.com/schema/woql#',xdd:'http://terminusdb.com/schema/xdd#',xsd:'http://www.w3.org/2001/XMLSchema#'},selected:[],system:transaction_object{descriptor: ...,inference_objects:[],instance_objects: ...,schema_objects: ...},transaction_objects:[...],update_guard:_24316,write_graph:branch_graph{branch_name:\"ttttt\",database_name:\"test\",organization_name:\"hehjuejkjek\",repository_name:\"local\",type:instance}},_24246) at /app/terminusdb/src/core/query/woql_compile.pl:614\n  [30] query_response:run_context_ast_jsonld_response(query_context{all_witnesses:false,authorization:'User/auth0%7C614ceb4c2a17ef006a6c5951',bindings:[],commit_info:_24094{},default_collection:branch_descriptor{branch_name:\"ttttt\",repository_descriptor: ...},files:[],filter:type_filter{types: ...},prefixes:_23940{api:'http://terminusdb.com/schema/api#',owl:'http://www.w3.org/2002/07/owl#',rdf:'http://www.w3.org/1999/02/22-rdf-syntax-ns#',rdfs:'http://www.w3.org/2000/01/rdf-schema#',sys:'http://terminusdb.com/schema/sys#',vio:'http://terminusdb.com/schema/vio#',woql:'http://terminusdb.com/schema/woql#',xdd:'http://terminusdb.com/schema/xdd#',xsd:'http://www.w3.org/2001/XMLSchema#'},selected:[],system:transaction_object{descriptor: ...,inference_objects:[],instance_objects: ...,schema_objects: ...},transaction_objects:[...],update_guard:_24526,write_graph:branch_graph{branch_name:\"ttttt\",database_name:\"test\",organization_name:\"hehjuejkjek\",repository_name:\"local\",type:instance}},limit(10^^ ...,t(...,...,...)),_24476) at /app/terminusdb/src/core/query/query_response.pl:20\n  [28] '<meta-call>'('<garbage_collected>') <foreign>\n  [27] catch(routes:(...,...),error(prefix_error('@base','User/auth0%7C614ceb4c2a17ef006a6c5951'),context(_24762,_24764)),routes:do_or_die(...,...)) at /usr/lib/swipl/boot/init.pl:532\n  [26] catch_with_backtrace('<garbage_collected>','<garbage_collected>','<garbage_collected>') at /usr/lib/swipl/boot/init.pl:582\n\nNote: some frames are missing due to last-call optimization.\nRe-run your program in debug mode (:- debug.) to get more detail.\n\n",
  "api:status":"api:server_error"
}

**Comment by matko** [comment]
It appears that the context is missing.

For newly created databases (which also start with an 'empty' branch), we create a fake initial commit containing just the context, which is replaced upon the very next commit. We probably forgot to do this for branches. I'll look into it.

**Comment by matko** [comment]
One open problem here is that it is unclear which context object the branch should be initialized with. When inheriting from another branch, it's clear that their context object is used, but without any sort of shared history, nothing can really be known.

As an initial approach, just copying from main may work.

**Comment by matko** [comment]
Similarly, it's unclear if the new branch is supposed to be schemaless or not. Again, we can inherit from main, but imo it's a bit dodgy. Really this information should be coming in from the api.

**Comment by GavinMendelGleason** [comment]
I think the plan should be API information is optional, and main becomes the prototype object if it is not supplied. This gives us backward compatibility and we should later start asking the user what they want as we move forward.
