### ISSUE TITLE
optimize concurrency issue

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb/terminusdb#636]
Running optimize concurrently sometimes leads to missing branches. 

It is as yet unclear *which* level the optimize is being run on which leads to the error. We need to try and recreate a race condition by firing many updates concurrently with optimizations.

**Comment by matko** [comment]
This was due to a bug in terminus-store and has been fixed in https://github.com/terminusdb/terminusdb-store/pull/84.
