### ISSUE TITLE
Upgrade to swipl 8.4

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#637]
swipl 8.4 has just been released. Let's try to upgrade to it.

**Comment by spl** [comment]
Do we continue testing against 8.2 and supporting it?

**Comment by matko** [comment]
In my opinion, we should just support latest stable, and not be afraid to use its features. So we should also drop testing against 8.2. Unless you think there's a good reason to keep supporting 8.2. Right now I don't think there's any particular 8.4 feature we were waiting for.

Strangely, at least one test in the connect_handler test hangs indefinitely for me after upgrading. So some work will need to be done to do this upgrade.

**Comment by spl** [comment]
I don't mind dropping 8.2 support. TerminusDB is more of an application than a library, so we don't need to support users on multiple versions. I would like to be able to use 8.4 features, especially the error exit codes, which we are working around in our build for 8.2.

**Comment by spl** [comment]
Merge this when done: https://github.com/terminusdb/terminus_store_prolog/pull/29

**Comment by spl** [comment]
Tests pass for me on macOS.

**Comment by spl** [comment]
Let's wait for at least the SWI-Prolog 8.4.1 release, which should have fixes for several issues we've found.

**Comment by spl** [comment]
I'm pushing this through to get <https://github.com/SWI-Prolog/packages-http/commit/9bfa494b523685d23722c2a0b7739a6a93d04b8e>, which will be used to fix #825.
