### ISSUE TITLE
TerminuxX page crash on entering set value

### ISSUE THREAD

**Issue by zenkuro** [terminusdb/terminusdb#641]
**Describe the bug**
All element dissapear from terminusx document page when I start entering value of a set field

**To Reproduce**
1. Create a document with string set field
2. Try to add text to it

**Expected behavior**
No idea... text should be entered, or some error should be showed that that will guide me on how to enter set fields

**Screenshots**
...

**Info (please complete the following information):**
 - OS: Fedora 33 Firefox 81
 - TerminusX online version
 - 
**Additional context**
...

**Comment by spl** [comment]
Hi @zenkuro. Thanks for the bug report! Sorry we didn't respond earlier. We've fixed a number of issues since then. Is this still a problem for you?

**Comment by spl** [comment]
We're closing for now. Feel free to open the issue again if you still find a problem.
