### ISSUE TITLE
Schema: make @comment in @documentation optional

### ISSUE THREAD

**Issue by fidelthomet** [terminusdb/terminusdb#667]
**Is your feature request related to a problem? Please describe.**
When documenting a Class in the schema with `@documentation` and `@properties` I also need to provide `@comment`

```json
{
  "@id": "Entity",
  "@type": "Class",
  "@documentation": {
    "@comment": "Any entity",
    "@properties": {
      "description": "Description of the entity"
    }
  },
  "description": "xsd:string"
}
```
↑ this works fine
↓ this returns a Schema check failure
```json
{
  "@id": "Entity",
  "@type": "Class",
  "@documentation": {
    "@properties": {
      "description": "Description of the entity"
    }
  },
  "description": "xsd:string"
}
```

**Describe the solution you'd like**
`@comment` should be optional

**Describe alternatives you've considered**
Always provide `@comment` – this is probably best practice but it can be be a bit tedious 🙃

**Comment by spl** [comment]
I just realized we already have this issue at <https://github.com/terminusdb/terminusdb/issues/612>. Thanks for the report, however.
