### ISSUE TITLE
Schema: Storing arbitrary class/property metadata

### ISSUE THREAD

**Issue by fidelthomet** [terminusdb/terminusdb#668]
**Is your feature request related to a problem? Please describe.**
I have data that describe classes and properties which I want to store in my schema.

Use cases:
- Importing data from external sources (e.g. storing that a class `Person` is equivalent to `wd:Q5` and its property `scm:birthplace` to `wdt:P19` on Wikidata)
- Storing colours or icons related to classes and properties which can be used in an frontend application

**Describe the solution you'd like**
Something similar to `@documentation` – maybe called `@metadata`:
```js
{
  "@id": "Person",
  "@type": "Class",
  "@documentation": {
    "@comment": "A person",
    "@properties": {
      "place_of_birth": "The persons birthplace"
    }
  },
  "@metadata": {
    "wikidata_class": "wd:Q5",
    "color": "indigo"
  },
  "place_of_birth": {
    "@type"  : "Optional",
    "@class" : "Place",
    "@metadata": {
      "wikidata_property": "wdt:P19",
      "icon": "map.png"
    }
  }
}
```

**Describe alternatives you've considered**
The above proposal would be quite easy to use and – i imagine – not that hard to implement either. But I also see some value for more structured approaches (i.e. letting users define a set of properties classes and properties can have).

One option would be to create `ClassMetadata` and `PropertyMetadata` classes in the schema and store the arbitrary metadata in the instance graph. This is almost already possible, the only issue being that it doesn't seem to be possible to have a _link property_ that links to the type `owl:Class` (if I don't want to specify the class a `ClassMetadata` document is referring to as a string).

In my eyes it doesn't really make sense to store that sort of metadata on the instance graph. Instead I could imagine – no idea if this is technically feasible so this is purely speculative – a schema of a schema which would allow me to define custom `@`properties, maybe prefixed with `@meta_`.
```js
{
  "@id": "Person",
  "@type": "Class",
  "@documentation": {
    "@comment": "A person",
    "@properties": {
      "place_of_birth": "The persons birthplace"
    }
  },
  "@meta_wikidata_class": "wd:Q5",
  "@meta_color": "indigo"
  "place_of_birth": {
    "@type"  : "Optional",
    "@class" : "Place",
    "@meta_wikidata_property": "wdt:P19",
    "@meta_icon": "map.png"
  }
}
```

**Comment by spl** [comment]
This seems similar to https://github.com/terminusdb/terminusdb/issues/669.
