### ISSUE TITLE
Schema object documentation annotations

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#669]
**Is your feature request related to a problem? Please describe.**

I am missing what, in the previous version, existed as a label on schema elements; to enable a flexible description of the schema object.

To bring the fluidity of versioned code to versioned data; most things should be mutable–including schema element names that may change as the data product evolves. I had envisioned using random ids for schema elements (such as document and subdocument schema definitions), and use labels for the names of them. 

Most schema changes happen early in defining a model, but sometimes it is hard to get the wording right immediately before understanding the domain fully; and it would make sense with a fluid label.

To have a label for the schema solves this as it can be changed later, whereas having an id would lead to continuous use of the old (incorrect) term for something in evolving schemas. In code, refactoring is an option - I could make the argument it would help here too (if one wants to). The description document element is used for a textual description of the schema, and could be coerced into a json to be a more rich description of the schema/which is could ingestable for computers too, but it would be to misuse the field.

What could be helpful for schema implementers (as in my case), is schema annotation, where the implementer would be choosing what kind of schema annotations would be necessary for their specific use cases. In my case, label is helpful, someone else might have specific properties they want to annotate a class with (such as a connected query type or name of it, others might want to store class i18n label names for internationalization of their classnames, or just a unit of measure for values contained in a subdocument, unsure if I would model it that way though). 

The example of the WOQL schema below illustrates the point; it seems you needed specific annotations on the class for the AST and the name of it in the case of the named Query, you might have other cases with different needs.

```
{ "@id" : "NamedQuery",
  "@type" : "Class",
  "@documentation" : {
      "@comment" : "A named query names a specific query for later retrieval and re-use.",
      "@properties" : { 
                        "name" : "The name of the NamedQuery to be retrieved",
                        "query" : "The query AST as WOQL JSON" }
              },
  "@key" : { 
             "@type" : "Lexical",
             "@fields" : [ "name" ] 
         },
  "name" : "xsd:string",
  "query" : "Query" }
```

A more free-form key such as "@properties" above with a flat namespace as shown would be a more flexible approach for schema annotation, whilst not breaking the strict schema checking, and enabling to keep the metadata within the data product itself at all times.

I believe the choice should be there for adding an optional label, and that an @documentation item called label would be helpful to have; for those that want to use labels for their schema elements, where id and label differ, or making the transition.

Additional considerations for this feature includes i18n (internationalisation) of the label (and perhaps of the description and each property as well), and the ability to add other related annotations, that could be both machine-orientated, and human-orientated, for provenance, integration instructions, property validation/sanitisation/allowable values, and other needs of data model developers. 

The "@documentation"/"@properties" as a JSON object notation (with fairly free naming of the properties inside) with @comment being a valid optional part used in the Product Model UI as you do now, looks neat as done in the WOQL Schema. 

An alternative would be to add an "@annotation"/{} JSON object side by side of "@documentation", or as a property in "@documentation". See the solution descriptions below.

**Describe the solution you'd like**

In order of preference, the following solutions could make sense:

1. Add an @annotation namespace (next to the @documentation namespace) with free-form key/value pairs for the document/subdocument definition that can hold arbitrary information about the document/subdocument/enum, its properties or other relationship with the rest of the world
2. Add an @annotation key/value object within @documentation (same as above)
3. Extend the @documentation element to support arbitrary key/value pairs, including @label, @description, and any other key/value pair (unsure if this is a good idea though, just a top-of-mind idea)
4. Add @label/title as an allowable entry added to the @documentation entry

**Describe alternatives you've considered**
A workaround is to put a JSON object into the description field that contains both label and description key/values.

**Additional context**

**Comment by spl** [comment]
This seems similar to https://github.com/terminusdb/terminusdb/issues/668.

**Comment by hoijnet** [comment]
Indeed very similar, but applied to different problem spaces. For perspective, in my code I am storing a free-form base64 JSON object in the comment field to allow for arbitrary annotations which is a workaround. I have not yet had the time to explore what to put in there in detail, but will be validating the field using JSON schema so it will follow a consistent form.

A different approach, mentioned in a different issue, is to allow arbitrary references to the schema classes and properties themselves as instance values, enabling arbitrary annotations to be made using existing constructs. The latter would be a significantly more extensible approach and enable a large number of additional use cases. What would need to be added is a link type (or something like it) that can point to a schema element as part of the instance value.

I agree and believe the two issues can be reasoned about together.

**Comment by hoijnet** [comment]
The more I work with the schema and instances of it, I see the need for makers to be able to add their schema annotations. A way that would be superhelpful is likely a JSON arbitrary object of arbitrary shape would do the trick, and even better would be to create it of a subdocument shape.

To make it even more useful at scale is to reason that there will be multiple schema writers/clients, and each would like to have their own such JSON arbitrary object; thus a namespaced variant would work better. It could be part of the json, but better make the semantics explicit and have the namespace expectations defined in the schema (i.e. an IRI that references an arbitrary object so that each don't have to retrieve the full set. Also, each structure could potentially be larger depending on use cases.

This would help a lot, I already created meta-schema instances of a MetaSchema element and it doesn't feel right (even if it works). Ordinary users should not be able to affect the schema and behaviours of it by changing its metadata.

Hope for it to make the roadmap =)

**Comment by GavinMendelGleason** [comment]
We will put this on the road map for sure.
