### ISSUE TITLE
Not possible to add enum property to document

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#672]
**Describe the bug**
Trying to add an enum property to a document type I get a failure to update the schema

**To Reproduce**
1. Go to Data Product Modeller 
2. Click on document type schema to edit
3. Go to properties tab
4. Add property type enum
5. Add name of property (tried different names)
6. Select precreated enum (no description added)
7. Save
8. See error, "Failed to update schema graph" - error 400 from the backend with no explanation or debugging information

**Expected behavior**
The enum property should be added

**Screenshots**
![image](https://user-images.githubusercontent.com/144317/136650807-ea395b5e-388b-44fb-9775-8f93b14853f6.png)

**Info (please complete the following information):**
 - OS: macOS. Microsoft Edge browser (Chromium-based)
 - TerminusX console

**Comment by spl** [comment]
Thanks, @hoijnet!
