### ISSUE TITLE
Use of WOQL IsA Class yields "Not well formed WOQL JSON-LD"

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#689]
**Describe the bug**
I get the error "Not well formed WOQL JSON-LD" when using the IsA WOQL class. I use it in a similar way as I have in previous release 4, but getting an error. 

**To Reproduce**
1. Go to WOQL console in TerminusX
2. Add query below
3. Click Run...
4. See error in console (http response 400 details)

I expect below query to be seen as well-formed.
```
WOQL.and(
    WOQL.triple("v:a", "v:b", "v:c"),
    WOQL.isa("v:a", "@schema:MyDocumentType")
)
``` 

**Expected behavior**
I expect the query to be successful and not return that it's malformed WOQL. In essence a reply with documents that are of type, or types that subsumes, MyDocumentType:

**Screenshots**
I'm getting error "Not well formed WOQL JSON-LD" when using the IsA WOQL class in queries. I have used it in the previous version, but now it's no longer working. I expect that I should be able to perform the following query:

```
{
  "@type":"api:WoqlErrorResponse",
  "api:error": {
    "@type":"vio:WOQLSyntaxError",
    "vio:path": ["and", "query" ],
    "vio:query": {
      "@type":"IsA",
      "element": {"@type":"NodeValue", "variable":"a"},
      "type": {"@type":"NodeValue", "node":"@schema:MyDocumentType"}
    }
  },
  "api:message":"Not well formed WOQL JSON-LD",
  "api:status":"api:failure"
}
``` 

**Info (please complete the following information):**
 - OS: TerminusX and Docker image 10.0.7 (same error)

**Additional context**
N/A

**Comment by hoijnet** [comment]
For anyone else facing the same issue, I managed to use sub as a workaround until resolved:
```
WOQL.sub("MyDocumentType", "v:classesImplementingType"),
WOQL.triple("v:a", "rdf:type", "v:classesImplementingType"),
```
If you use it in multiple places, make `classesImplementingType` unique per use.

**Comment by spl** [comment]
This is fixed now. Let us know if you run into something like this again. Thanks!

**Comment by hoijnet** [comment]
Will do! Will be helpful in developing and refactoring queries further! Thanks for fixing!
