### ISSUE TITLE
`client.author()` undefined after `client.setApiKey(accessToken)`

### ISSUE THREAD

**Issue by fidelthomet** [terminusdb/terminusdb#748]
## Describe the bug
The [documentation on connecting with WOQLClient](https://terminusdb.com/docs/v10.0/#/terminusx/start-with-a-client?id=connect-with-woqlclient) (and the TerminusX profile page) offer this code snippet:

```js
const client = new TerminusDBClient.WOQLClient(
  "https://cloud.terminusdb.com/cloudabc/",
  {
    user: "user@email.com",
    organization: "cloudabc"
  }
)

client.setApiKey(process.env.TERMINUSDB_ACCESS_TOKEN)
```

When following these Instructions, `client.author()` (or `client.user()`) will return `undefined`. This does not seem to cause much of an issue at first – the Document Interface can be used without issues and `client.query(WOQL…)` can be used for read operations. But when trying to add/delete/update triples and quads TerminusX returns a rather incomprehensible `existence_error` (see #677).

## Fix(es)
This issue can (and probably should) be fixed on three levels: Documentation, JS-Client, and Server

### Documentation

Good news! It just works when the Access Token is not set with `client.setApiKey()` but instead is provided as `connectionParams` in `new TerminusDBClient.WOQLClient()` or `client.connect()`.

```js
const client = new TerminusDBClient.WOQLClient(
  "https://cloud.terminusdb.com/cloudabc/",
  {
    user: "user@email.com",
    organization: "cloudabc",
    jwt: process.env.TERMINUSDB_ACCESS_TOKEN
  }
)

```

### JS-Client

Currently, [`user` is only stored when `connectionParams` provide a `key` or `jwt`](https://github.com/terminusdb/terminusdb-client-js/blob/964976f957de453c250f065934502b07b4865160/lib/connectionConfig.js#L81-L82). And even then, [calling 
`client.setApiKey(accessToken)` makes `client.user()` undefined.](https://github.com/terminusdb/terminusdb-client-js/blob/964976f957de453c250f065934502b07b4865160/lib/woqlClient.js#L58-L60)

But what's the purpose of `client.setApiKey` anyways? Is there any use case for setting the API key without immediately (re–)connecting to TerminusX?

### Server

The document interface allows to make changes without providing the author/user. So why is it required when using `client.query(WOQL.…)`?

**Comment by Francesca-Bit** [comment]
thanks for point it out ,
the user have to be set when you initialise the woqlClient, so this is a bug, 
it worked before, in any case I'll fix it.
we need to review woqlClient, it is better have only one way to do the things

About client.setApiKey (accessToken) is useful 
if you have a token that expires in 10 minutes and you need to set a new one.

I'll check why this method remove the author

**Comment by Francesca-Bit** [comment]
I fixed the bug 
`const client = new TerminusDBClient.WOQLClient(
  "https://cloud.terminusdb.com/cloudabc/",
  {
    user: "user@email.com",
    organization: "cloudabc"
  }
)

client.setApiKey(process.env.TERMINUSDB_ACCESS_TOKEN)`

It works correctly now, the user is not removed.

In any case I fixed the bug, but I would like to review WOQLClient 

We planned to rename the class, so I will review the classes methods too
Any suggestion is welcome.

**Comment by fidelthomet** [comment]
Thank you!
