### ISSUE TITLE
Content-Type text should be rejected with proper error

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb#760]
When using the API and putting a JSON document with content-type text, it displays "No field X" instead of a proper error message that the content-type should be json.

**Comment by spl** [comment]
> When using the API and putting a JSON document with content-type text

Can you be more specific? I've fixed a number of places that weren't checking `Content-Type` (e.g. https://github.com/terminusdb/terminusdb/pull/751). I'm sure there are more places where it's needed, but you'll have to tell us which routes you're using.
