### ISSUE TITLE
Users and Organizations API updates

### ISSUE THREAD

**Issue by Francesca-Bit** [terminusdb/terminusdb#771]
Operations desired:
* Create a user
* Delete a user
* Create an organization
* Delete an organization
* Add a user to an organization
* Remove a user from an organization
* Get all organizations for a user
  * Get all organizations for the authenticated user
* Get all databases to which a user has access
  * Get all databases to which the authenticated user has access

**Comment by spl** [comment]
See also <https://discuss.terminusdb.com/t/ganymede-sustainable-food/280/5>:

<blockquote>
The biggest issue I’m dealing with right now is the changes in version 10. I’m mostly focused on simplifying (automating) the deployment (with Docker) for each organisation. Other issues are lower down on my list.

I’m having to infer what best practice is for setting up an organisation on an instance based on issues, comments, and code, as the docs seem to be missing that key part, so any advice or guidance on what we should be looking for there would be good.

The docs cover changing organisation names, adding users to organisations, etc. Adding an organisation and authenticating / role management is less clear.

My understanding is that this has to be done with the default user (admin) in the first instance, currently using authentication through the bearer token; I have a OIDC / OAuth2 solution for long-term, but that’s outside of the scope of the experiments we’re currently running against it.
</blockquote>

**Comment by spl** [comment]
I've updated the summary. Here are @Francesca-Bit's previous comments:
- get all the organizations and roles (organization level) of a current user (`/api/organizations`)
- get all the databases and roles (databases level) of a current user, I was thinking that we'll need roles related with databases too (`/api/organizations/:orgid/databases`)

**Comment by Francesca-Bit** [comment]
This function will return the list of organizations and databases
terminusdb-client-js:
tmpClient.getUserOrganizations().then(result=>{console.log})
the result will be like this 
[
  {
    "@id":"Organization/my_team",
    "@type":"Organization",
    "databases": [
      {
	"@id":"UserDatabase/5efbe4c00aabad2738b332cb3db306c8d49779eda7319aa3af3ee9....",
	"@type":"UserDatabase",
	"comment":"test",
	"creation_date":"2022-01-13T15:05:53.337Z",
	"label":"test",
	"name":"test",
	"state":"finalized"
      }
    ],
    "name":"my_team"
  }]

**Comment by spl** [comment]
This could include <https://github.com/terminusdb/terminusdb/issues/954>.

**Comment by GavinMendelGleason** [comment]
Fixed in #1265
