### ISSUE TITLE
Text encoding issues in document query

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb#825]
Consider the following script:

```sh
#!/bin/bash
set -ex

# Delete and create a new database
xh DELETE 'http://admin:root@localhost:6363/api/db/admin/tdb' || true
xh 'http://admin:root@localhost:6363/api/db/admin/tdb' label=l comment=c

# Insert the schema
xh 'http://admin:root@localhost:6363/api/document/admin/tdb' graph_type==schema author==a message==m <<EOF
{"@id":"X","@type":"Class","@key":{"@type":"Lexical","@fields":["s"]},"s":"xsd:string"}
EOF

# Insert an instance with a non-ASCII string
xh 'http://admin:root@localhost:6363/api/document/admin/tdb' author==a message==m <<EOF
{"@type":"X","s":"Kurt Gödel"}
EOF

# Fetch the instances
xh 'http://admin:root@localhost:6363/api/document/admin/tdb'
```

The output from the last command is:

```json
{
    "@id": "X/Kurt%20G%C3%83%C2%B6del",
    "@type": "X",
    "s": "Kurt GÃ¶del"
}
```

Observations:
* `@id` is URL-encoded. Does it need to be for JSON? It means more work comparing the value passed in.
* `s` is ugh.

**Comment by spl** [comment]
Similar output with `curl`:

```sh
#!/bin/bash
set -ex

# Delete and create a new database
curl -X DELETE 'http://admin:root@localhost:6363/api/db/admin/tdb'
curl -X POST -H 'Content-Type: application/json' 'http://admin:root@localhost:6363/api/db/admin/tdb' -d @- <<EOF
{"label":"l","comment":"c"}
EOF

# Insert the schema
curl -X POST -H 'Content-Type: application/json' 'http://admin:root@localhost:6363/api/document/admin/tdb?graph_type=schema&author=a&message==m' -d @- <<EOF
{"@id":"X","@type":"Class","@key":{"@type":"Lexical","@fields":["s"]},"s":"xsd:string"}
EOF

# Insert an instance with a non-ASCII string
curl -X POST -H 'Content-Type: application/json' 'http://admin:root@localhost:6363/api/document/admin/tdb?author=a&message=m' -d @- <<EOF
{"@type":"X","s":"Kurt Gödel"}
EOF

# Fetch the instances
curl 'http://admin:root@localhost:6363/api/document/admin/tdb'
```

Output of the last command:

```json
{"@id":"X/Kurt%20G%C3%83%C2%B6del", "@type":"X", "s":"Kurt GÃ¶del"}
```

**Comment by spl** [comment]
I haven't figured out if the printing of `GÃ¶del` is due to my terminal. I have no problem typing `Gödel` or `echo`-ing it. The following don't change the output:

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

I wonder if TerminusDB is actually sending UTF-8 or ASCII / ISO 8859-1.

**Comment by spl** [comment]
Also, I first ran into this while developing a test. The bad encoding of `ö` makes it difficult to compare inputs and outputs.

**Comment by spl** [comment]
> `@id` is URL-encoded. Does it need to be for JSON? It means more work comparing the value passed in.

To answer my own question, I guess it does need to be. It's an abbreviated IRI after all.

**Comment by spl** [comment]
Okay, so the real issue here is that the server doesn't properly support UTF-8. Here's my evidence.

If the internal representation of `Gödel` was correct, we might URL-encode it as NodeJS does:

```
$ node
> encodeURI('ö')
'%C3%B6'
```

Instead, we're encoding it as follows:

```
$ node
> encodeURI('Ã¶')
'%C3%83%C2%B6'
```

**Comment by GavinMendelGleason** [comment]
We just don't do any guesswork about charset - it needs to be sent by the client.

```shell
$ curl -X POST -H 'Content-Type: application/json; charset=utf-8' 'http://admin:root@localhost:6363/api/document/admin/tdb?author=a&message=m' -d @- <<EOF
{"@type":"X","s":"Kurt Gödel"}
EOF
> > ["terminusdb:///data/X/Kurt%20G%C3%B6del" ]
$ curl 'http://admin:root@localhost:6363/api/document/admin/tdb'

{"@id":"X/Kurt%20G%C3%B6del", "@type":"X", "s":"Kurt Gödel"}
```

**Comment by spl** [comment]
> We just don't do any guesswork about charset - it needs to be sent by the client.

@GavinMendelGleason I see. But we are assuming a default encoding. Should we change the default charset to UTF-8?

[RFC 8259](https://datatracker.ietf.org/doc/html/rfc8259#section-8.1) says:

> JSON text exchanged between systems that are not part of a closed ecosystem MUST be encoded using UTF-8.

So, it seems to me that `Content-Type: application/json` should imply `charset=utf-8` unless `charset` is otherwise provided.

**Comment by spl** [comment]
It seems like the JSON predicates are doing the right thing by default:

```prolog
?- open_string("{\"a\":\"Gödel\"}", Stream), json:json_read_dict(Stream, Dict).
Stream = <stream>(0x7fd1f7b98470),
Dict = _{a:"Gödel"}.

?- open_string("{\"a\":\"Gödel\"}", Stream), json:json_read(Stream, Term).
Stream = <stream>(0x7fd1f3461810),
Term = json([a='Gödel']).
```

**Comment by GavinMendelGleason** [comment]
I wasn't aware of RFC 8259. I'd say the fix in the server would be a relatively minimal PR. You could also put in a bug report to SWIPL. I'm not sure how the HTTP server is deciding on the default charset but we might also be able to set that.
