### ISSUE TITLE
Add README to DOCS folder

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb#837]
There should be a README pointing to the documentation repo or page, since people might get the impression that the `docs` folder is the only documentation out there. There is already a link to the full documentation in the README file, but users might still get a bit confused if they don't read it thoroughly.

**Comment by luke-feeney** [comment]
are we using the docs folder for anything other than the release notes? Could move it elsewhere (like the docs repo!). Maybe better then to just get rid of the docs folder from the main repo?

**Comment by GavinMendelGleason** [comment]
I think all of those docs are necessary for a repo since they are developer focused / contributor guides, build guides etc. And better in a subfolder than in the main so we don't push down the readme too much.

**Comment by luke-feeney** [comment]
All the docs are developer focused thou - seems better to either centralize in a single docs repo or to distribute to different relevant repos. We can always link to the contributor guides. Doesn't really matter if it is in a subfolder?

**Comment by GavinMendelGleason** [comment]
It's unusual to not get your contributor guide / build guide etc. in the repo - violates the principle of least surprise. And it isn't necessary to have it elsewhere so I think it should just live here.

**Comment by GavinMendelGleason** [comment]
There is a difference between developers and people who are going to be doing builds, forks, clones of the repo and then making contributions. I meant contributing developers above rather than users of the database.

**Comment by luke-feeney** [comment]
the build guide here looks to be different than the one in our official docs: https://terminusdb.com/docs/v10.0/#/install/install-from-source-code 

We have multiple locations that need to be maintained separately - perhaps just a contributing.md for the repo and get rid of the docs folder to remove the confusion & push people to update docs centrally?

**Comment by GavinMendelGleason** [comment]
Yeah, totally agree we shouldn't have 2! It's *very* odd not to have the build instructions in the repo though - I don't think I've ever encountered it, and if I did I'd be very annoyed!

**Comment by GavinMendelGleason** [comment]
Agree we have to pick one - I'd strongly favour repo for build instructions, but willing to defer if others think otherwise.

**Comment by luke-feeney** [comment]
see: https://github.com/terminusdb/terminusdb/pull/844

**Comment by luke-feeney** [comment]
According to discussion, I think this should be just the repo specific CONTRIBUTING.md, CODE_OF_CONDUCT.md and BUILD.md

The remainder might be better handled in the main docs and not in specific repos? Maybe we should move/replicate in the main docs repo. 

@GavinMendelGleason @rrooij @mark-terminusdb 

![image](https://user-images.githubusercontent.com/53231019/145807013-5ad79ff5-790c-4360-b84d-3d601ab4b447.png)

**Comment by spl** [comment]
Done in d94145d099b26214acc183fe690be5669002734c
