### ISSUE TITLE
Temporal property typo

### ISSUE THREAD

**Issue by andtheWings** [terminusdb/terminusdb#838]
**Describe the bug**
When selecting from the options for temporal properties, one of the options says "Duraction" rather than "Duration".

**To Reproduce**
In graph view of TerminusX, select a document. Click to its property tab, click on add property, click on temporal property, one of the options is "Duraction".

**Expected behavior**
It should say "Duration"

**Info (please complete the following information):**
Web TerminusX Gui

**Comment by spl** [comment]
Thanks for the report! We released an update to TerminusX with a spelling correction.
