### ISSUE TITLE
Update documentation for open_descriptor

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb#851]
In `src/core/transaction/descriptor.pl`, `open_descriptor/5` is documented as `det`, but multiple uses of it are wrapped with `do_or_die`, which, I believe, should only be necessary with predicates that are not deterministic.

* Which is wrong: the documentation of `open_descriptor` or the `do_or_die` uses of it?
* If `open_descriptor` is semi-deterministic, should it be made deterministic by throwing an exception as the last clause?

---

https://github.com/terminusdb/terminusdb/blob/0b18276532f5b62af9aa28b1e4c1388990523781/src/core/transaction/descriptor.pl#L392

https://github.com/terminusdb/terminusdb/blob/0b18276532f5b62af9aa28b1e4c1388990523781/src/core/api/api_document.pl#L86-L87

https://github.com/terminusdb/terminusdb/blob/0b18276532f5b62af9aa28b1e4c1388990523781/src/core/api/api_document.pl#L105-L106

https://github.com/terminusdb/terminusdb/blob/0b18276532f5b62af9aa28b1e4c1388990523781/src/core/api/api_document.pl#L117-L118

https://github.com/terminusdb/terminusdb/blob/0b18276532f5b62af9aa28b1e4c1388990523781/src/core/api/api_document.pl#L144-L145

https://github.com/terminusdb/terminusdb/blob/0b18276532f5b62af9aa28b1e4c1388990523781/src/core/api/db_pull.pl#L40-L41

**Comment by spl** [comment]
Also, there seems to be an apparent disconnect between the `open_descriptor` documentation of the second and third arguments and their actual usage in the definition:

| Doc | Def |
| --- | --- |
| `@Read_Graph_Descriptor has type list(collection_descriptor)` | `commit_info` |
| `@Write_Graph_Descriptor has type list(collection_descriptor)` | `transaction_object` |

**Comment by GavinMendelGleason** [comment]
Documentation has drifted from implementation. It's semi-det and we are largely expecting it to be.

**Comment by spl** [comment]
Thanks! Just for my edification, for which cases should it fail without throwing an exception?

**Comment by GavinMendelGleason** [comment]
Failure means that there was no way to resolve the descriptor - but the caller has more information about the context. You could throw but then you would have to catch and rethrow - it's easier just to fail if it isn't resolved.

**Comment by GavinMendelGleason** [comment]
It could be done either way of course.

**Comment by spl** [comment]
Makes sense. So we just need to update the documentation.

1.  It should be `semidet` with an explanation.
2. The argument documentation should be updated to reflect the implementation.
