### ISSUE TITLE
No documentation explaining how to authenticate to a personal instance using curl or direct HTTP API

### ISSUE THREAD

**Issue by montaropdf** [terminusdb/terminusdb#858]
**Describe the bug**
Hello,

I am running a local instance with the docker image of version 10.0.13. I haven't found, yet how one can actually authenticate to the instance using curl or using the HTTP API with another language than javascript or python.

Except for disabling HTTPS, I use the default values in the ENV file for running the container.

Using the Python client, I can connect without issues to the server and perform any requests I want.

**Example1 with curl**
```
curl -k 'http://localhost:6363/api'
{
  "api:message":"Path not found: /api",
  "api:path":"/api",
  "api:status":"api:not_found"
}
```

**Example2 with curl**
```
curl -k 'http://localhost:6363/api/document/admin/medialib'
{
  "action":"'@schema':'Action/instance_read_access'",
  "api:message":"Access to 'UserDatabase/c414760cae05173a7621c25e56a4c78fa0a3180c0e61f03b8ced332e3d99fb6d' is not authorised with action '@schema':'Action/instance_read_access' and auth anonymous",
  "api:status":"api:forbidden",
  "auth":"anonymous",
  "scope":"'UserDatabase/c414760cae05173a7621c25e56a4c78fa0a3180c0e61f03b8ced332e3d99fb6d'"
}
```

**Expected behavior**
Finding the article or page describing the authentication mechanism, with proper examples. And, of course, being able to authenticate properly to the terminusdb instance, with any languages or tools, and perform requests against it.

**Info (please complete the following information):**
 - OS: Fedora 34
 - How did you run terminus-server: using Docker directly

**Comment by spl** [comment]
Hi @montaropdf. You're absolutely right! We're currently working on improving our HTTP API documentation. You can look at the following document to see the current progress. Hopefully that will help you out in the meantime.

https://github.com/terminusdb/terminusdb-docs/blob/http-api-curl-ref/md/reference/reference-api.md

If you have any suggestions, we're tracking this work at <https://github.com/terminusdb/terminusdb-docs/issues/23>. Thanks for trying out TerminusDB!
