### ISSUE TITLE
Can't have @properties comments without a set @comment on a type

### ISSUE THREAD

**Issue by hoijnet** [terminusdb/terminusdb#862]
**Describe the bug**
It should be possible to set a `@properties` comment without having to also add a value of at least one byte in `@comment` on a type.

**To Reproduce**
1. Call the API, adding a property comment (in `@properties`) in a type
2. Ensure @comment is not set on the type
3. Submit the type update

**Expected behavior**
A key in @properties should be possible to set without adding a value to the @comment key. It would be ok though to force the @comment key with an empty string `""` as an alternative.

**Screenshots**
```
{
  "@type":"api:ReplaceDocumentErrorResponse",
  "api:error": {
    "@type":"api:SchemaCheckFailure",
    "api:witnesses": [
      {
	"@type":"no_comment_on_documentation_object",
	"class":"terminusdb:///schema#Node",
	"object":"terminusdb:///schema#Node/documentation/Documentation"
      }
    ]
  },
  "api:message":"Schema check failure",
  "api:status":"api:failure"
}
```
**Info (please complete the following information):**
 - OS: N/A, through the API
 - TerminusX (2021-01-02), i.e.
 - TerminusDB internal storage version | 1
 - TerminusDB version | 10.0.13
 - TerminusDB store version | 0.19.5

**Additional context**
This has bit me a few times already, and it would be ok with an empty string, but having to set a value (just a space) in the comment as the @property key is added feels odd.

**Comment by hoijnet** [comment]
This has a fairly significant impact on user experience in the way I use the property comment to help the user. I chose to wait for JSON annotations until (hopefully) they become available instead of misusing the property comment field. It would be great to get fixed so I don't have to add a space or dot or something to the comment field for a workaround as I want to be mindful of users existing graphs and not change what they don't expect to get changed.

**Comment by hoijnet** [comment]
Thanks, confirmed to be fixed in the new release! Thanks a lot @GavinMendelGleason @spl @matko for the fix!!!

🥳

**Comment by hoijnet** [comment]
There seems to be a regression or an issue I have not seen once the mandatory comment got fixed. It seems there must be an empty string provided for @comment for @properties to be saved in the graph. 

If `@comment` is not provided, the Schema checker will not complain, but also, items in @properties will be lost silently with the transaction coming through.

In brief:
* with `@comment`  + `@properties` = success
* `@comment`  without `@properties` = success
* `@properties` without `@comment`  = dropped `@properties` and successful save (like if no `@documentation` was provided)

Before the change made in this issue, the schema checker prevented data loss, but required users to add both comment and properties. It was changed to allow property comments without `@comment`, but they are lost without `@comment` provided.

**Comment by spl** [comment]
Thanks, @hoijnet. In the future, don't worry about creating a new issue even if you think it's related to an old one. We'll follow this up on #1041.
