### ISSUE TITLE
Missing document in DB API does not close connection

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb#864]
**To Reproduce**
1. Start the server
2. Try the curl command: `curl localhost:6363/api/db/admin/MyNewDatabase -u admin:root -X POST -H 'Content-Type: application/json'`

**Expected behavior**
A closed connection and an error, instead of keeping the connection open. It works correctly when I supply an empty document:

```
curl localhost:6363/api/db/admin/MyNewDatabase -u admin:root -X POST -H 'Content-Type: application/json'` -d '{}'
```

**Information**

Using the latest dev docker

**Comment by spl** [comment]
This requires changing SWI-Prolog or working around it. With a gateway in front of TerminusDB (such as we have in TerminusX), the gateway can implement the timeout.
