### ISSUE TITLE
Not able to insert document using WOQL 

### ISSUE THREAD

**Issue by Neelterminusdb** [terminusdb/terminusdb#900]
**Describe the bug**
I was trying to insert a document using WOQL query. but was not successful and it gave the following error
This happened because we didn't pass a commit message when executing the query.

```
 "api:message": "Error: existence_error(key,message,_25678{})\n  [44] '$get_dict_ex'(message,_25730{},_25726)\n  [43] '.'(_25730{},message,_25764) at /usr/lib/swipl/boot/dicts.pl:46\
```

**To Reproduce**
1. Make a query without a commit message

**Expected behavior**
It should throw a better error so that user can know what is happening.

**Comment by spl** [comment]
I'm betting this is the same error I ran into last week when I was trying to use WOQL to insert a document. Did you include `commit_info` in your POST?

```json
{
  "query": { ... },
  "commit_info": {
    "author": "neel",
    "message": "insert this document!"
   }
}
```

Let me know if that's it. I know the error checking in the `/api/woql` endpoint needs some of the same attention I gave the other endpoints.
