### ISSUE TITLE
Improve authentication approach in integration tests

### ISSUE THREAD

**Issue by spl** [terminusdb/terminusdb#941]
Currently, the integration tests use environment variables (e.g. `TERMINUSDB_USER` and `TERMINUSDB_PASS`) for authentication. However, this is not ideal, because:

* If we want to use a different user in a test, we cannot do that, without running the whole test file again.
* We want to be able to create a new user using `admin` and then authenticate as that user and run tests as that user.
* We want to be able to use different authentication approaches in different test files: basic auth, JWT, HTTP header.

Several thoughts on how to do it:

* Simplify by assuming `admin` and `root` will always be supported unless overridden by environment variables. So, we could use `TERMINUSDB_ADMIN_USER`/`TERMINUSDB_ADMIN_PASS` if they exist or use `admin`/`root` if not. This has the side benefit of making it easier to run the tests locally, since we don't have to remember to set environment variables.
* Allow `agent.auth()` to take options which define how authentication is done. Here's a first attempt at the structure:

  1. `{"basic": {"password": <password>}, "user": <username>}`
  2. `{"bearer": {"token": <token>}}`
  3. `{"insecure": {"header": <header>}}`

  If no options are provided, we assume the authentication is `basic` and the password is `TERMINUSDB_ADMIN_PASS`/`root`. If `user` is not provided, we assume the user should be `TERMINUSDB_ADMIN_USER`/`admin`.

As far as programmatically creating a user and doing authentication with that new user, I _think_ we would do that by just creating a new `Agent` and calling its `auth()`. But I'll test that when I get to that stage.

**Comment by rrooij** [comment]
I totally agree with all of your proposals. It is a bit of a hassle to always have the ENV files set up for local testing and most of the time in development, you are using `admin/root` anyway.

Agree with the structure as well. The only thing that I found really handy now is that I can run all the tests against the different authentication mechanisms. But perhaps we can find another solution to this rather than running all the tests again with different ENV variables?

**Comment by spl** [comment]
Also, for some endpoints like `organization`, they will only work for `admin`. We should make sure that is done.

**Comment by spl** [comment]
This should include running as a non-`admin` user. So, we don't need to change the unit tests to run as a non-`admin` user (<https://github.com/terminusdb/terminusdb/issues/502>).

**Comment by matko** [comment]
It looks like this has been implemented. Closing.
