### ISSUE TITLE
Deleting an organization does not delete the database labels

### ISSUE THREAD

**Issue by matko** [terminusdb/terminusdb#954]
When deleting an organization through the api, we don't actually properly delete the databases it contains. this leaves behind unused labels.

**Comment by matko** [comment]
@GavinMendelGleason with the new interface, is this still an issue? Or is organization deletion blocked until all databases are gone?

We might have to fix it in the deprecated interface anyway, but I'm less worried aobut that.

**Comment by GavinMendelGleason** [comment]
It is blocked at the minute.

**Comment by GavinMendelGleason** [comment]
It is not blocked at the minute, but we can block it.

**Comment by GavinMendelGleason** [comment]
Fixed in #1378
