### ISSUE TITLE
Make a good workflow for integration tests that require two servers

### ISSUE THREAD

**Issue by rrooij** [terminusdb/terminusdb#983]
Fortunately we are already converting a lot of existing tests in the `routes.pl` file to the new integration tests written in JavaScript. However, some of these tests pose a challenge. A lot of the git-like feature tests require the use of two servers.

I propose that we choose one of the following options unless someone else has a better idea:

- We could require two servers to be spawned, one on port 6363 and the other one on 6364. This however, complicates running the test locally significantly for most developers. Of course, we could wrap this up in all kinds of scripts to get it easy to get running, but I think most of our developers like to have just one server running by spawning it inside `src/interactive.pl`.
- Do the approach above, but skip the Git-like tests when a ENV variable is set like `TERMINUSDB_SKIP_TWO_SERVER_TESTS`. It will probably lead to developers accidentally breaking stuff more often, but it will be catched in CI anyway.

Other ideas are appreciated as well. I think the second option might be the best.

**Comment by matko** [comment]
Closing, as by now we have integration tests which test clone, push and pull  by spawning a server, then using the CLI tool to contact this server. If we need anything more than that, it deserves a new issue.
